### ISSUE TITLE
WinPatch out of date?

### ISSUE THREAD

**Issue by faissaloo** [enigma-dev/enigma-dev#1010]
I ran into this issue when trying to test Robert's dialog cleanup. I believe enigma.jar is out of date and the gcc.ey is wrong, installing only the ENIGMAsystem stuff and the gcc.ey (with `-std=c++11` added to cxx flags) allows me to lint and creation of object files but fails at linking, telling me something along the lines of `<path to mingw-ld>: -l<whatever library> not found`

**Comment by RobertBColton** [comment]
Yes it needs updated, you can see from the date on the file it has not been updated since 2013. The main reason is that most of us just started using the ENIGMA Portable ZIP once it became available. I am not sure whose Dropbox it is even on, but it could be on the Dropbox I created for the ENIGMA team where the Portable ZIP resides. Why are you trying to install it this way though?

**Comment by faissaloo** [comment]
I was using WinPatch to try to satisfy the dependencies like zlib and libalure the compiler kept complaining about whenever I tried to install on Windows.

**Comment by fundies** [comment]
winpatch is unrelated to the code on this tracker. flag it on the wiki and close this.

**Comment by faissaloo** [comment]
>winpatch is unrelated to the code on this tracker. flag it on the wiki and close this.  
  
Except for the fact that I can't get the code on this repo working without it. It's not a wiki issue.

**Comment by fundies** [comment]
Nothing in the winpatch is our code. Enigma is a big project  with many dependencies. Go learn to compile enigmas dependencies on your own. The winpatch is a convenience created by me and maintained by @RobertBColton. It's not a requirement for running the code in this repo at all. You can get mingw, and all these libs yourself too.

**Comment by RobertBColton** [comment]
I am keeping this open because I am going to update that WinPatch or else change the directions on the wiki or some how simplify. I might rewrite install.py in bash. The website tracker is probably more appropriate for this but I'm not going to nitpick so just leave this alone.

**Comment by JoshDreamland** [comment]
I saw you put out a release. Was that to correct this?

**Comment by RobertBColton** [comment]
No it was not that was our portable ZIP which includes MinGW and git-bash with it. This here is a ZIP that you can download with OpenAL and everything already built as well as lateralgm.jar and enigma.jar then copy and paste it into enigma-dev to get ENIGMA running. The WinPatch route requires that you install MinGW (which I haven't found an installer that works with ENIGMA).

See the WIndows install page:
http://enigma-dev.org/docs/Wiki/Install:Windows

**Comment by JoshDreamland** [comment]
That zip is creating more problems than it's correcting. We should move to be rid of it.

**Comment by RobertBColton** [comment]
Really I do not understand why everyone keeps complaining about the ZIP because it is not the problem here. Installing with the ZIP is significantly simpler than using the WinPatch method and requires fewer steps. The only real problem with the ZIP that people have had is that it does not support 64 bit (yet).

**Comment by fundies** [comment]
the zip was more intended for cross compilation on linux.

**Comment by fundies** [comment]
The winpatch is unoffical tool created by myself and does not fall under scope of this tracker. There is a new one here https://github.com/fundies/enigma-libs/files/1347135/enigma-libs.zip but if you have any issue with it contact me on irc.

**Comment by RobertBColton** [comment]
We are also going to soon change the primary distribution means for ENIGMA and possibly create an installer, so this issue is really stale.

**Comment by RobertBColton** [comment]
Quick update, the install instructions no longer mention the WinPatch and we should remove any remaining references to it over time. The new instructions for setting up ENIGMA from source code using an MSYS2 subsystem can be found here: https://enigma-dev.org/docs/Wiki/Install:Windows#MSYS2
