### ISSUE TITLE
String or text functions broken?

### ISSUE THREAD

**Issue by desttinghim** [enigma-dev/enigma-dev#1032]
```
Line 67, position 26 (absolute 2337): Too few arguments to function `ord': provided 1, required 2.
```

Every function I've tried to use relating to text seems to want more arguments than Game Maker required. In fact, it contradicts the documentation. This happens with show_message() and ord(). I think it may happen on more functions but I haven't checked. Here's the project file that I am trying to compile:

https://drive.google.com/file/d/0BxHgTM9tgDLOXzRLWjZLaHZmYWs/view?usp=sharing

However, this can also be replicated by making a new project and creating a room. Inside the creation code, put 
```
show_message("Hello, world!");
```
and run the result. If that doesn't work, then something is wrong with my setup.

**Comment by faissaloo** [comment]
This could be another manifestation of #978 which has been occurring with newer GCC versions, try replacing line 22 of SHELLmain.cpp with this:  
```
#ifndef JUST_DEFINE_IT_RUN
  #include <string>
#else
  #define _GLIBCXX_STRING 1
  template<typename T, typename traits = int> class basic_string {};
  typedef basic_string<char> string;
#endif
```

**Comment by RobertBColton** [comment]
Yes, sadly we are already aware of this one because of #978. Follow @faissaloos advice.
