### ISSUE TITLE
how to change the code editor font ?

### ISSUE THREAD

**Issue by dazzulay** [enigma-dev/enigma-dev#1042]
this is shotscreen [http://i.imgur.com/tXh0y5G.png](http://i.imgur.com/tXh0y5G.png)
it was too small, i want to change the font size and font.

**Comment by JoshDreamland** [comment]
It would be better to file this bug against [LateralGM](/IsmAvatar/LateralGM). I recall that we had an options panel for this, but that it didn't make it to an actual release. There may be a key in a config file somewhere in the LGM jar that would allow you to change this. I don't really remember; it's possible that Robert might know.

**Comment by RobertBColton** [comment]
There is already a ticket filed for this.
https://github.com/JoshDreamland/JoshEdit/issues/52

**Comment by JoshDreamland** [comment]
Why is the ticket filed against JoshEdit? JoshEdit has had a panel for that for like a bajillion years. You just need a button to open it in LGM and dump the settings to your own properties file.

**Comment by RobertBColton** [comment]
There are various UI bugs you can read about in the ticket.
