### ISSUE TITLE
Tilesets only render in OpenGL and Room Transition Flickers

### ISSUE THREAD

**Issue by 9Morello** [enigma-dev/enigma-dev#1056]
I have a seamless room transition system that currently works perfectly on Game Maker 8.1. However, with ENIGMA, I get a fast (but noticeable) screen blink when the character passes the transition point.

I suspected this was related to the graphics API, so I tried changing the default. None of the alternatives worked correctly (unrelated to the blink issue from before):

**DirectX 11**: the game compiles, but I just get a black screen. Nothing seems to be rendered.
**DirectX 9**: objects appear normally, as do things drawn by them, but the backgrounds disappeared.
**OpenGL 3.3**: objects appear normally but backgrounds are completely glitched. It drew parts of it randomly on the screen.

Tested on Windows 7, running a Nvidia graphics card from 2012. If there is any more information I can provide on the issues, please ask.

**Comment by JoshDreamland** [comment]
I definitely need more information than that, but I don't know what to ask for. Can you isolate an issue? Particularly, the circumstances under which backgrounds "disappear"? Are you setting the alpha somewhere and not resetting it? Maybe ENIGMA treats that differently (I think there's a dedicated `background_alpha`, so it shouldn't be using regular image alpha). I don't have any clue what might be wrong from just this bug.

**Comment by 9Morello** [comment]
I have not used `background_alpha`, nor anything that should change the "background". Actually I meant tilesets before, not backgrounbs, sorry for that.

I just made a quick test: opened a new game, added a tile set, drew some stuff on the screen and ran the game compiled with **DX9**. Nothing appears.
https://my.mixtape.moe/djmekf.png

Same room with **OpenGL 3.3**:
https://my.mixtape.moe/vuxmnh.png

Same room with **DX11**:
https://my.mixtape.moe/djpoux.png

There are no objects running in this game and the room has no code. Just a barebones room and a few tile sets. With **OpenGL 1.1**, the tilesets do appear:
https://my.mixtape.moe/ljqptp.png

If theres anything else, please ask.

**Comment by JoshDreamland** [comment]
Okay. Are you suggesting that tilesets are completely broken? I guess I never use tilesets myself, so I shouldn't be incredibly surprised, but I mean, holy shit. Why haven't we heard about this before?

**Comment by JoshDreamland** [comment]
@RobertBColton Do you have any free cycles to look at this? This seems up your alley. I haven't budgeted the mental energy to figure out why an entire system in ENIGMA is completely busted.

**Comment by 9Morello** [comment]
Thanks for the quick answer. If there is anything else I can test, I'll be here.

**Comment by RobertBColton** [comment]
It looks like nobody/me ever moved the tile drawing stuff to general graphics, even though it could have been well implemented that way. Thus each system reimplements the functions but it looks like I didn't even do that for Direct3D 9. D3D11 should not work because I couldn't even get it to draw a triangle, the code was a WIP, it can only clear background color right now is all it does.
https://github.com/enigma-dev/enigma-dev/blob/master/ENIGMAsystem/SHELL/Graphics_Systems/Direct3D9/DX9tiles.cpp

**Comment by 9Morello** [comment]
@RobertBColton Hey, I'm happy to see you guys are working on this!
Unfortunately, I cannot test this anymore, since the project now depends on #1214 to compile.

**Comment by 9Morello** [comment]
That's awesome to hear. I'll keep tuned!

**Comment by RobertBColton** [comment]
One more part of this is fixed in #1377. The part that is fixed is that Direct3D11 does now actually draw stuff and does draw the tiles demo you shared with us previously. That leaves one issue to be looked into here and that is the flicker between room transition, which TKG has also asked about in regards to his "Key to Success" game.

![D3D11 Tile Collision Demo](https://user-images.githubusercontent.com/3212801/45460290-8670f980-b6ca-11e8-962a-25cd71794fa8.png)

**Comment by RobertBColton** [comment]
Ok, I made a test case for the room transition issues: [room-transition-state-test.zip](https://github.com/enigma-dev/enigma-dev/files/2385898/room-transition-state-test.zip)

In the test you can just press spacebar to go to the next room. There are actually more issues than just the flicker, we are also unnecessarily and incorrectly resetting the render state (draw color back to white and alpha back to 1.0).

This is what occurs in GM8.1 and GMSv1.4:
* window appears but room is black for 1 second
* "hello! 0" appears in the italic font with a reddish transparent coloring
* Press spacebar and the image stays the same for 1 second
* "hello! 1" appears in the italic font with a reddish transparent coloring

This is what occurs in ENIGMA master:
* window does not appear at all for 1 second
* "hello! 0" appears in the italic font with a reddish transparent coloring
* Press spacebar and the room goes black for 1 second
* "hello! 1" appears in the italic font but white and opaque

**Comment by RobertBColton** [comment]
I am going to close this here because the one remaining issue of this ticket, the room transition flicker, is covered more thoroughly by #1337 where I have a test for it. To know when the issue gets resolved, please follow that ticket instead.

**Comment by RobertBColton** [comment]
Alright, after testing and testing to make sure, I have merged #1387 and am certain that it resolves the black flickering mentioned here. There are remaining graphics issues and clearly we need to cleanup the render state functions so they are consistent between graphics backends but those issues are now covered by the other ticket. Cheers!
