### ISSUE TITLE
Unknown function or script `toString'

### ISSUE THREAD

**Issue by fervi** [enigma-dev/enigma-dev#1097]
```
Line 14, position 57 (absolute 300): Unknown function or script `toString'
```

Hello! Nice to see you!

My game use string function. Probably enigma replace "string" to "toString", but gcc / something don't use that function.

```
scr_set_global_main_text("You received " + string(randn) + " Spellcounters!");
```

**Comment by RobertBColton** [comment]
@fervi Duplicate issue, there's a workaround in #978 (read the forum post by Josh). This is happening in newer gcc's only, we're looking to get it fixed. I am going to close this since it's already reported, if the workaround doesn't fix it for you please let me know and I'll get Josh in here. 👍
