### ISSUE TITLE
[DS list] Read value

### ISSUE THREAD

**Issue by fervi** [enigma-dev/enigma-dev#1098]
I can't read value from DS List (or I just don't know how :D), because Game Maker use stupid combination for that

list_index[| index]
from : http://docs.yoyogames.com/source/dadiospice/002_reference/data%20structures/ds%20lists/

Do you know other way to do that? Maybe there is some replacement technology for DS List (I need - add / remove elements, shuffle, get index, value, find it, get size [i hope it is all]).

Or maybe you have alternative for this mess?

```
if(global.animation=0)
{
cardsinhand = ds_list_size(global.player1_hand);
algoritm = global.cardboard / cardsinhand;

for(i=0; i<=cardsinhand; i++)
{
/// DOWN
variable = (global.player1_hand[|i]); // OVER HERE
/// UP
variable.x = window_get_width()*0.31 + (algoritm * i); 
}
}
```

**Comment by faissaloo** [comment]
ENIGMA does not support Game Maker's accessor system (because it's very ugly), use ```variable=ds_list_find_value(global.player1_hand, i);```

**Comment by fervi** [comment]
It probably works! Thanks!
