### ISSUE TITLE
Randomize / Random_set_seed doesn't work (?)

### ISSUE THREAD

**Issue by fervi** [enigma-dev/enigma-dev#1100]
Hi

While moving the game I noticed that things that should be random are not always in the same order as randomize(). My tests (not shown on the movie) show that also the function random_set_seed does not work properly.

Check for "hand" cards and "chaos gate" effects
https://youtu.be/nkAQuEebmhU

https://i.imgur.com/alLo2Zj.gif

**Comment by fervi** [comment]
Edit: Is is probably bugged, because i have twice "var <variable>", GM:S Accept that, EGM not

**Comment by fervi** [comment]
Or maybe it fix this problem, but not randomize (deck doesn't work property)

**Comment by RobertBColton** [comment]
All of the random functions are in Universal_System/mathnc.h
https://github.com/enigma-dev/enigma-dev/blob/master/ENIGMAsystem/SHELL/Universal_System/mathnc.h#L158

We just wrap the C++ random functions to be Delphi-like. Josh wrote those forever ago and nobody has reported any problems with them. If you can though, a reproducible small test is helpful, as in a code example of how any of the random() functions don't work like GM, to help solve the issue.

**Comment by fervi** [comment]
Ok. Maybe the problem is only with DS List Shuffle (I will check it later)
http://meshnet-users.tk/paste/p/homh/a.gmk

In Enigma i have usually 5, 4, 2, 3, 1; on GM - Random

**Comment by fervi** [comment]
Little mess, closing and creating new issue
