### ISSUE TITLE
Randomize is not connect with ds_list_shuffle

### ISSUE THREAD

**Issue by fervi** [enigma-dev/enigma-dev#1107]
Hello.

The GMS Randomize affects the values created by ds_list_shuffle (they are random). Enigma randomize does not affect them. We always get the same value.

Example (if you have GMS and Enigma):
http://meshnet-users.tk/paste/p/homh/a.gmk

**Comment by RobertBColton** [comment]
@fervi for reference: https://github.com/enigma-dev/enigma-dev/blob/d5b803dbe682aee06ea499bfbf2f4cf229defd72/ENIGMAsystem/SHELL/Universal_System/Extensions/DataStructures/data_structures.cpp#L1281

**Comment by fervi** [comment]
Thanks for reply

Unfortunately I am not a programmer in C ++, I can not verify the correctness of the code - I just noticed that it is working badly.

I know some non-optimal way to solve this problem.

But maybe someday someone will fix it and that's why I reported it ;)

**Comment by RobertBColton** [comment]
Just to provide clarification to this ticket, the unit test is:
```gml
randomize();
global.player1_deck = ds_list_create();
ds_list_add(global.player1_deck,1);
ds_list_add(global.player1_deck,2);
ds_list_add(global.player1_deck,3);
ds_list_add(global.player1_deck,4);
ds_list_add(global.player1_deck,5);
ds_list_shuffle(global.player1_deck);
```

In GameMaker: Studio I get different results each execution of the game, but not if I comment out the first line calling `randomize()`, as you indicated:
![image](https://user-images.githubusercontent.com/3212801/31514490-c378e1da-af5f-11e7-8ae2-7dd2fd6b0601.png)

I confirm that I can reproduce the issue with ENIGMA whereby even with the `randomize()` call I always get the same order over and over and over:
![confirmed](https://user-images.githubusercontent.com/3212801/31514527-de92b482-af5f-11e7-96de-cff29f524cee.png)

The GameMaker: Studio documentation does make this clear that `randomize()` should be called during testing and debugging:
https://docs.yoyogames.com/source/dadiospice/002_reference/data%20structures/ds%20lists/ds_list_shuffle.html

I don't know what the behavior was in previous GameMaker versions:
http://gamemaker.info/en/manual#ds_list_shuffle

Regardless, `ds_list_shuffle(...)` is clearly not randomizing at all in ENIGMA.

**Comment by RobertBColton** [comment]
@fervi Thanks, this is actually an easy one to fix with your reproducible.

Issue is, source I linked above `random_shuffle` is deprecated in C++14 and also we were never calling the random function for it. So not only does the random need fixed, it also needs to use `std::shuffle` instead.
https://meetingcpp.com/blog/items/stdrandom_shuffle-is-deprecated.html

I'll forward this to @JoshDreamland and take a look at it later.

**Comment by RobertBColton** [comment]
Alright, #1270 has been merged and it does fix the original issue reported here. If you simply do a `git pull` you should be able to use the functions without any problems now and they should be correctly randomized.
