### ISSUE TITLE
Os_browser should return -1

### ISSUE THREAD

**Issue by fervi** [enigma-dev/enigma-dev#1108]
Hello.

My game recognizes whether someone started the game on the browser or not. Of course, Enigma does not support browsers. However, in the context of compatibility with evil incarnate - should return the same.

```
// Enigma return nothing (?? or zero maybe, but it doesn't show results), GMS "-1"
draw_text(10, 10, string(os_browser));

// It's good - Enigma and GM return "Not a bowser"
if os_browser == browser_not_a_browser
{
draw_text(10, 25, "Not a bowser! :)");
}
```

**Comment by RobertBColton** [comment]
It's just not implemented with the other constants, at all.

**Comment by RobertBColton** [comment]
Alright, #1444 implements it even though it's not really needed yet, it makes it a little simpler to convert projects to ENIGMA.

![Browser Constant Initialized](https://user-images.githubusercontent.com/3212801/48744783-b262ab00-ec36-11e8-93f5-939080f7f3fa.png)
