### ISSUE TITLE
'S_IRGRP' was not declared in this scope

### ISSUE THREAD

**Issue by RobertBColton** [enigma-dev/enigma-dev#1156]
Looks like #1143 introduced a regression. I get this every time I open LGM now:

```
Owner@DESKTOP /c/Users/Owner/Desktop/ENIGMA/enigma-dev (UniversalResourcesDir)
$ make
c:/Users/Owner/Desktop/ENIGMA/mingw32/bin/make -C CompilerSource
make[1]: Entering directory `c:/Users/Owner/Desktop/ENIGMA/enigma-dev/CompilerSource'
mkdir.exe -p .eobjs/./
mkdir.exe -p .eobjs/./JDI/src/API/
mkdir.exe -p .eobjs/./JDI/src/General/
mkdir.exe -p .eobjs/./JDI/src/Parser/
mkdir.exe -p .eobjs/./JDI/src/Parser/handlers/
mkdir.exe -p .eobjs/./JDI/src/Parser/readers/
mkdir.exe -p .eobjs/./JDI/src/Storage/
mkdir.exe -p .eobjs/./JDI/src/System/
mkdir.exe -p .eobjs/./JDI/test/
mkdir.exe -p .eobjs/./backend/
mkdir.exe -p .eobjs/./compiler/
mkdir.exe -p .eobjs/./compiler/components/
mkdir.exe -p .eobjs/./compiler/event_reader/
mkdir.exe -p .eobjs/./compiler/reshandlers/
mkdir.exe -p .eobjs/./filesystem/
mkdir.exe -p .eobjs/./gcc_interface/
mkdir.exe -p .eobjs/./general/
mkdir.exe -p .eobjs/./languages/
mkdir.exe -p .eobjs/./parser/
mkdir.exe -p .eobjs/./settings-parse/
mkdir.exe -p .eobjs/./syntax/
g++ -std=c++11 -Wall -O3 -g -I./JDI/src -I. -MMD -MP -c -o .eobjs/./compiler/compile.o compiler/compile.cpp
compiler/compile.cpp: In function 'void write_desktop_entry(std::string, const GameSettings&)':
compiler/compile.cpp:116:47: error: 'S_IRGRP' was not declared in this scope
   chmod((fPath + ".desktop").c_str(), S_IRWXU|S_IRGRP|S_IXGRP|S_IROTH);
                                               ^
compiler/compile.cpp:116:55: error: 'S_IXGRP' was not declared in this scope
   chmod((fPath + ".desktop").c_str(), S_IRWXU|S_IRGRP|S_IXGRP|S_IROTH);
                                                       ^
compiler/compile.cpp:116:63: error: 'S_IROTH' was not declared in this scope
   chmod((fPath + ".desktop").c_str(), S_IRWXU|S_IRGRP|S_IXGRP|S_IROTH);
                                                               ^
make[1]: Leaving directory `c:/Users/Owner/Desktop/ENIGMA/enigma-dev/CompilerSource'
make: *** [ENIGMA] Error 2
```

**Comment by fundies** [comment]
That line compiles in appveyor so looks like your mingw is out of date / buggy.

**Comment by fundies** [comment]
you can wrap that line in an if not windows macro if you want as chmod doesn't actually do anything on windows

**Comment by RobertBColton** [comment]
Hold on to your ass man, I haven't even had a second to look further into this. But no I can't do that because you want to write the desktop entry if you cross-compile from Windows for Linux. Or will what you are saying still work? I need a check to tell me if my target is Linux... that is statically analyzed at compile time...

**Comment by fundies** [comment]
itll still write the file without that line it. that line just sets the executable bit on the file which is a linux only thing. ntfs doesnt support it.

**Comment by RobertBColton** [comment]
I see, thank you, I will test it and send the pr when I get a chance.

**Comment by RobertBColton** [comment]
@fundies Ok, I have a couple of questions.

1. Why are you even setting the file permissions on the file? Since it's using the standard I/O the file permissions should be correct already, no? If the line isn't needed we should just remove it.
2. If I use a cross-compiler for Linux or MinGW on Linux will it report a different operating system for the OS preprocessor macro? Or do they report the operating system they are compiling from? If it's the former, I'd rather wrap this whole thing in the Macro so that it only runs on Linux or when you are cross-compiling **_for_** Linux.

**Comment by fundies** [comment]
Because you need to set it executable on linux or the file manager bitches that its not executable when you try to open. 2 is exacty what I told you to do

**Comment by RobertBColton** [comment]
Oh, well instead of using those constants (for read/write which are already set), we could query the one's set first and then or it with the one just for file execution. But I'd rather just use the not windows macro because it doesn't even need done on Windows, and hopefully that will work in any potential Windows->Linux cross-compiler. Can I do the same thing so that the Windows icon is not written unless Windows is defined? Will that work with MinGW on Linux, as in, will it pretend that it's Windows?

**Comment by fundies** [comment]
just put ifndef #win32 around that line all u needa do.  its not rocket science

**Comment by RobertBColton** [comment]
If we add a cross-compiler for Linux to Windows though, will it write the desktop entry? I'd want it to.

**Comment by fundies** [comment]
learn to read I told u 5x already the cmod cmd only sets executable bit on the file. It wont work on windows. Windows will still generate the file without that line but as with any script you transfer from windows to linux they'll need to chmod+x it on linux

**Comment by fundies** [comment]
Windows is a turd. ntfs is a turd. theres nothing that can be done so just put macro like i said and itll write the file to best of window's handicap

**Comment by RobertBColton** [comment]
Right, but can I do this also for Windows exe? So I can disable it from Linux, except when cross-compiling for Windows? I want to do that too all in same PR since is technically correct. Thanks!

**Comment by fundies** [comment]
this is in the plugin. the plugin only compiles for the os youre on...

**Comment by RobertBColton** [comment]
Wait so your cross-compiler for Windows doesn't write exe icon? I think it should... because it can? Since Windows embeds it in the exe... I mean the file is fubar on Linux either way.

**Comment by fundies** [comment]
youre retarded. come to irc n ill explain

**Comment by RobertBColton** [comment]
Closing this as resolved for now. We may need to come back later and discuss @rpjohnst's idea to use ZIP files to preserve file permissions across platforms. But we'll discuss that when we look into packaging games and creating MSI installers. This issue is resolved!
