### ISSUE TITLE
Circle CI?

### ISSUE THREAD

**Issue by RobertBColton** [enigma-dev/enigma-dev#1167]
Just a thought, I could add Circle CI for Mac tests... We could also offload some of the Linux jobs to Circle CI or use it purely for the test harness.

# Advantages
* The test harness code would be in its own CI system and not convolute the Travis YAML we already have.
* Circle CI is entirely free for open source, you get 3 Linux containers and 1 Mac container:
https://circleci.com/pricing/#build-os-x
* Builds may complete faster because Circle CI might have a less taxed Mac backlog and Travis also wouldn't be overloaded with Mac and the test harness tests.
https://circleci.com/docs/2.0/testing-ios/
# Disadvantages
* We would have 3 separate CI files and that may be a bit much to maintain due to the public's general lack of familiarity with these services.
* Using a less popular CI system may mean that I'll hit more roadblocks setting it up.

**Comment by JoshDreamland** [comment]
Too expensive for what it's worth. If Apple can't get off their asses and support the software development community a little better, then fuck their platform. For the price of each month of service with Circle, I can buy my own Mac Mini. Even if reimaging them takes four hours, I could just buy a dozen of them and do it in a ring-buffer fashion.

**Comment by RobertBColton** [comment]
> I could just buy a dozen of them and do it in a ring-buffer fashion.

Is this technical jargon for "I'm going to run a train on Travis in circle-jerk fashion"?

**Comment by JoshDreamland** [comment]
No; it's a statement that their service costs more than refreshing the hardware required to run it, monthly.

**Comment by faissaloo** [comment]
>For the price of each month of service with Circle, I can buy my own Mac Mini. Even if reimaging them takes four hours, I could just buy a dozen of them and do it in a ring-buffer fashion.  
  
It's situations like this that makes me excited for https://github.com/darlinghq/darling , besides it would be cheaper to just run a hackintosh (not that I'm saying you should do that because obviously that would be violating EULAs and that's bad and stuff).
