### ISSUE TITLE
Build system is not parallelized by default

### ISSUE THREAD

**Issue by RobertBColton** [enigma-dev/enigma-dev#1173]
These are some issues I get if I delete `CompilerSource/.eobjs` and `enigma-dev/compileEGMf.dll`:

1) Compiling compileEGMf.dll is taking forever now, it used to be so quick I couldn't screen cap it. I think it's @fundies fault for removing `-j 3`: https://github.com/enigma-dev/enigma-dev/commit/bc3dac10a9ce7343d9e906ff032355ba4bc9c570#diff-b67911656ef5d18c4ae36cb6741b7965L6

2) Git is now trying to commit output_log.txt since Josh removed it from .gitignore: 44dc72da8a424aa1f3726df9100208e0dc925c14
This file is created by the Windows executable that launches LateralGM: https://github.com/enigma-dev/enigma-dev/blob/83bffa133def3f3621f47930a8eb224a53de95ad/CompilerSource/windows-executable/main.cc#L450

**Comment by RobertBColton** [comment]
I've readded output_log.txt to gitignore as part of #1170: 3fbd182045b7f406e679542acb2102679b80ca3c

**Comment by fundies** [comment]
You can call make -j4 yourself. no reason for it to be in that file

**Comment by RobertBColton** [comment]
The problem is it slowed down LateralGM doing it, so how is LateralGM doing it. I wonder if it's in the plugin... Why exactly did you delete it though?

**Comment by faissaloo** [comment]
Yeah it slowed it down *for you*, you should at least be using the number of cores to decide how many threads to run rather than an arbitrary number, in fact this should be a plugin option with a default of something along the lines of `max(1, cores - 1)`

**Comment by RobertBColton** [comment]
That makes sense @faissaloo, however, I assumed that even if more cores were not available, GNU make would be able to safely fall back to behaving as if the option was not present? Thus, I believe @JoshDreamland told me before that it was fine to just set it higher because it will still work even if you don't have multiple cores.

**Comment by faissaloo** [comment]
It shouldn't because it's not unsafe, it's just impractical because you'll end up with the CPU task switching constantly. You can test this quite easily though, time a build with like 4x the number of threads as cores on your CPU, then time it with -j at the number of cores in your CPU.

**Comment by RobertBColton** [comment]
Which of those are you saying would be faster? The 4 x concurrent jobs one? Or would that one be slower because of thrashing?

On that same topic, I think it should still be fine to put it back to -j4 for now. The reason being is that only 4 is not enough to cause thrashing on systems without multiple cores (right?), but good enough to improve the performance for those with multiple cores. I see -j4 as a nice middle ground that I think does work for a lot of projects as the reasonable default.

My other question is that if we did tell the plugin to call make using -j4 instead, would that be passed along when we call make inside the makefiles? If not we're going to need a whole lot more refactoring. I kind of hate that GNU Make can't just pick a reasonable default, I don't like this at all, but I understand it's been kept this way for backwards compatibility.

**Comment by faissaloo** [comment]
The 4x concurrent jobs one should be slower.

**Comment by RobertBColton** [comment]
Ok, I am in favor of doing some variation of what MSVC does in our root enigma-dev Makefile and propagating it to the lower makefiles. This way it will be a reasonable default, given the user's number of real processing cores, and they can easily change it to something special if need be in a single location. I don't see a real good reason for putting that anywhere in the UI, but we can like Visual Studio, down the road or something.

**Comment by fundies** [comment]
call make -j4 yourself in msys2 (or enigma.jar) and you'll see it trickle down to other make. Running make -j4 from enigmas root to build plugin to me 26 seconds where as just make was 1minute 10 seconds

**Comment by RobertBColton** [comment]
No, we just discussed how -j4 is not appropriate for everybody. We need to copy MSVC's solution over to our makefile:
> It spawns MIN(numFiles,NumProcs) copies of itself and each of those child processes grabs a source file and starts compiling.

But then it wouldn't work if you cd to CompilerSource and run make there yourself. So what we probably need to do is put the real processor counting into a bash script and just include that or alias make to it or something.

**Comment by fundies** [comment]
What If I dont want to use all my cores? Honestly, I'd just leave it be its not like you build the plugin every day and if youre in a rush you can call make -j4 from cmd prompt yourself

**Comment by faissaloo** [comment]
>What If I dont want to use all my cores?  
This is exactly why it needs to be part of the GUI. Something so basic shouldn't require the user messing with the shell, in fact we should be actively working to reduce how much the user needs the shell.

**Comment by RobertBColton** [comment]
I suppose, but I mean, my argument is just that if Visual Studio thinks it's reasonable to do that once you enable parallel build, I don't get why we can't just make it that simple? I am fine with having the UI options to tweak it too, I just meant that for the most part, the detailed ones can be buried/hidden and we can mostly just go with a simple checkbox etc.

For example: Just a checkbox somewhere under ENIGMA Settings saying "Enable parallel build" then a second checkbox that says "Limit concurrent jobs" with a textfield next to it that is enabled when it is checked.

> so simple shouldn't require the user messing with the shell

Sorry, I don't think I'm being clear, I was more so saying we could make it as simple as having in just a single makefile "JOBS=0" or something where the user only needs to edit it in one place. I hope that makes sense what I meant now?

Really I just mean that we should make it as simple as Visual Studio does:
![Visual Studio Parallel Build](https://user-images.githubusercontent.com/3212801/35358272-0b89e27e-0124-11e8-8d45-3850eb1f1519.png)

**Comment by faissaloo** [comment]
Ah then yes, that would be a good solution imo.
