### ISSUE TITLE
Running the game in CI build

### ISSUE THREAD

**Issue by RobertBColton** [enigma-dev/enigma-dev#1176]
Why exactly did we decide not to run the game in continuous integration? While working on #1175, which currently has a segmentation fault on an empty game, I realized that my changes were still passing AppVeyor and Travis. I think we should maybe change this to let the game open and check its return code, to make sure they not only compile but at minimum open without a segfault.

**Comment by fundies** [comment]
because the test harness didn't exist yet

**Comment by RobertBColton** [comment]
And is the test harness going to check every single extension that's tested in CI?

**Comment by JoshDreamland** [comment]
It just builds with all of them. If you want test coverage for your extension, write a test game that uses it. There are two mechanisms for doing that. They're simple to figure out; feel free to add documentation.

**Comment by RobertBColton** [comment]
That does make sense then, thanks for clarifying Josh.
