### ISSUE TITLE
ENIGMA GUI Extension lacks documentation on how to use it

### ISSUE THREAD

**Issue by 9Morello** [enigma-dev/enigma-dev#1177]
ENIGMA seems to have an extension called "Basic GUI", which is used to create basic elements such as buttons, labels, scrollbars, etc. (according to its own description).

However, I couldn't find any guide or documentation about it. [This wiki page](https://enigma-dev.org/docs/Wiki/GUI_Functions) was the only related page I found and it seems outdated. Was it ever implemented or is option to enable it in LateralGM just a placeholder?

**Comment by TheExDeus** [comment]
I didn't manage to write doc's for them all. Right now for learning you can try the example here: https://enigma-dev.org/forums/index.php?topic=2450.msg25287#msg25287

Some visual examples without code (sadly): https://enigma-dev.org/forums/index.php?topic=2492.msg25035#msg25035

The example code I had is probably berried somewhere deep in by ssd.

**Comment by 9Morello** [comment]
@TheExDeus Thanks for the fast answer. I thought the extension worked with native-like appearance (like using the user's GTK theme if he was using GNU/Linux, etc.), but from the examples, it looks like the users implements them themselves, right?

Are you still working on it?

**Comment by RobertBColton** [comment]
For GTK you would want to set "Widget Systems" though we do not have a comprehensive set of regular GUI functions for those systems, just the basic dialogs. BasicGUI is intended for your actual game's UI because it leverages the same tools as the actual game. There are really advantages and disadvantages to both, but for actual in-game menus you want to use BasicGUI probably.

**Comment by TheExDeus** [comment]
Yeah, it was meant to make game UI, not tool UI like GTK or QT. This is for in-game menus, inventory systems and so on. They can be blended using GL and shaders and render extremely fast using batching. I added all the functions I needed to make the tools I needed, so I haven't worked on it for a while now.

**Comment by 9Morello** [comment]
I see. I'll close this issue, since I thought the extension was meant for typical system UI. Thanks for the help.
