### ISSUE TITLE
GMX File Paths

### ISSUE THREAD

**Issue by RobertBColton** [enigma-dev/enigma-dev#1189]
Ok, so I want to have a quick conversation about this so I can get the FPS example loading. I was going to add the missing piece, image data, but that requires dealing with the file paths. So the way we have the protos now is that the background proto simply holds the file path to the image data:
https://github.com/enigma-dev/enigma-dev/blob/9aa9ecaf504fa029cc065e3427ba165e443f35e7/CommandLine/libGMX/resources/Background.proto#L30

This is a relative path as loaded by the GMX loader, i.e. "images/background0.png" but for me to load it at the point the Proto2ES conversion takes place, I would need the full file path to pass to an image loader. So there's several options then:

1) I could make the GMX loader do the image loading since it has the full path on hand at that time. That however overcomplicates the GMX loader and also requires that I add it to every other reader too, duplicating a lot of stupid shit.
2) I could make the GMX loader convert the relative paths to full paths first, which kinda has the same issue as number 1, but is even worse because it makes it difficult to share the protos over a network.
3) Could add it to Proto2ES directly, so all the formats can just specify the file path, but then the Proto2ES conversion function also needs to know the file path of the project that its converting to construct full paths.
4) Could make the image data section for backgrounds and sprites have a oneof so that it can optionally be the file path or it can be the bytes directly. I think this option would make it even easier to share the protos over a network.

Let me know what combination of the above I should do before I do this. Once this kink is worked out we can load sounds and images and I can basically make the FPS example load completely.

**Comment by RemoveRusky** [comment]
4 sounds like a good idea to add but it will require fixing the paths in the gmx reader or proto2es. I think you should implemented for and to fix the paths you should add a "data" attribute to crap  and put an if check in gmx reader. if (is data) str = gmxpath + str;

**Comment by RobertBColton** [comment]
Lol, ok, but please read number 2 and 3, because it might make more sense to convert to full paths or give proto2es the ability to do that, so that all the potential file readers we make won't load image data, but expect either proto2es or the compiler to do it. That way libEGM, libGMX, libGMK don't all independently have to link the image loader, thus decreasing executable size of ENIGMA. Know what I'm sayin?

**Comment by RemoveRusky** [comment]
I did read them. Anyways the gmx loader should fix the paths as I said. The paths should be correct in the protobuf imo. Also you shouldn't need any image loaders to pack they bytes. Just pack them as is. You don't need to convert png to bmp before packing as enigma can handle that.

**Comment by RobertBColton** [comment]
Sorry, how do you know it does? I may be going about this wrong because I am basing this off of the outdated plugin, written before TheExDeus wrote a texture packer, where the image writing code converted the images to BGRA (GM's internal image format):
https://github.com/enigma-dev/lgmplugin/blob/ccc750ac54745d05599299549c13a29d91b659d4/org/enigma/EnigmaWriter.java#L1080

**Comment by RemoveRusky** [comment]
enigmas not set up to do it currently but the fuctions are there. https://github.com/enigma-dev/enigma-dev/blob/master/ENIGMAsystem/SHELL/Universal_System/lodepng.h#L116

**Comment by RobertBColton** [comment]
Ok, but I'm not going to do that right now, I will put it in proto2es for now, since we plan on moving all that to the compiler later anyway. For now, I will correct the paths to be project relative in the GMX loader and then proto2es will load and convert the image datas to BGRA. We can tack on more complicated things later on, this is the best way to do it.
