### ISSUE TITLE
Tree Structure

### ISSUE THREAD

**Issue by RobertBColton** [enigma-dev/enigma-dev#1194]
Ok, this is something that needs to be fleshed out for the protocol format.

* **Consistency**: There are many differences between the project trees pictured from GM 5, GM 8.1, GMS 1.4, and GMS 2. Do we want a consistent tree regardless of which format the user loads , or do we want the tree to appear different for each format.
* **Customization and i18n**: If we choose to enforce consistency, then that may restrict the user from moving the tree around or customizing it by modifying their project file. And that is also where i18n comes in, because if we disallow the user to customize the tree by modifying the project file, then they can't do their own localization of the tree, and thus we have to localize it like we do the rest of the UI, which is also acceptable.
* **Integrated with the resource lists or separate**: Also, we can obviously have `Project.proto` structured in two ways, where there's a list for each resource type, and the tree is separate. The alternative is to have only the tree, but then that requires that Proto2ES and later the CompilerSource do a DFS traversal of a tree instead of linearly iterating a list. So we can have the lists and the tree, or just the tree. If we keep the tree separate, then that means the user could _optionally_ include the tree structure in their game to use that resource_load/resource_unload group functionality we discussed. Which makes sense because there's not really a reason to write the tree into every game if not every game uses it.
* **Redundancy**: Finally, we don't even have to include the tree in the protocol format at all and can leave it entirely up to the frontend. However, one other advantage, in addition to being able to easily include it in the game, is the fact that we know all of the frontends will be using the same tree loading code which reduces code redundancy.

![GM 5](https://user-images.githubusercontent.com/3212801/36700393-85b18026-1b1d-11e8-9ab3-da4b4d6c55a7.png) ![GM 8.1](https://user-images.githubusercontent.com/3212801/36700410-97e1ba04-1b1d-11e8-91c9-02c14bd868d0.png) ![GMS 1.4](https://user-images.githubusercontent.com/3212801/36700475-ccc285b4-1b1d-11e8-8d81-5e8f8413990e.png) ![GMS 2](https://user-images.githubusercontent.com/3212801/36700517-ee5c3788-1b1d-11e8-847f-0264d03bf0d4.png)

**Comment by RemoveRusky** [comment]
I don't get half of what your're talking about. Add support for all the gm shit + (anything new in egm) in the tree and warn about truncating data on saving to older formats that don't support things in newer format

**Comment by RobertBColton** [comment]
Here's what I am trying to describe, the fact that the tree structure is recursive, so how are you going to force the consistency? How are you going to code that consistency (Sprites followed by Backgrounds before Objects then Rooms, etc.) into the following proto:

```proto
message TreeNode {
	repeated TreeNode children = 1;
}

message Project {
	optional TreeNode tree_root = 1;
}
```

**Comment by JoshDreamland** [comment]
My vision for the resource tree was that it would be fully customizable, but that we would provide a mode that creates virtual Sprite/Sound/Object/etc (category) folders which each contain duplicates of the entire tree structure, filtered by resource type. We would localize only that mode.

**Comment by RobertBColton** [comment]
Ok, so you want the best of both worlds, I'm fine with that. But that begs the question, when the logical view is applied, do we just swap them in for the root nodes? For example the user-created "Sprites" root child, do we just swap that out for our logical one?

**Comment by RobertBColton** [comment]
I'm closing this because we already have the first version working and we know how we're going to do the rest of it now. There's no more need for a discussion on this.
