### ISSUE TITLE
Broken fullscreen from Game Settings

### ISSUE THREAD

**Issue by fervi** [enigma-dev/enigma-dev#1201]
Hello. I noticed a small error in Enigma-Dev, which should be patched one day;)

You can enable fullscreen in Game Settings. The game is scaled to full screen, but it is not stretched. (Bad)
http://meshnet-users.tk/paste/p/hoqe/g.png
However, if we use the screen_set_fullscreen function, the game runs in full screen without problems. (Good)
http://meshnet-users.tk/paste/p/hoqe/u.png

Devuan Ceres 64 bit (Linux) with Nouveau Drivers
Fervi

**Comment by faissaloo** [comment]
Duplicate: https://github.com/enigma-dev/enigma-dev/issues/1069

**Comment by fervi** [comment]
I see ;)
