### ISSUE TITLE
Begin/End Parsing

### ISSUE THREAD

**Issue by RobertBColton** [enigma-dev/enigma-dev#124]
if mm > 0
begin
    pX /= mm;
    pY /= mm;
    pZ /= mm;
end;
else 
begin
    x_2d = 0;
    y_2d = -100;
    return 0;
end;

That code is perfectly valid in Game Maker it comes from several examples by Phantom107 that are quite popular over on the GMC. ENIGMA has a fit and outputs this....

Preprocessor_Environment_Editable/IDE_EDIT_objectfunctionality.h: In function ‘variant _SCR_convert_3d(variant, variant, variant, variant, variant, variant, variant, variant, variant, variant, variant, variant, variant, variant, variant, variant)’:
Preprocessor_Environment_Editable/IDE_EDIT_objectfunctionality.h:86:5: error: ‘else’ without a previous ‘if’
Preprocessor_Environment_Editable/IDE_EDIT_objectfunctionality.h: In function ‘variant _SCR_convert_2d(variant, variant, variant, variant, variant, variant, variant, variant, variant, variant, variant, variant, variant, variant, variant, variant)’:
Preprocessor_Environment_Editable/IDE_EDIT_objectfunctionality.h:117:5: error: ‘else’ without a previous ‘if’
In file included from SHELLmain.cpp:103:0:

**Comment by RobertBColton** [comment]
The same error is still thrown on master even though begin/end are implemented because of the semicolon on the end before else.

**Comment by JoshDreamland** [comment]
ENIGMA's errors are valid... I have no idea why GM is allowing that. Does it allow a semicolon after a `}` before `else`?

**Comment by RobertBColton** [comment]
I tried the following:
```gml
if (true) {
  show_message("true");
}; else {
  show_message("false");
}

if (false) {
  show_message("false");
}; else {
  show_message("true");
}

if (true) begin
  show_message("true");
end; else begin
  show_message("false");
end

if (false) begin
  show_message("false");
end; else begin
  show_message("true");
end
```
* GM 5 says true, true, true, true

**Comment by JoshDreamland** [comment]
Then I suppose ENIGMA's syntax checker also doesn't care if you say, eg,
```GML
if (foo)
  a = 1;
  b = 2;
else
  a = 2;
  b = 1;
```

Which is obviously completely wrong....

**Comment by RobertBColton** [comment]
The syntax checker does not throw any errors. GM 5's does though.
