### ISSUE TITLE
GMK/Emake image loading issues

### ISSUE THREAD

**Issue by RemoveRusky** [enigma-dev/enigma-dev#1254]
I tried to run http://files.enigma-dev.org/game/69/file/1/0be4e3/Source/platform_engine.gmk from the edc using emake and I get 

ERROR in some action of some event for object -4, instance id -4: Zerror: Output of 16 above allotted 16
ERROR in some action of some event for object -4, instance id -4: Sprite load error: Sprite does not match expected size

but I can run the same game from lgm fine.

**Comment by RobertBColton** [comment]
Fixed by #1269
