### ISSUE TITLE
LGM crashes on compile

### ISSUE THREAD

**Issue by rcobraone** [enigma-dev/enigma-dev#1276]
hi, LGM in crashes on button run or debug , i saw that there were similar topics, unfortunately those solutions did not help

ENIGMA Version: commits 4,216

LateralGM Version: 1.8.40

Operating System: Linux Mint 18.3 Sylvia
Version: Linux 4.13.0-43-generic (i686)
Architecture: i386

Java Version:
java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) Client VM (build 25.171-b11, mixed mode)

GCC Version:
gcc (Ubuntu 7.3.0-21ubuntu1~16.04) 7.3.0

[file1.txt](https://github.com/enigma-dev/enigma-dev/files/2621883/file1.txt)

**Comment by RobertBColton** [comment]
@rcobraone I believe it has to do with 32 bit. Is your Oracle Java installation 32 bit? You must use a Java that has the same 32 or 64 bit architecture as the `compileEGMf.so`.

Your architecture says i386 in the log, which is 32 bit. Working with you on another issue recently, it sounded as though you got the setup working. Is this that same setup, or a new setup? If this is the same setup, then what did you change between then and now?

### Pro tip: https://gist.github.com/ would make it much easier to read and diagnose your issues/bug report logs.

**Comment by rcobraone** [comment]
yes this is the same configuration except system updates, I have not changed anything but at the beginning I had a problem with launching LGM

Well, forgive me for mistakes I'm not a programmer

**Comment by rcobraone** [comment]
no, I had problems starting LGM from the very beginning and lgmplugin.
I suspect that this may be a change to the new version of the compiler or it needs a LGM version of 32 bit

**Comment by RobertBColton** [comment]
Ok, please try a couple of things here:
```
cd enigma-dev
git pull
make clean
make all -j4 disable_server=true
```
And then give it another go, we've changed a couple of things since you did this setup.

**Comment by rcobraone** [comment]
I did not write before, but emake works, but from what I see is a bit limited but fast
I have a question whether emake supports game settings from LGM?
Have you ever thought about using write enigma IDE in Python and wxPython?

**Comment by RobertBColton** [comment]
It does not support game settings yet, we hard code them for right now:
https://github.com/enigma-dev/enigma-dev/blob/624d84c0c708d5d7db862cdf97640a3618f0917b/CommandLine/emake/Proto2ES.cpp#L346

We will be adding them, but are still working on the new EGM format. I am also cleaning some things up in the engine before I finish the YYP support, then I intend to jump back on RadialGM full time again. That's my current game plan/strategy.

>Have you ever thought about using write enigma IDE in Python and wxPython?

I helped fundies and the old forum user canthelp do that before with PyQt:
https://enigma-dev.org/forums/index.php?topic=1476.msg14590#msg14590
This, however, no longer works, as it uses the old backend like LGM still does. It was based on all of our outdated tech, so it would be better to start over. But thanks to the new flexibility of libEGM/emake it's much easier now for anybody to make an IDE that can load GM projects and pass them to our command line.

One of the other major points to our new protos is not just making the project format readers easier, but also making them scalable so people can write third party IDEs/applications/tools for ENIGMA and we can still change the project format and compiler communication _without_ breaking anybody!

**Comment by rcobraone** [comment]
ok, thanks to all for the development of the enigma

hi, I made updates linux mint 18.3 (32bit an 64bit), and configure enigma is emake build broken

enigma-dev commits 4.270 ok build worked (32bit an 64bit)

from the version enigma-dev commits 4.276 make build broken (32bit an 64bit)

1. netbook version 32bit LGM started is worked and build broken (yes i checked updated java new version)

2. my new laptops in version 64bit LGM started is worked and build


check log build emake in version 64 bit

**Comment by rcobraone** [comment]
ok, thanks to all for the development of the enigma

hi, I made updates linux mint 18.3 (32bit an 64bit), and configure enigma is emake build broken

enigma-dev commits 4.270 ok build worked (32bit an 64bit)

from the version enigma-dev commits 4.276 make build broken (32bit an 64bit)

1. netbook version 32bit LGM started is worked and build broken (yes i checked updated java new version)
2. my new laptops in version 64bit LGM started is worked and build
check log build emake in version 64 bit
[log.txt](https://github.com/enigma-dev/enigma-dev/files/2498303/log.txt)

**Comment by RobertBColton** [comment]
I recommend trying specifically the same Java version I am using on Windows, and downloading the Oracle version.
```
$ java --version
java 9.0.4
Java(TM) SE Runtime Environment (build 9.0.4+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.4+11, mixed mode)
```

**Comment by rcobraone** [comment]
probably once again incomprehensibly I wrote, I apologize in advance

ok, I checked build emake new update enigma-dev commits 4.239 is broken, there seems to be a problem with the libboost library there is a conflict of dependence between the old and the new version

1. LGM on linuxmint 18.3 (64bit) is worked (run and compile build game)

java -version
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-8u181-b13-1ubuntu0.16.04.1-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)

2. my old netbook on linux mint 18.3 (32 bit), LGM is worked run i checked with openjdk and oracle java, but if I want to build game, it crashes

**Comment by rcobraone** [comment]
probably once again incomprehensibly I wrote, I apologize in advance

ok, I checked build emake new update enigma-dev commits 4.239 is broken, there seems to be a problem with the libboost library there is a conflict of dependence between the old and the new version

1. LGM on linuxmint 18.3 (64bit) is worked (run and compile build game)

java -version
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-8u181-b13-1ubuntu0.16.04.1-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)

2. my old netbook on linux mint 18.3 (32 bit), LGM is worked run i checked with openjdk and oracle java, but if I want to build game, it crashes

**Comment by RobertBColton** [comment]
Ok, coming back to this one again, I see you posted #1557, which I helped you with just recently. I see you were also using 32 bit Linux Mint there as well. Since everything was working with you last we spoke and this issue here is older, I presume it is resolved. Since I have no reason to assume the issue still persists, I am going to close this one! 😺
