### ISSUE TITLE
SDL on Mac not working when trying to run from LGM instead of emake

### ISSUE THREAD

**Issue by time-killer-games** [enigma-dev/enigma-dev#1325]
SDL on Mac when running from LGM produces the following errors in the compile form:

https://pastebin.com/eAhESkw8

Doesn't happen when building with emake. But emake currently can't handle very large projects like LGM can, which is a different bug of its own but not the focus of this ticket.

Seems to be an issue with mouse, cursor, and window related functions.

**Comment by RobertBColton** [comment]
This must be Mac specific because I can use it fine over here on Windows.
```cpp
if (keyboard_check(ord('1'))) {
	window_mouse_set(0, 0);
}
if (keyboard_check(ord('2'))) {
	display_mouse_set(0, 0);
}
```

Do those functions work in GM on Mac?

**Comment by time-killer-games** [comment]
Yes those functions work in GM4Mac

**Comment by RobertBColton** [comment]
Understood, I totally wouldn't have guessed that, so thank you very much for clarifying. I'll maybe try to help you guys look into this.

**Comment by time-killer-games** [comment]
Yes, that is the branch I pulled from. It didn't fix these errors. These errors I get from that branch. I don't know what would happen if I pulled from master because I haven't tried that, fundies said it didn't work in master.

**Comment by fundies** [comment]
This specific to @time-killer-games being a dummy and launching lgm in different env than emake. One without pkg-config. You can close this

**Comment by time-killer-games** [comment]
Well excuse me for being dum enough to do as you tell me to. :P (jk)

**Comment by time-killer-games** [comment]
@fundies how many months did you wait to inform us of this exactly? What purpose did that serve?

**Comment by fundies** [comment]
It can be run in lgm. You just need to launch lgm from the same place you launch emake. Also, I did try telling you this before but my account was banned by someone and then I forgot

**Comment by time-killer-games** [comment]
Well just be happy to know I'm not going to do that again and no from the bottom of my heart when I'm not having a hissy fit I genuinely do not enjoy doing anything that negatively effects you. But github isn't really the place to talk about this. You can talk to me on hang outs, and if you do, I will be sort of confused
