### ISSUE TITLE
Git history is full of shit

### ISSUE THREAD

**Issue by JoshDreamland** [enigma-dev/enigma-dev#1413]
I was going to leave it alone until we committed 5MB of binaries to it. Now master needs to be replaced.

To-do points:

- Erase those DLLs from history
- Squash the hundreds of "update travis.ci" commits from Sam's other PR into one commit.
- Audit for any other broken commits.

**Comment by RobertBColton** [comment]
Sorry, he told me you were ok with the dll.

**Comment by JoshDreamland** [comment]
I am okay with the dependency on a DLL, yes, but I told him he'd need to find somewhere to host it.

**Comment by time-killer-games** [comment]
@JoshDreamland I asked you if we could host it on Github and you said "ok". At any rate I misunderstood what you were ok with. You meant in my own repository, which wasn't very clear to me.

**Comment by JoshDreamland** [comment]
This has been resolved.

Rebase work log: https://pastebin.com/TqAT3nq7

ENIGMA master has been changed from 950036ab76c366d5ab809011a94bda68d86f9f9d → ab5f27d4f0cee229a735ff1070b797aca6bf1c6e.

Diff:
```diff
josh@dreamland:~/Projects/ENIGMA$ git diff  950036ab76c366d5ab809011a94bda68d86f9f9d ab5f27d4f0cee229a735ff1070b797aca6bf1c6e
diff --git a/Compilers/Linux/gcc.ey b/Compilers/Linux/gcc.ey
index 4df34fc47..3f321df71 100644
--- a/Compilers/Linux/gcc.ey
+++ b/Compilers/Linux/gcc.ey
@@ -14,7 +14,7 @@ Make-Vars:
   cppflags:
   cxxflags: -std=c++11
   cflags:
-  ldflags:
+  ldflags: -no-pie
   links:
 
 Parser-Vars:
diff --git a/ENIGMAsystem/SHELL/Widget_Systems/DlgMod/x64/DialogModule.dll b/ENIGMAsystem/SHELL/Widget_Systems/DlgMod/x64/DialogModule.dll
new file mode 100644
index 000000000..7def7f440
Binary files /dev/null and b/ENIGMAsystem/SHELL/Widget_Systems/DlgMod/x64/DialogModule.dll differ
diff --git a/ENIGMAsystem/SHELL/Widget_Systems/DlgMod/x86/DialogModule.dll b/ENIGMAsystem/SHELL/Widget_Systems/DlgMod/x86/DialogModule.dll
new file mode 100644
index 000000000..f5f55249b
Binary files /dev/null and b/ENIGMAsystem/SHELL/Widget_Systems/DlgMod/x86/DialogModule.dll differ
```

**Comment by RobertBColton** [comment]
We maybe want to post an announcement about this? I am not sure, but if people go to git pull, I think they'll have some issues.
