### ISSUE TITLE
sprite_create_from_screen does this shit in OpenGL1

### ISSUE THREAD

**Issue by time-killer-games** [enigma-dev/enigma-dev#1423]
![screenshot from 2018-10-27 07-40-59](https://user-images.githubusercontent.com/4379204/47603592-299c7a80-d9bc-11e8-939b-3c2073a68be6.png)

The Fucking:
![screenshot from 2018-10-27 07-43-04](https://user-images.githubusercontent.com/4379204/47603593-2a351100-d9bc-11e8-9b50-6937fd15bdbe.png)

**Comment by RobertBColton** [comment]
Closing as resolved by #1540.
