### ISSUE TITLE
Every game I compile throws SIGSEGV

### ISSUE THREAD

**Issue by nkrapivin** [enigma-dev/enigma-dev#1449]
Lubuntu 16.04
2gb ram
intel atom n455 \ intel gma 3150 (opengl 1.4)
LateralGM and ENIGMA are working just fine, also compiles just fine, but when launching any game it crashes.

**Comment by RobertBColton** [comment]
Can you build it in debug mode and run the executable that crashes in GDB?
https://enigma-dev.org/docs/Wiki/Debugging

It's likely a dependency conflict, maybe glew or glxew.

**Comment by nkrapivin** [comment]
Thanks! Reinstalling opengl libs fixed problem.

**Comment by RobertBColton** [comment]
Wonderful, I'm glad you could get it working!
