### ISSUE TITLE
Travis/Ubuntu 14 Have Outdated GLM

### ISSUE THREAD

**Issue by RobertBColton** [enigma-dev/enigma-dev#1457]
As discovered in #1454, Ubuntu 14 has GLM 0.9.5 which apparently did not have support for left handed coordinates. This causes the test harness to render games inverted on the z-axis, and effectively makes the depth comparison test I added useless.

Hugar has GLM 0.9.7 on his distro which also complains about me defining `GLM_LEFT_HANDED` which was for GLM 0.9.6. I do define `GLM_FORCE_LEFT_HANDED` but somebody made a mistake over there making the old one error for Hugar's version only instead of just a warning. My version does not error if I define both and mine is newer than Hugar's. I have GLM 0.9.9 in my MSYS2 setup of enigma-dev.

### Travis GLM 0.9.5 Renders With Right-Handed Coordinate System
![Travis GLM Right Handed](https://user-images.githubusercontent.com/3212801/49991382-e0de5800-ff4e-11e8-9cb5-7be520a8a75d.png)

### Local MSYS2 GLM 0.9.9 Renders Correctly With Left-Handed Coordinate System
![Local GLM Left Handed](https://user-images.githubusercontent.com/3212801/49991436-0d926f80-ff4f-11e8-8bf9-3a4657f473bd.png)

### GameMaker: Studio v1.4 Reference
![GMS v1.4 Reference](https://user-images.githubusercontent.com/3212801/50050451-2c1c7600-00c9-11e9-8857-3cc60ffd7fbf.png)

### GameMaker 8 Reference
![GM8 Reference](https://user-images.githubusercontent.com/3212801/50050485-37bc6c80-00ca-11e9-8daf-afbfcdda98d7.png)

**Comment by fundies** [comment]
The CI is now on ubuntu 18.04 and it has glm 0.9.9. can we close this?

**Comment by fundies** [comment]
@RobertBColton poke

**Comment by RobertBColton** [comment]
What about people using outdated Ubuntu, like Hugar who frequently faced this issue. Part of this also missing, because I didn't feel like explaining it. I was discovering it seems that GM apparently has a right handed coordinate system (see #1620).

**Comment by fundies** [comment]
noone has ubuntu 14. It's past long term support and noone supports it. It's like saying enigma doesnt work on windows 95

**Comment by RobertBColton** [comment]
Well that still leaves that I wanted somebody who knows about matrices to look at this. I don't feel like digging into it, but I am not sure if there's some other aspect of this I may have been missing. Also because of this, I am not sure if testing the shape functions is actually correct yet. An apitrace should be done to compare our texture coordinates and vertex data is the same as GM's, as well as a comparison of our projection matrices.
