### ISSUE TITLE
GameData Branch Regressions

### ISSUE THREAD

**Issue by RobertBColton** [enigma-dev/enigma-dev#1514]
Just making a list of remaining regressions I caught from #1448 being merged so @JoshDreamland can find them. All of these issues go away if I reset to before #1448 was merged and clean build the compiler.

- [x] Project Mario crashes at the start.
- [x] SONIGMA coins won't go away after being destroyed. (alarms related)
- [x] One of dazappa's games on the EDC has stopped working and now generates random rooms that are simply empty.
https://enigma-dev.org/edc/games.php?game=20

**Comment by JoshDreamland** [comment]
Amazing how we can catch more regressions in two days of my submitting a change than in six weeks of "everyone please test this" beforehand.

**Comment by RobertBColton** [comment]
You basically fixed every single one of the issues in #1523.

**Comment by RobertBColton** [comment]
Closing since 36de74c8d44871ea260506a8f8e27d684aee4253 is merged and all of the issues are resolved.
