### ISSUE TITLE
"Error: Compile failed at C++ level" when starting up game

### ISSUE THREAD

**Issue by tinoposts** [enigma-dev/enigma-dev#1545]
Dang, Tino, back at it again with the GitHub error report. Dead meme asides, you've heard me correctly. I'm trying to play a .gmk file, but the compile failed at the C++ level. This is my first time using Lateral and Enigma, so I might need a bit of help. Don't know why this happened but here's a bunch of text from when I tried launching the game:

Building for mode (0)
Cleaning up from previous executions
 - Cleared event info.
Loading shared locals from extensions list
The IDE didn't tell ENIGMA what extensions were selected before requesting a build....Continuing anyway...
Copying resources:
Copying sprite names [53]
Copying sound names [31]
Copying background names [3]
Copying path names [0]
Copying script names [0]
Copying shader names [0]
Copying font names [1]
Copying timeline names [0]
Copying object names [65]
Copying room names [4]
Copying constant names [0]
SYNTAX CHECKING AND PRIMARY PARSING:
0 Scripts:
"Linking" scripts
`Linking' 0 scripts and 0 timelines in 0 passes...
Completing script "Link"
Done.
Completing timeline "Link"
Done.
65 Objects:
 obj_mario: 20 events: 
  Event[0, 0] Check `obj_mario::create... Done. Parse... Done.
  Event[3, 0] Check `obj_mario::step... Done. Parse... Done.
  Event[4, 1] Check `obj_mario::collision_1... Done. Parse... Done.
  Event[4, 2] Check `obj_mario::collision_2... Done. Parse... Done.
  Event[4, 32] Check `obj_mario::collision_32... Done. Parse... Done.
  Event[4, 33] Check `obj_mario::collision_33... Done. Parse... Done.
  Event[4, 39] Check `obj_mario::collision_39... Done. Parse... Done.
  Event[4, 47] Check `obj_mario::collision_47... Done. Parse... Done.
  Event[4, 48] Check `obj_mario::collision_48... Done. Parse... Done.
  Event[4, 49] Check `obj_mario::collision_49... Done. Parse... Done.
  Event[4, 52] Check `obj_mario::collision_52... Done. Parse... Done.
  Event[4, 60] Check `obj_mario::collision_60... Done. Parse... Done.
  Event[7, 0] Check `obj_mario::outsideroom... Done. Parse... Done.
  Event[7, 2] Check `obj_mario::gamestart... Done. Parse... Done.
  Event[7, 4] Check `obj_mario::roomstart... Done. Parse... Done.
  Event[9, 37] Check `obj_mario::keypress_37... Done. Parse... Done.
  Event[9, 39] Check `obj_mario::keypress_39... Done. Parse... Done.
  Event[9, 90] Check `obj_mario::keypress_90... Done. Parse... Done.
  Event[10, 37] Check `obj_mario::keyrelease_37... Done. Parse... Done.
  Event[10, 39] Check `obj_mario::keyrelease_39... Done. Parse... Done.
 obj_block: 0 events: 
 obj_goomba: 13 events: 
  Event[0, 0] Check `obj_goomba::create... Done. Parse... Done.
  Event[3, 0] Check `obj_goomba::step... Done. Parse... Done.
  Event[4, 0] Check `obj_goomba::collision_0... Done. Parse... Done.
  Event[4, 1] Check `obj_goomba::collision_1... Done. Parse... Done.
  Event[4, 24] Check `obj_goomba::collision_24... Done. Parse... Done.
  Event[4, 26] Check `obj_goomba::collision_26... Done. Parse... Done.
  Event[4, 28] Check `obj_goomba::collision_28... Done. Parse... Done.
  Event[4, 29] Check `obj_goomba::collision_29... Done. Parse... Done.
  Event[4, 41] Check `obj_goomba::collision_41... Done. Parse... Done.
  Event[4, 42] Check `obj_goomba::collision_42... Done. Parse... Done.
  Event[4, 55] Check `obj_goomba::collision_55... Done. Parse... Done.
  Event[4, 57] Check `obj_goomba::collision_57... Done. Parse... Done.
  Event[4, 58] Check `obj_goomba::collision_58... Done. Parse... Done.
 obj_goomba_squish: 2 events: 
  Event[0, 0] Check `obj_goomba_squish::create... Done. Parse... Done.
  Event[2, 0] Check `obj_goomba_squish::alarm_0... Done. Parse... Done.
 obj_coinblock: 6 events: 
  Event[0, 0] Check `obj_coinblock::create... Done. Parse... Done.
  Event[2, 0] Check `obj_coinblock::alarm_0... Done. Parse... Done.
  Event[2, 1] Check `obj_coinblock::alarm_1... Done. Parse... Done.
  Event[4, 0] Check `obj_coinblock::collision_0... Done. Parse... Done.
  Event[4, 24] Check `obj_coinblock::collision_24... Done. Parse... Done.
  Event[4, 26] Check `obj_coinblock::collision_26... Done. Parse... Done.
 obj_blockcoin: 2 events: 
  Event[0, 0] Check `obj_blockcoin::create... Done. Parse... Done.
  Event[2, 0] Check `obj_blockcoin::alarm_0... Done. Parse... Done.
 obj_coinhud: 1 events: 
  Event[8, 0] Check `obj_coinhud::draw... Done. Parse... Done.
 obj_liveshud: 1 events: 
  Event[8, 0] Check `obj_liveshud::draw... Done. Parse... Done.
 obj_coincount: 1 events: 
  Event[8, 0] Check `obj_coincount::draw... Done. Parse... Done.
 obj_lifecount: 2 events: 
  Event[3, 0] Check `obj_lifecount::step... Done. Parse... Done.
  Event[8, 0] Check `obj_lifecount::draw... Done. Parse... Done.
 obj_deadmario: 3 events: 
  Event[0, 0] Check `obj_deadmario::create... Done. Parse... Done.
  Event[3, 0] Check `obj_deadmario::step... Done. Parse... Done.
  Event[7, 0] Check `obj_deadmario::outsideroom... Done. Parse... Done.
 obj_gameover: 2 events: 
  Event[0, 0] Check `obj_gameover::create... Done. Parse... Done.
  Event[2, 0] Check `obj_gameover::alarm_0... Done. Parse... Done.
 mus_athletic: 1 events: 
  Event[7, 4] Check `mus_athletic::roomstart... Done. Parse... Done.
 mus_boss: 1 events: 
  Event[7, 4] Check `mus_boss::roomstart... Done. Parse... Done.
 mus_castle: 1 events: 
  Event[7, 4] Check `mus_castle::roomstart... Done. Parse... Done.
 mus_caves: 1 events: 
  Event[7, 4] Check `mus_caves::roomstart... Done. Parse... Done.
 mus_desert: 1 events: 
  Event[7, 4] Check `mus_desert::roomstart... Done. Parse... Done.
 mus_jungle: 1 events: 
  Event[7, 4] Check `mus_jungle::roomstart... Done. Parse... Done.
 mus_manor: 1 events: 
  Event[7, 4] Check `mus_manor::roomstart... Done. Parse... Done.
 mus_grasslands: 1 events: 
  Event[7, 4] Check `mus_grasslands::roomstart... Done. Parse... Done.
 mus_snow: 1 events: 
  Event[7, 4] Check `mus_snow::roomstart... Done. Parse... Done.
 mus_title: 1 events: 
  Event[7, 4] Check `mus_title::roomstart... Done. Parse... Done.
 mus_underwater: 1 events: 
  Event[7, 4] Check `mus_underwater::roomstart... Done. Parse... Done.
 mus_volcano: 1 events: 
  Event[7, 4] Check `mus_volcano::roomstart... Done. Parse... Done.
 obj_mario_fire: 21 events: 
  Event[0, 0] Check `obj_mario_fire::create... Done. Parse... Done.
  Event[3, 0] Check `obj_mario_fire::step... Done. Parse... Done.
  Event[4, 1] Check `obj_mario_fire::collision_1... Done. Parse... Done.
  Event[4, 2] Check `obj_mario_fire::collision_2... Done. Parse... Done.
  Event[4, 31] Check `obj_mario_fire::collision_31... Done. Parse... Done.
  Event[4, 33] Check `obj_mario_fire::collision_33... Done. Parse... Done.
  Event[4, 39] Check `obj_mario_fire::collision_39... Done. Parse... Done.
  Event[4, 40] Check `obj_mario_fire::collision_40... Done. Parse... Done.
  Event[4, 47] Check `obj_mario_fire::collision_47... Done. Parse... Done.
  Event[4, 48] Check `obj_mario_fire::collision_48... Done. Parse... Done.
  Event[4, 49] Check `obj_mario_fire::collision_49... Done. Parse... Done.
  Event[4, 52] Check `obj_mario_fire::collision_52... Done. Parse... Done.
  Event[4, 60] Check `obj_mario_fire::collision_60... Done. Parse... Done.
  Event[7, 0] Check `obj_mario_fire::outsideroom... Done. Parse... Done.
  Event[7, 2] Check `obj_mario_fire::gamestart... Done. Parse... Done.
  Event[7, 4] Check `obj_mario_fire::roomstart... Done. Parse... Done.
  Event[9, 37] Check `obj_mario_fire::keypress_37... Done. Parse... Done.
  Event[9, 39] Check `obj_mario_fire::keypress_39... Done. Parse... Done.
  Event[9, 90] Check `obj_mario_fire::keypress_90... Done. Parse... Done.
  Event[10, 37] Check `obj_mario_fire::keyrelease_37... Done. Parse... Done.
  Event[10, 39] Check `obj_mario_fire::keyrelease_39... Done. Parse... Done.
 obj_deadmario_fire: 3 events: 
  Event[0, 0] Check `obj_deadmario_fire::create... Done. Parse... Done.
  Event[3, 0] Check `obj_deadmario_fire::step... Done. Parse... Done.
  Event[7, 0] Check `obj_deadmario_fire::outsideroom... Done. Parse... Done.
 obj_mario_raccoon: 21 events: 
  Event[0, 0] Check `obj_mario_raccoon::create... Done. Parse... Done.
  Event[3, 0] Check `obj_mario_raccoon::step... Done. Parse... Done.
  Event[4, 1] Check `obj_mario_raccoon::collision_1... Done. Parse... Done.
  Event[4, 2] Check `obj_mario_raccoon::collision_2... Done. Parse... Done.
  Event[4, 31] Check `obj_mario_raccoon::collision_31... Done. Parse... Done.
  Event[4, 32] Check `obj_mario_raccoon::collision_32... Done. Parse... Done.
  Event[4, 39] Check `obj_mario_raccoon::collision_39... Done. Parse... Done.
  Event[4, 40] Check `obj_mario_raccoon::collision_40... Done. Parse... Done.
  Event[4, 47] Check `obj_mario_raccoon::collision_47... Done. Parse... Done.
  Event[4, 48] Check `obj_mario_raccoon::collision_48... Done. Parse... Done.
  Event[4, 49] Check `obj_mario_raccoon::collision_49... Done. Parse... Done.
  Event[4, 52] Check `obj_mario_raccoon::collision_52... Done. Parse... Done.
  Event[4, 60] Check `obj_mario_raccoon::collision_60... Done. Parse... Done.
  Event[7, 0] Check `obj_mario_raccoon::outsideroom... Done. Parse... Done.
  Event[7, 2] Check `obj_mario_raccoon::gamestart... Done. Parse... Done.
  Event[7, 4] Check `obj_mario_raccoon::roomstart... Done. Parse... Done.
  Event[9, 37] Check `obj_mario_raccoon::keypress_37... Done. Parse... Done.
  Event[9, 39] Check `obj_mario_raccoon::keypress_39... Done. Parse... Done.
  Event[9, 90] Check `obj_mario_raccoon::keypress_90... Done. Parse... Done.
  Event[10, 37] Check `obj_mario_raccoon::keyrelease_37... Done. Parse... Done.
  Event[10, 39] Check `obj_mario_raccoon::keyrelease_39... Done. Parse... Done.
 obj_deadmario_raccoon: 3 events: 
  Event[0, 0] Check `obj_deadmario_raccoon::create... Done. Parse... Done.
  Event[3, 0] Check `obj_deadmario_raccoon::step... Done. Parse... Done.
  Event[7, 0] Check `obj_deadmario_raccoon::outsideroom... Done. Parse... Done.
 obj_fireball_l: 1 events: 
  Event[0, 0] Check `obj_fireball_l::create... Done. Parse... Done.
 obj_fireball_r: 1 events: 
  Event[0, 0] Check `obj_fireball_r::create... Done. Parse... Done.
 obj_mushblock: 6 events: 
  Event[0, 0] Check `obj_mushblock::create... Done. Parse... Done.
  Event[2, 0] Check `obj_mushblock::alarm_0... Done. Parse... Done.
  Event[2, 1] Check `obj_mushblock::alarm_1... Done. Parse... Done.
  Event[4, 0] Check `obj_mushblock::collision_0... Done. Parse... Done.
  Event[4, 24] Check `obj_mushblock::collision_24... Done. Parse... Done.
  Event[4, 26] Check `obj_mushblock::collision_26... Done. Parse... Done.
 obj_mushroom: 13 events: 
  Event[0, 0] Check `obj_mushroom::create... Done. Parse... Done.
  Event[3, 0] Check `obj_mushroom::step... Done. Parse... Done.
  Event[4, 0] Check `obj_mushroom::collision_0... Done. Parse... Done.
  Event[4, 1] Check `obj_mushroom::collision_1... Done. Parse... Done.
  Event[4, 4] Check `obj_mushroom::collision_4... Done. Parse... Done.
  Event[4, 24] Check `obj_mushroom::collision_24... Done. Parse... Done.
  Event[4, 26] Check `obj_mushroom::collision_26... Done. Parse... Done.
  Event[4, 30] Check `obj_mushroom::collision_30... Done. Parse... Done.
  Event[4, 34] Check `obj_mushroom::collision_34... Done. Parse... Done.
  Event[4, 35] Check `obj_mushroom::collision_35... Done. Parse... Done.
  Event[4, 48] Check `obj_mushroom::collision_48... Done. Parse... Done.
  Event[4, 49] Check `obj_mushroom::collision_49... Done. Parse... Done.
  Event[4, 55] Check `obj_mushroom::collision_55... Done. Parse... Done.
 obj_flower: 3 events: 
  Event[4, 0] Check `obj_flower::collision_0... Done. Parse... Done.
  Event[4, 24] Check `obj_flower::collision_24... Done. Parse... Done.
  Event[4, 26] Check `obj_flower::collision_26... Done. Parse... Done.
 obj_leaf: 5 events: 
  Event[0, 0] Check `obj_leaf::create... Done. Parse... Done.
  Event[3, 0] Check `obj_leaf::step... Done. Parse... Done.
  Event[4, 0] Check `obj_leaf::collision_0... Done. Parse... Done.
  Event[4, 24] Check `obj_leaf::collision_24... Done. Parse... Done.
  Event[4, 26] Check `obj_leaf::collision_26... Done. Parse... Done.
 obj_flowblock: 6 events: 
  Event[0, 0] Check `obj_flowblock::create... Done. Parse... Done.
  Event[2, 0] Check `obj_flowblock::alarm_0... Done. Parse... Done.
  Event[2, 1] Check `obj_flowblock::alarm_1... Done. Parse... Done.
  Event[4, 0] Check `obj_flowblock::collision_0... Done. Parse... Done.
  Event[4, 24] Check `obj_flowblock::collision_24... Done. Parse... Done.
  Event[4, 26] Check `obj_flowblock::collision_26... Done. Parse... Done.
 obj_leafblock: 6 events: 
  Event[0, 0] Check `obj_leafblock::create... Done. Parse... Done.
  Event[2, 0] Check `obj_leafblock::alarm_0... Done. Parse... Done.
  Event[2, 1] Check `obj_leafblock::alarm_1... Done. Parse... Done.
  Event[4, 0] Check `obj_leafblock::collision_0... Done. Parse... Done.
  Event[4, 24] Check `obj_leafblock::collision_24... Done. Parse... Done.
  Event[4, 26] Check `obj_leafblock::collision_26... Done. Parse... Done.
 obj_invisimario: 12 events: 
  Event[0, 0] Check `obj_invisimario::create... Done. Parse... Done.
  Event[3, 0] Check `obj_invisimario::step... Done. Parse... Done.
  Event[4, 1] Check `obj_invisimario::collision_1... Done. Parse... Done.
  Event[4, 2] Check `obj_invisimario::collision_2... Done. Parse... Done.
  Event[4, 4] Check `obj_invisimario::collision_4... Done. Parse... Done.
  Event[4, 30] Check `obj_invisimario::collision_30... Done. Parse... Done.
  Event[4, 34] Check `obj_invisimario::collision_34... Done. Parse... Done.
  Event[4, 35] Check `obj_invisimario::collision_35... Done. Parse... Done.
  Event[4, 51] Check `obj_invisimario::collision_51... Done. Parse... Done.
  Event[4, 59] Check `obj_invisimario::collision_59... Done. Parse... Done.
  Event[4, 61] Check `obj_invisimario::collision_61... Done. Parse... Done.
  Event[7, 4] Check `obj_invisimario::roomstart... Done. Parse... Done.
 obj_goomba_fall: 3 events: 
  Event[0, 0] Check `obj_goomba_fall::create... Done. Parse... Done.
  Event[2, 0] Check `obj_goomba_fall::alarm_0... Done. Parse... Done.
  Event[3, 0] Check `obj_goomba_fall::step... Done. Parse... Done.
 obj_1up_mushroom: 12 events: 
  Event[0, 0] Check `obj_1up_mushroom::create... Done. Parse... Done.
  Event[3, 0] Check `obj_1up_mushroom::step... Done. Parse... Done.
  Event[4, 0] Check `obj_1up_mushroom::collision_0... Done. Parse... Done.
  Event[4, 1] Check `obj_1up_mushroom::collision_1... Done. Parse... Done.
  Event[4, 4] Check `obj_1up_mushroom::collision_4... Done. Parse... Done.
  Event[4, 24] Check `obj_1up_mushroom::collision_24... Done. Parse... Done.
  Event[4, 26] Check `obj_1up_mushroom::collision_26... Done. Parse... Done.
  Event[4, 30] Check `obj_1up_mushroom::collision_30... Done. Parse... Done.
  Event[4, 34] Check `obj_1up_mushroom::collision_34... Done. Parse... Done.
  Event[4, 35] Check `obj_1up_mushroom::collision_35... Done. Parse... Done.
  Event[4, 51] Check `obj_1up_mushroom::collision_51... Done. Parse... Done.
  Event[4, 55] Check `obj_1up_mushroom::collision_55... Done. Parse... Done.
 obj_koopa: 13 events: 
  Event[0, 0] Check `obj_koopa::create... Done. Parse... Done.
  Event[3, 0] Check `obj_koopa::step... Done. Parse... Done.
  Event[4, 0] Check `obj_koopa::collision_0... Done. Parse... Done.
  Event[4, 1] Check `obj_koopa::collision_1... Done. Parse... Done.
  Event[4, 24] Check `obj_koopa::collision_24... Done. Parse... Done.
  Event[4, 26] Check `obj_koopa::collision_26... Done. Parse... Done.
  Event[4, 28] Check `obj_koopa::collision_28... Done. Parse... Done.
  Event[4, 29] Check `obj_koopa::collision_29... Done. Parse... Done.
  Event[4, 41] Check `obj_koopa::collision_41... Done. Parse... Done.
  Event[4, 42] Check `obj_koopa::collision_42... Done. Parse... Done.
  Event[4, 55] Check `obj_koopa::collision_55... Done. Parse... Done.
  Event[4, 57] Check `obj_koopa::collision_57... Done. Parse... Done.
  Event[4, 58] Check `obj_koopa::collision_58... Done. Parse... Done.
 obj_koopashell: 7 events: 
  Event[0, 0] Check `obj_koopashell::create... Done. Parse... Done.
  Event[3, 0] Check `obj_koopashell::step... Done. Parse... Done.
  Event[4, 1] Check `obj_koopashell::collision_1... Done. Parse... Done.
  Event[4, 28] Check `obj_koopashell::collision_28... Done. Parse... Done.
  Event[4, 29] Check `obj_koopashell::collision_29... Done. Parse... Done.
  Event[4, 41] Check `obj_koopashell::collision_41... Done. Parse... Done.
  Event[4, 42] Check `obj_koopashell::collision_42... Done. Parse... Done.
 obj_enemy_left: 1 events: 
  Event[0, 0] Check `obj_enemy_left::create... Done. Parse... Done.
 obj_enemy_right: 1 events: 
  Event[0, 0] Check `obj_enemy_right::create... Done. Parse... Done.
 obj_koopa_fall: 3 events: 
  Event[0, 0] Check `obj_koopa_fall::create... Done. Parse... Done.
  Event[2, 0] Check `obj_koopa_fall::alarm_0... Done. Parse... Done.
  Event[3, 0] Check `obj_koopa_fall::step... Done. Parse... Done.
 obj_koopa_red: 13 events: 
  Event[0, 0] Check `obj_koopa_red::create... Done. Parse... Done.
  Event[3, 0] Check `obj_koopa_red::step... Done. Parse... Done.
  Event[4, 0] Check `obj_koopa_red::collision_0... Done. Parse... Done.
  Event[4, 1] Check `obj_koopa_red::collision_1... Done. Parse... Done.
  Event[4, 24] Check `obj_koopa_red::collision_24... Done. Parse... Done.
  Event[4, 26] Check `obj_koopa_red::collision_26... Done. Parse... Done.
  Event[4, 28] Check `obj_koopa_red::collision_28... Done. Parse... Done.
  Event[4, 29] Check `obj_koopa_red::collision_29... Done. Parse... Done.
  Event[4, 41] Check `obj_koopa_red::collision_41... Done. Parse... Done.
  Event[4, 42] Check `obj_koopa_red::collision_42... Done. Parse... Done.
  Event[4, 55] Check `obj_koopa_red::collision_55... Done. Parse... Done.
  Event[4, 57] Check `obj_koopa_red::collision_57... Done. Parse... Done.
  Event[4, 58] Check `obj_koopa_red::collision_58... Done. Parse... Done.
 obj_koopashell_red: 7 events: 
  Event[0, 0] Check `obj_koopashell_red::create... Done. Parse... Done.
  Event[3, 0] Check `obj_koopashell_red::step... Done. Parse... Done.
  Event[4, 1] Check `obj_koopashell_red::collision_1... Done. Parse... Done.
  Event[4, 28] Check `obj_koopashell_red::collision_28... Done. Parse... Done.
  Event[4, 29] Check `obj_koopashell_red::collision_29... Done. Parse... Done.
  Event[4, 41] Check `obj_koopashell_red::collision_41... Done. Parse... Done.
  Event[4, 42] Check `obj_koopashell_red::collision_42... Done. Parse... Done.
 obj_koopa_fall_red: 3 events: 
  Event[0, 0] Check `obj_koopa_fall_red::create... Done. Parse... Done.
  Event[2, 0] Check `obj_koopa_fall_red::alarm_0... Done. Parse... Done.
  Event[3, 0] Check `obj_koopa_fall_red::step... Done. Parse... Done.
 obj_pipe: 1 events: 
  Event[5, 40] Check `obj_pipe::keyboard_40... Done. Parse... Done.
 obj_blue_block: 0 events: 
 obj_grass: 0 events: 
 obj_coin: 3 events: 
  Event[4, 0] Check `obj_coin::collision_0... Done. Parse... Done.
  Event[4, 24] Check `obj_coin::collision_24... Done. Parse... Done.
  Event[4, 26] Check `obj_coin::collision_26... Done. Parse... Done.
 obj_brickblock: 7 events: 
  Event[0, 0] Check `obj_brickblock::create... Done. Parse... Done.
  Event[2, 0] Check `obj_brickblock::alarm_0... Done. Parse... Done.
  Event[2, 1] Check `obj_brickblock::alarm_1... Done. Parse... Done.
  Event[4, 0] Check `obj_brickblock::collision_0... Done. Parse... Done.
  Event[4, 24] Check `obj_brickblock::collision_24... Done. Parse... Done.
  Event[4, 26] Check `obj_brickblock::collision_26... Done. Parse... Done.
  Event[4, 55] Check `obj_brickblock::collision_55... Done. Parse... Done.
 obj_pipe2: 1 events: 
  Event[5, 40] Check `obj_pipe2::keyboard_40... Done. Parse... Done.
 obj_dirt: 0 events: 
 obj_logo: 0 events: 
 obj_mario_ice: 20 events: 
  Event[0, 0] Check `obj_mario_ice::create... Done. Parse... Done.
  Event[3, 0] Check `obj_mario_ice::step... Done. Parse... Done.
  Event[4, 1] Check `obj_mario_ice::collision_1... Done. Parse... Done.
  Event[4, 2] Check `obj_mario_ice::collision_2... Done. Parse... Done.
  Event[4, 31] Check `obj_mario_ice::collision_31... Done. Parse... Done.
  Event[4, 33] Check `obj_mario_ice::collision_33... Done. Parse... Done.
  Event[4, 39] Check `obj_mario_ice::collision_39... Done. Parse... Done.
  Event[4, 40] Check `obj_mario_ice::collision_40... Done. Parse... Done.
  Event[4, 47] Check `obj_mario_ice::collision_47... Done. Parse... Done.
  Event[4, 48] Check `obj_mario_ice::collision_48... Done. Parse... Done.
  Event[4, 49] Check `obj_mario_ice::collision_49... Done. Parse... Done.
  Event[4, 52] Check `obj_mario_ice::collision_52... Done. Parse... Done.
  Event[7, 0] Check `obj_mario_ice::outsideroom... Done. Parse... Done.
  Event[7, 2] Check `obj_mario_ice::gamestart... Done. Parse... Done.
  Event[7, 4] Check `obj_mario_ice::roomstart... Done. Parse... Done.
  Event[9, 37] Check `obj_mario_ice::keypress_37... Done. Parse... Done.
  Event[9, 39] Check `obj_mario_ice::keypress_39... Done. Parse... Done.
  Event[9, 90] Check `obj_mario_ice::keypress_90... Done. Parse... Done.
  Event[10, 37] Check `obj_mario_ice::keyrelease_37... Done. Parse... Done.
  Event[10, 39] Check `obj_mario_ice::keyrelease_39... Done. Parse... Done.
 obj_deadmario_ice: 3 events: 
  Event[0, 0] Check `obj_deadmario_ice::create... Done. Parse... Done.
  Event[3, 0] Check `obj_deadmario_ice::step... Done. Parse... Done.
  Event[7, 0] Check `obj_deadmario_ice::outsideroom... Done. Parse... Done.
 obj_iceball_l: 1 events: 
  Event[0, 0] Check `obj_iceball_l::create... Done. Parse... Done.
 obj_iceball_r: 1 events: 
  Event[0, 0] Check `obj_iceball_r::create... Done. Parse... Done.
 obj_tulpbox: 7 events: 
  Event[0, 0] Check `obj_tulpbox::create... Done. Parse... Done.
  Event[2, 0] Check `obj_tulpbox::alarm_0... Done. Parse... Done.
  Event[2, 1] Check `obj_tulpbox::alarm_1... Done. Parse... Done.
  Event[4, 0] Check `obj_tulpbox::collision_0... Done. Parse... Done.
  Event[4, 24] Check `obj_tulpbox::collision_24... Done. Parse... Done.
  Event[4, 26] Check `obj_tulpbox::collision_26... Done. Parse... Done.
  Event[4, 55] Check `obj_tulpbox::collision_55... Done. Parse... Done.
 obj_tulip: 4 events: 
  Event[4, 0] Check `obj_tulip::collision_0... Done. Parse... Done.
  Event[4, 24] Check `obj_tulip::collision_24... Done. Parse... Done.
  Event[4, 26] Check `obj_tulip::collision_26... Done. Parse... Done.
  Event[4, 55] Check `obj_tulip::collision_55... Done. Parse... Done.
 obj_ice_block: 1 events: 
  Event[0, 0] Check `obj_ice_block::create... Done. Parse... Done.
 obj_play: 1 events: 
  Event[6, 0] Check `obj_play::leftbutton... Done. Parse... Done.
 obj_edit: 1 events: 
  Event[6, 0] Check `obj_edit::leftbutton... Done. Parse... Done.
 obj_quit: 1 events: 
  Event[6, 0] Check `obj_quit::leftbutton... Done. Parse... Done.
Creating room creation code scope and parsing
"Linking" scripts into the objects...
"Linking" timelines into the objects...
"Link" complete.
Tabulating maximum argument passes to each script
Finished
Writing executable information and resources.
Writing modes and settings
Writing object switch
Writing resource names and maxima
Writing timeline control information
Linking globals and ambiguous variables
Running Secondary Parse Passes
Add dot accessed local marioregular
 var 
Add dot accessed local mariofire
 var 
Add dot accessed local marioice
 var 
Add dot accessed local marioraccoon
 var 
Add dot accessed local coins
 var 
Add dot accessed local mariolives
 var 
Writing events
Writing object data
Writing local accessors
Writing font data
Writing room data
Writing shader data
Running make from `make'
Full command line: make Game WORKDIR="/home/tinoposts/.enigma/" CODEGEN="/home/tinoposts/.enigma/" GMODE="Run" GRAPHICS="OpenGL1" AUDIO="OpenAL" COLLISION="Precise" WIDGETS="None" NETWORKING="None" PLATFORM="xlib" TARGET-PLATFORM="Linux" CC="gcc" CXX="g++" CXXFLAGS="-std=c++11" MAKE="make" COMPILEPATH="Linux/Linux/GNU_GCC_G++" EXTENSIONS=" Universal_System/Extensions/Paths Universal_System/Extensions/DateTime Universal_System/Extensions/DataStructures Universal_System/Extensions/MotionPlanning Universal_System/Extensions/Alarms Universal_System/Extensions/ParticleSystems Universal_System/Extensions/Timelines" OUTPUTNAME="/tmp/egm8783570073812386626.tmp" 
make -C shared/lodepng/
make[1]: Entering directory '/home/tinoposts/enigma-dev/shared/lodepng'
mkdir -p .eobjs/
g++  -std=c++11 -fPIC -MMD -c -o .eobjs/lodepng.o lodepng.cpp
ar rvs liblodepng.a .eobjs/lodepng.o
r - .eobjs/lodepng.o
make[1]: Leaving directory '/home/tinoposts/enigma-dev/shared/lodepng'
make -C ENIGMAsystem/SHELL
make[1]: Entering directory '/home/tinoposts/enigma-dev/ENIGMAsystem/SHELL'
g++ -std=c++11 -Wall -s -O3 -fno-rtti -fno-exceptions -DPATH_EXT_SET -IPlatforms/xlib/Info -IGraphics_Systems/OpenGL1/Info -IAudio_Systems/OpenAL/Info -ICollision_Systems/Precise/Info -IWidget_Systems/None/Info -INetworking_Systems/None/Info -IUniversal_System/Info -I. -I/home/tinoposts/.enigma/ -I../../shared/lodepng -I../../shared  -MMD -MP -c -o /home/tinoposts/.enigma/.eobjs/Linux/Linux/GNU_GCC_G++/Run/SHELLmain.o SHELLmain.cpp
In file included from SHELLmain.cpp:93:0:
/home/tinoposts/.enigma/Preprocessor_Environment_Editable/IDE_EDIT_resourcenames.h:203:5: error: expected identifier before numeric constant
     1up = 26,
     ^~~
/home/tinoposts/.enigma/Preprocessor_Environment_Editable/IDE_EDIT_resourcenames.h:203:5: error: expected ‘}’ before numeric constant
/home/tinoposts/.enigma/Preprocessor_Environment_Editable/IDE_EDIT_resourcenames.h:203:5: error: expected unqualified-id before numeric constant
/home/tinoposts/.enigma/Preprocessor_Environment_Editable/IDE_EDIT_resourcenames.h:290:1: error: expected declaration before ‘}’ token
 }
 ^
rm -f /home/tinoposts/.enigma/.eobjs/Linux/Linux/GNU_GCC_G++/Run/Universal_System/loading.o /home/tinoposts/.enigma/.eobjs/Linux/Linux/GNU_GCC_G++/Run/Universal_System/Extensions/MotionPlanning/motion_planning.o
make[1]: Leaving directory '/home/tinoposts/enigma-dev/ENIGMAsystem/SHELL'
Makefile:20: recipe for target 'Game' failed
make: *** [Game] Error 2

**Comment by tinoposts** [comment]
If your curios about the game, I guess I'll just post the link to it's GameJolt page. I think it's neat for a project that took me nearly a week. https://gamejolt.com/games/bsme/359845

**Comment by RobertBColton** [comment]
The error is actually quite obvious:
```
    * /home/tinoposts/.enigma/Preprocessor_Environment_Editable/IDE_EDIT_resourcenames.h:203:5: error: expected identifier before numeric constant
      1up = 26,
      ^~~
```

`1up` is an invalid variable name... even in GM. Variable names/identifiers have to start with a letter or underscore. Resource names also since they are treated like variables.

**Comment by JoshDreamland** [comment]
ENIGMA may have been the one that produced that variable name. And it probably is, if this works in GM. I'll take a look, shortly.

**Comment by RobertBColton** [comment]
Ok, I gave GM8 a look and I can say that I was able to give a resource this name. However, attempting to use its name like a variable... does in fact result in a syntax error.
![GM8 Invalid Object Identifier Syntax Error](https://user-images.githubusercontent.com/3212801/52521726-5dd53780-2c49-11e9-9b60-3e1f002640c9.png)

**Comment by JoshDreamland** [comment]
Indeed, ENIGMA generated your error from a resource name. In this case, you have a sound named `1up`. How are you playing that sound? You can't play it by name...

**Comment by tinoposts** [comment]
ok got it, the name 1up is the issue. so i'm assuming that i gotta change it to something else, like "extralife?"

**Comment by RobertBColton** [comment]
That would be fine, or just use what the GM manual recommends: `snd_1up` or `snd1up`.

**Comment by JoshDreamland** [comment]
Yeah, it turns out you have a lot of resources with the same name, or with invalid identifiers, but your game works in GM because you're using DND or the other resource editors to specify them. This doesn't work in ENIGMA because we ship that data to GCC to build; to get your game to work right now, you'd have to rename sprite `1up` to `spr_1up`, rename your second `koopa_shell_red` to `koopa_fall_red`, and rename a few sounds to have valid names:

`1up` → `snd_1up`
`coin` → `snd_coin` (conflicts with sprite)
`fireball` → `snd_fireball` (conflicts with sprite)
`fireball` → `snd_fireball2` (conflicts with sprite)
`break` → `snd_break` (break is a keyword)
`boss battle` → `boss_battle`
`level clear` → `level_clear`
`game over` → `game_over`

I went ahead and did so for you to test the game out. Apart from that, it seems to work fine. You can download the patched game here: http://dreamland.im/files/BSME.gmk

**Comment by JoshDreamland** [comment]
Most of these problems could be solved automatically in the GameData constructor. Let's go ahead and leave this bug open; at the point where this issue appears prevalent and is the only thing standing between users and their GM game actually working in ENIGMA, we should consider fixing it.

**Comment by tinoposts** [comment]
k thanks peeps, new to lateralgm. used to use gm8 before switching to ubuntu

**Comment by tinoposts** [comment]
now if only i could fix the music overlapping... eh i'm sure it's pretty simple
