### ISSUE TITLE
"#define byte" macro in javastruct.h conflicting with google protobuf headers

### ISSUE THREAD

**Issue by sociopart1** [enigma-dev/enigma-dev#1593]
https://github.com/enigma-dev/enigma-dev/blob/d0487e73f36b51de9f9f9fbbf4d62d73fa4a9043/CommandLine/emake/EnigmaCallbacks.hpp#L5
Move #include "backend/JavaCallbacks.h"  to line 10 (after #include "codegen/server.pb.h")

**Comment by RobertBColton** [comment]
Thanks, I haven't run into this error myself, but I submitted #1594 anyway.
