### ISSUE TITLE
Function shader_set_uniform_f_array() Unimplemented

### ISSUE THREAD

**Issue by time-killer-games** [enigma-dev/enigma-dev#1666]
I created a 3D 3rd person example game and I really was hoping with it I could publish on the EDC and prove the very nice shader it uses on the 3D floaring demon head models actually work in ENIGMA, but unfortunately it does not. The function in the title is not implemented, and that is my first roadblock. Here's the GMX project folder: https://www.dropbox.com/s/qkr0l9dhtlkpjze/Steal%20the%20Gold.gmx.zip?dl=0

Btw that dropbox link to the project folder download includes a shader written by xygthop3. I didn't get his permission to share it here in this github issue (yet), but I did ask him and if he complains about it I'll take the link down. You can find xygthop3 on the GMC: https://forum.yoyogames.com/

Edit: Alright, I got his permission.

**Comment by time-killer-games** [comment]
@RobertBColton Here's a demo executable for Windows to show you what the game looks like when everything is working how it is supposed to: https://samuel-venable.itch.io/steal-the-gold

**Comment by time-killer-games** [comment]
@RobertBColton updated description with some important info.

**Comment by time-killer-games** [comment]
@RobertBColton Ok, I got his permission.

**Comment by RobertBColton** [comment]
This is resolved by #2022.

**Comment by RobertBColton** [comment]
This is resolved by #2022 if you want @time-killer-games to test it out.

**Comment by time-killer-games** [comment]
I'm not in a position to test it anymore; the project no longer uses it because I didn't anticipate it being fixed any time soon. When I have time, I'll download a shader-related project from the gamemaker marketplace to give my feedback.

**Comment by RobertBColton** [comment]
Closing as resolved by #2022. Don't worry about testing it, if later you find that it doesn't work, you can file a new issue and I'll get it fixed. For now, it is at least implemented.
