### ISSUE TITLE
SNOO PINGAS USUAL, I SEE

### ISSUE THREAD

**Issue by time-killer-games** [enigma-dev/enigma-dev#1689]
I don't know where else to post this. Please increase max upload file size for EDC on my account. k'thx

**Comment by RobertBColton** [comment]
You could have posted this on the EDC tracker: https://github.com/enigma-dev/EDC

Forwarding to @JoshDreamland.

**Comment by time-killer-games** [comment]
How did i not see that? My bad!

**Comment by JoshDreamland** [comment]
This is an Apache limit. I don't control it. You may be able to get around it by uploading somewhere else and uploading to the EDC via URL.
