### ISSUE TITLE
Fix compiler settings for Windows (especially Win32)

### ISSUE THREAD

**Issue by sociopart1** [enigma-dev/enigma-dev#1734]
https://github.com/enigma-dev/enigma-dev/blob/148023a668ad72927fc165bc0bc1c24952e5077e/Compilers/Windows/gcc.ey#L15
This line broke ENIGMA for 32bit systems cause you forgot to add `-I/mingw32/lib/libffi-3.2.1/include` .

**Comment by RobertBColton** [comment]
Nice find! I have sent the changes in #1735.

**Comment by RobertBColton** [comment]
Closing as resolved by #1735.
