### ISSUE TITLE
Show Debug Message

### ISSUE THREAD

**Issue by RobertBColton** [enigma-dev/enigma-dev#1752]
It seems 8 years ago polygonz (7a00fb0fba7c4c1cf767e6929810bc89edf66604) implemented `show_debug_message` in the regular terminal I/O instead of the Widget Systems. Need to test GM8.1 and GMSv1.4 to see what the behavior is. User reported that ENIGMA's only shows the message in debug mode, while GMSv1.4 will show it in run and debug mode.

**Comment by RobertBColton** [comment]
Alright, so I tested GM8.1 and it seems the debug message is only shown in debug mode. You have to go to the debug window and select the menu to show debug messages. It doesn't show up in run mode or compile mode. I launched the compile mode exe inside a terminal and didn't see any output.

Download GM81 Exe: [debug-message-gm81.zip](https://github.com/enigma-dev/enigma-dev/files/3294712/debug-message-gm81.zip)


This means ENIGMA's version of `show_debug_message` seems to be based on GM8.1. We only show it in debug mode, and since we have no debug window, we just print it to the terminal.

**Comment by RobertBColton** [comment]
Alright, so I went and tested GMSv1.4 and it seems the debug message is just a tad different. The menu in the debug mode window is gone, so instead they printed it to the GMS output window inside the IDE. They will print it in debug and run mode. The compile mode seems to behave the same as GM8.1 and the debug message is not shown.

Download GMSv1.4 Exe: [debug-message-gmsv14.zip](https://github.com/enigma-dev/enigma-dev/files/3294716/debug-message-gmsv14.zip)

**Comment by RobertBColton** [comment]
So, to summarize the ENIGMA differences.
* GMSv1.4 shows debug message in run mode, ENIGMA only shows in debug mode.
* GMSv1.4/GM8.1 use a special output window, ENIGMA just uses the terminal.

I don't see a valid reason to change the behavior in either of these cases, so I don't know if we'll actually do anything.

**Comment by 9Morello** [comment]
FYI, if you build an executable and run it from the terminal, you can see the debug messages (GMS1.4).

**Comment by RobertBColton** [comment]
Really? I can't seem to get it to do that here. See the "debug-message-gmsv14.zip" I posted above? Yeah, I launch it in CMD and I don't get the debug message.

**Comment by RobertBColton** [comment]
Oh, if I extract the compiled exe though and launch the executable inside, I do see it.
![GMSv1.4 Extracted Exe Debug Messages](https://user-images.githubusercontent.com/3212801/59576875-45f64000-908f-11e9-9b1c-26ecd70e2c18.png)

**Comment by time-killer-games** [comment]
What's the point of this now? Since nothing is going to change, I guess this issue can be closed now?

**Comment by RobertBColton** [comment]
No, I said it would maybe be nice to let it go to the output window in RGM or LGM. Letting it open for people to say what they want or think.

**Comment by 9Morello** [comment]
I think letting it go to the output window of the IDE is a good idea.
I believe having it like GMS1.4 (showing messages on normal mode and debug mode) is the way to go.
