### ISSUE TITLE
TODO: Add Virtual Key functions

### ISSUE THREAD

**Issue by time-killer-games** [enigma-dev/enigma-dev#1775]
This is mandatory for any kind of android game seeking to use "gamepad-like" onscreen button controls (keyboard keys simulated at specified rectangular screen areas)

More info on the GameMaker API along these lines found here:
https://docs.yoyogames.com/source/dadiospice/002_reference/mouse,%20keyboard%20and%20other%20controls/virtual%20keys/index.html

**Comment by RobertBColton** [comment]
This one is actually very easy to do, the only challenging part is the virtual keys use screen coordinates which sounds like they can be outside the window. I recommend AssetArray be completed first to store the virtual keys, since that is the primary storage mechanism for resources going forward.

**Comment by RobertBColton** [comment]
Why do they not allow these to work on Windows? It's very possible to add them to Windows too.

**Comment by time-killer-games** [comment]
@RobertBColton they did add it on windows

**Comment by RobertBColton** [comment]
Well this looks pretty good, as in, I could use it for my city building game to provide UI buttons for the build tools. Also, I see by screen coordinates they mean the backbuffer, so not outside the window. I will do it, I just need to get free time to get AssetArray in so I can use it to hold the keys.

**Comment by time-killer-games** [comment]
Thank you! :D

**Comment by RobertBColton** [comment]
I have an in-progress extension proposed in #1805 that's already working. Will announce when it's fully completed. I'm going to add in some extra functionality not present in GM.

**Comment by RobertBColton** [comment]
Closing as resolved by #1805.
