### ISSUE TITLE
*.desktop file generated doesn't link to game correctly

### ISSUE THREAD

**Issue by time-killer-games** [enigma-dev/enigma-dev#1798]
It should look like this:

`Exec=sh -e -c "exec \\"\\$(dirname \\"\\$0\\")/some_app\\"" %k`

Replace 'some_app' with the exported executable name.

It works for me. Got it from here:

https://unix.stackexchange.com/questions/428992/why-do-freedesktop-desktop-files-not-allow-relative-paths

I have no idea where in ENIGMA / LateralGM's code this is handled, so I don't know how to fix this myself, other than the desktop file that gets saved should be written this way.

There is no way to set the icon with a relative path, however. So... fixing that part is a lost cause.

**Comment by fundies** [comment]
https://github.com/enigma-dev/enigma-dev/blob/master/CompilerSource/compiler/compile.cpp#L83

**Comment by fundies** [comment]
youre supposed to edit this file when we you package it as a deb or whatever. I've been over this before
