### ISSUE TITLE
Code Coverage Broke

### ISSUE THREAD

**Issue by RobertBColton** [enigma-dev/enigma-dev#1810]
So, none of the commits or any pull request since #1792 has run code coverage.

**Comment by fundies** [comment]
thats odd cause it deffly runs ci-regression.sh maybe the if [[ "$TRAVIS" -eq "true" ]]; condition is failing on new ubuntu images?

**Comment by fundies** [comment]
https://travis-ci.org/enigma-dev/enigma-dev/jobs/559916169#L6107 I see its still running codecov but theres no reports for it to upload

**Comment by fundies** [comment]
It looks like I may have missed installing lcov on testharness instantance but the testharness should probably error on that

**Comment by RobertBColton** [comment]
Closing as resolved by #1818.
