### ISSUE TITLE
Distribute compiled enigma-dev

### ISSUE THREAD

**Issue by linux-man** [enigma-dev/enigma-dev#1864]
After building enigma-dev on Windows (following instructions at [Install:Windows](https://enigma-dev.org/docs/Wiki/Install:Windows)), I want to distribute it and run outside msys2.
I can do it copying mingw64, usr and dev folders from msys2 to enigma-dev folder, creating a tmp folder and writing enigma.bat:
```
@Echo OFF
PATH = %CD%\mingw64\bin;%CD%\usr\bin;%PATH%
java -jar lateralgm.jar
```
My problem is: enigma is too big! More than 2GB. What can I remove and still make it work?

**Comment by RadThadd** [comment]
I would also like to know a solution. Do you have the "libEGMf.dll" by chance? Mine won't build too many missing files

**Comment by fundies** [comment]
everything in there is needed. Your games are compiled and needs an entire compiler as well as all the unix tools to run the makefiles

**Comment by linux-man** [comment]
@RadThadd I only have compileEGMf.dll and don't have access to it right now.
@fundies I expected to be able to shrink Enigma, based on last enigma-portable.exe size - only 94 Mb.

**Comment by fundies** [comment]
portable.exe has all this stuff it just uses 7zip's "best" compression to shrink it to that size. Once you unpack it it. itll be a similar size

**Comment by linux-man** [comment]
Don't get me wrong, but I can't believe that 7zip best compression gets a 10x smaller file than regular zip! There must be something I'm missing.
Either way, I'll not loose my sleep about this.

**Comment by fundies** [comment]
7zip the folder and youll see. There are many duplicate files cause windows cant do symlinks properly but you will get a 10:1 compression

**Comment by JoshDreamland** [comment]
We will investigate shipping pre-built packages once RadialGM is finished. Shipping a self-contained development environment will be much easier without an arcane JVM dependency. In the interim, feel free to dust off our old "portable" infrastructure. We don't maintain it because it's an enormous pain that would detract from other development, but there's nothing stopping others from doing so.
