### ISSUE TITLE
Add a polygon based collision system.

### ISSUE THREAD

**Issue by fundies** [enigma-dev/enigma-dev#1882]
Title says it all. I would like a 2D polygon based alternative to our "Bounding Box" & "Pixel Perfect" collision systems. I drafted most of one here https://github.com/fundies/Crash2D that I had planned to integrate one day but never got around to it but I would also be open to using something else like box2D.

**Comment by time-killer-games** [comment]
Very impressive to see you wrote your own collision system. Box2D is pretty popular and may be hard to compete with, but I prefer having as much of our codebase done in-house by our own contributors to rely the absolute least we can on third-party deps.

**Comment by RobertBColton** [comment]
While I do think a polygon only collision detection system is very nice, I am not sure about having Box2D as a system as opposed to an extension. With Box2D as an extension it does allow the combined use of both collision detection mechanisms simultaneously as is possible with GMS.
