### ISSUE TITLE
image_load doesn't give good errors

### ISSUE THREAD

**Issue by fundies** [enigma-dev/enigma-dev#1936]
image_load doesn't error when a format isn't supported and instead just runs bmp loader and errors there when it cant read header data. If an image format isn't supported it should give an error message saying so before trying to load it as a bmp.

you can reproduce this by building a game with libpng extension off and trying to load a png using sprite_add or whatever.

**Comment by time-killer-games** [comment]
right, but checking a file's existence is bad because it will prevent a crash and provide a good error
