### ISSUE TITLE
file tests polute test env

### ISSUE THREAD

**Issue by fundies** [enigma-dev/enigma-dev#1950]
@RobertBColton please clean up all the crapola you create in your file func tests as they cause failure on multiple runs.

https://github.com/enigma-dev/enigma-dev/blob/master/CommandLine/testing/SimpleTests/file_input_output.sog/create.edl

This interfering with me running the harness for multiple platforms

**Comment by RobertBColton** [comment]
Alright I prepared #1952 which takes of it I think.
