### ISSUE TITLE
[JSON] short JSONs crash the game

### ISSUE THREAD

**Issue by IntinteDAO** [enigma-dev/enigma-dev#1951]
Hello. What I called the short JSONs are JSONs that have value, and the indexes are iterated. Unfortunately, Enigma-dev does not support such and they crash the game

Long JSON:
{"0":1,"1":4}

Short:
[1, 4]

![obraz](https://user-images.githubusercontent.com/56807194/78401085-37feb500-75f8-11ea-9440-734d7b93d143.png)

**Comment by saifkandil** [comment]
then what is the short for: @IntinteDAO 
```
[
   {
       "0":
            {
                 "0":1,
                 "1":4
            },
       "1": 4
   }, 
   {
       "0": 1,
       "1": 4
   }
]
```

**Comment by IntinteDAO** [comment]
@saifkandil According to PHP: [[[1,4],4],[1,4]]

```
<?php
$json = '[
   {
       "0":
            {
                 "0":1,
                 "1":4
            },
       "1": 4
   },
   {
       "0": 1,
       "1": 4
   }
]';

$table = json_decode($json, TRUE);
echo json_encode($table);

```

**Comment by saifkandil** [comment]
@IntinteDAO 
perfect, it will be done in 4 days isa 
thanks btw, i will provide it for you to test it

**Comment by saifkandil** [comment]
@IntinteDAO 

it's now supported on branch ```short-json-support``` on this PR #2335 , you will just to call ```short_json_decode()``` and pass ur short json
