### ISSUE TITLE
directory_destroy is called directory_delete

### ISSUE THREAD

**Issue by RobertBColton** [enigma-dev/enigma-dev#1953]
ENIGMA has `directory_delete`, which was added to GameMaker as `directory_destroy`.
https://docs.yoyogames.com/source/dadiospice/002_reference/file%20handling/directory_destroy.html

It looks like @time-killer-games was going to fix this in #1072 and #1073 but they were never merged.

Please be aware that I am adding a test for directory_delete in #1952, which will need changed later when this is fixed.

**Comment by RobertBColton** [comment]
I don't know why they'd call it `directory_destroy` when `file_delete` already existed, they're never consistent.

**Comment by fundies** [comment]
did you delete my comment?

**Comment by RobertBColton** [comment]
Closing as resolved by #2036.
