### ISSUE TITLE
Compile failed at C++ level

### ISSUE THREAD

**Issue by Jumpybug214** [enigma-dev/enigma-dev#1974]
I have no idea whats going on. I made a school project in Game Maker Studio, and I loaded it into ENIGMA and every time I try to start the game, it errors. [here is my log](https://pastebin.com/1pbneDLR). I don't understand why its erroring.

**Comment by JoshDreamland** [comment]
Thanks for the report. This is a problem where ENIGMA's compiler thought the code looked right, handed it to GCC, but it was wrong. In this case, one of your objects seems to be named "rand," which happens to be the name of a function in ENIGMA. So the solution is to rename that object.

There may be other resources with similar problems. We hit this problem a lot with converted games, unfortunately.

**Comment by Jumpybug214** [comment]
Thak you.
