### ISSUE TITLE
Wrong sprite loaded in Game Maker 6 example

### ISSUE THREAD

**Issue by sharkwouter** [enigma-dev/enigma-dev#1976]
I've found that some of the examples I used to look at many years ago is able to build and run with Enigma. The game is called 1945 and the example file can be downloaded here: http://rupert.id.au/tutorials/gamemaker/examples.php

I'm using this on Windows 10. I cloned the master branch yesterday and build it using SDL as platform in LateralGM. I build Enigma in MSYS2 using the following instructions: https://enigma-dev.org/docs/Wiki/Install:Windows

The issues I'm seeing are the following:
- Instead of the configured sprite, the sprite below the player sprite is being loaded as player sprite when running. In LateralGM in the object editor the correct sprite is shown.
- The game crashes when the object which uses the last sprite in the sprite list is spawned.

I have seen this issue in more examples (I could share some if needed), but this is a nice one which is publicly available with a good license.

**Comment by sharkwouter** [comment]
I've tested in on Debian 10 as well now, I can reproduce it there.

**Comment by fundies** [comment]
Fix in #1979 will likely be merged today

**Comment by sharkwouter** [comment]
Great! I actually just tested that branch. It does solve the issue for me.

**Comment by sharkwouter** [comment]
The fix for this has been merged and it works, so I'm closing this.
