### ISSUE TITLE
sprite_add() regression

### ISSUE THREAD

**Issue by time-killer-games** [enigma-dev/enigma-dev#2000]
Here's th PNG I'm trying to load with sprite_add():

![m1_1](https://user-images.githubusercontent.com/4379204/80767132-364fe080-8b15-11ea-9294-c22796a0da3d.PNG)

Here's what it looks like drawn to the game after sprite_add() (stretched to fill game window):

![regression](https://user-images.githubusercontent.com/4379204/80767060-fe489d80-8b14-11ea-9635-887a7570abd7.png)

It happens regardless of how you draw it, whether stretched or otherwise.

reproducible gm91 project and png:

[regression.zip](https://github.com/enigma-dev/enigma-dev/files/4561797/regression.zip)

**Comment by RobertBColton** [comment]
Do a git bisect, and when you find out what caused it, be sure to add this to the sprites CI test.

**Comment by time-killer-games** [comment]
nah

**Comment by JoshDreamland** [comment]
Dup'ing against #2003
