### ISSUE TITLE
Test Harness Not Changing Merge Ability

### ISSUE THREAD

**Issue by RobertBColton** [enigma-dev/enigma-dev#2004]
I just realized on #1986 that although the test harness is failing on Azure, it's not preventing the pull request from being merged. It looks like we're still using just AppVeyor/Travis for that, but since fundies moved the test harness in #1946, we should probably change that now.

**Comment by JoshDreamland** [comment]
Isn't Azure still failing? I'm happy to enable it when it's done failing, but afaik it's never passed for all jobs (two have always failed).

**Comment by fundies** [comment]
Azure builds should be passing but there is odd bug where they sometimes don't list all the checks on some prs.

**Comment by RobertBColton** [comment]
Right, so @JoshDreamland go ahead and enable it.

**Comment by JoshDreamland** [comment]
Enabled.
