### ISSUE TITLE
Arch Linux build support

### ISSUE THREAD

**Issue by henriquelalves** [enigma-dev/enigma-dev#2019]
Currently there is an AUR repository to build Enigma easily on Arch: https://aur.archlinux.org/packages/enigma-dev-git/

Unfortunately it's not working anymore, as one of the building steps was to download http://dl.dropbox.com/s/yx0upohoipzfdhv/alure.epackage.2014.12.28 from dropbox, and now it gives a 403.

It was the best option on building Enigma on Arch / Manjaro systems, so it's an quick-win if the 403 problem can be solved easily.

**Comment by fundies** [comment]
just change "python ./install.py" to "./install.sh" in the pkgbuild

**Comment by Hughtech** [comment]
The Wiki have since been updated with its own 'Arch install instructions. check the link here.
https://enigma-dev.org/docs/Wiki/Install:Arch_Linux

please note that its has been installed and tested using Manjaro 32bit and 64bit.

**Comment by henriquelalves** [comment]
Nice, thanks for the clarification. Since there is an official wiki installation guide it doesn't make sense to keep the issue open.
