### ISSUE TITLE
Compile failed at the C++ level - old GM6 game

### ISSUE THREAD

**Issue by rejexx** [enigma-dev/enigma-dev#2024]
I'm trying to bring back an old GM6 game just enough to make a windows 10 executable. I've fixed a bunch of syntax errors, but I'm not exactly sure how to read these error codes from the C++ compile level.  

I'll copy the compile progress below.  Upload of the GM6 file is also included.  I'm on the fence if fixing the errors is worthwhile, or it would require a total re-write.  I'm brand new to LateralGM and the ENIGMA project, just found out about it when I tried to bring back these old games, forgive the ignorance, thanks in advance!

[microscopia_enigma.zip](https://github.com/enigma-dev/enigma-dev/files/4727412/microscopia_enigma.zip)

[CompileDetails.txt](https://github.com/enigma-dev/enigma-dev/files/4727423/CompileDetails.txt)

**Comment by fundies** [comment]
It looks like you have variables that share names with your resources causing conflict as well as a variable or resource named "exit" which conflicts with c++. All these things will need to be renamed to get your game to build

**Comment by rejexx** [comment]
Thank you!
