### ISSUE TITLE
Custom preferences 'looksandfeels' error

### ISSUE THREAD

**Issue by Hughtech** [enigma-dev/enigma-dev#2028]
it seems the method implemented to have your own custom look is not working as stated in the forums page here.

I can change the background image fine but when i try to change the theme i always gets this type of error...

Java Version: 110007 (11.0.7)
java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at org.lateralgm.main.LGM.addURL(LGM.java:651)
	at org.lateralgm.main.LGM.loadLookAndFeels(LGM.java:676)
	at org.lateralgm.main.LGM.main(LGM.java:1059)
Couldn't find class for specified look and feel:com.jtattoo.plaf.acryl.AcrylLookAndFeel
Did you include the L&F library in the class path?
Using the default look and feel.

used the following "~/enigma-dev/lookandfeels/com.jtattoo.plaf.acryl.AcrylLookAndFeel" and com.jtattoo.plaf.acryl.AcrylLookAndFeel" as filepath in the "Theme class:" section but neither worked.
![Screenshot_2020-06-19_12-44-15](https://user-images.githubusercontent.com/19632613/85158980-e21ad000-b22a-11ea-83ae-c1523ac27e61.png)
![Screenshot_2020-06-19_12-45-05](https://user-images.githubusercontent.com/19632613/85159014-ec3cce80-b22a-11ea-9274-86c3a1a829ff.png)

would like some help into solving this.

**Comment by RobertBColton** [comment]
Yeah I am able to reproduce, it seems the entire custom look and feels functionality has broken. However, I don't get an exception like you did, I will need to investigate more.

**Comment by RobertBColton** [comment]
This actually belonged on the LGM tracker hugar, so I've moved it there.
https://github.com/IsmAvatar/LateralGM/issues/493
