### ISSUE TITLE
Show Debug Message Ambiguous

### ISSUE THREAD

**Issue by RobertBColton** [enigma-dev/enigma-dev#2034]
The original version that was in GML no longer works now.
https://docs.yoyogames.com/source/dadiospice/002_reference/debugging/show_debug_message.html

Seems to be too many parameters, idk right now, I'm trying to fix something else when I discovered it.
```
[01m[KC:/Users/Owner/AppData/Local/ENIGMA/Preprocessor_Environment_Editable/IDE_EDIT_objectfunctionality.h:42:29:[m[K [01;31m[Kerror: [m[Kcall of overloaded '[01m[Kshow_debug_message(const char [4])[m[K' is ambiguous
   42 |     show_debug_message("jfc"[01;31m[K)[m[K;
      |                             [01;31m[K^[m[K
```

**Comment by RobertBColton** [comment]
Ah, it was because we have two declarations of it.

https://github.com/enigma-dev/enigma-dev/blob/dae5669a7415bd72d9efa503d523448148a61812/ENIGMAsystem/SHELL/Universal_System/terminal_io.h#L36
https://github.com/enigma-dev/enigma-dev/blob/dae5669a7415bd72d9efa503d523448148a61812/ENIGMAsystem/SHELL/Widget_Systems/widgets_mandatory.h#L78

**Comment by fundies** [comment]
you can delete the terminal_io one

**Comment by RobertBColton** [comment]
There are other issues, including the fact that the output is never flushed and the implementation was duplicated for 4 platforms.

**Comment by RobertBColton** [comment]
Also #1752 instead of going to the terminal these messages are later supposed to be forwarded to the IDE.

**Comment by fundies** [comment]
Well the ide can just capture stdout of game process but the point of me unifying all the printing so it's easier to send messages wherever you want. (To the IDE, To the terminal, to a Dialog) However, I wasn't interested in cleaning up the duplicate code we had from the 12 widget systems tkg had added :P
