### ISSUE TITLE
Deepin Linux Dock showing in fullscreen with some games

### ISSUE THREAD

**Issue by time-killer-games** [enigma-dev/enigma-dev#2051]
A regression! i seemed to have sniffered it out...

Taskbar / System Tray is visible in deepin linux in mg_keystroke's game:
![Screen Capture_20200627220836](https://user-images.githubusercontent.com/4379204/85935847-03328f00-b8c3-11ea-9ba9-55486df08ad9.png)

But it isn't with my key to success... weird?
![Screen Capture_20200627221139](https://user-images.githubusercontent.com/4379204/85935870-34ab5a80-b8c3-11ea-884a-291a5f40164b.png)

Anyways, I'm going to see if this happens with more mainstream taskbars / system trays, such as plank, and whatever gnome/kde/xfce uses...

**Comment by fundies** [comment]
This seems like an issue w/ your linux flavor of the week.  If you cant repro this on more common DE's like xfce or gnome please close this. Also, fix your title

**Comment by time-killer-games** [comment]
@fundies fair enough, if i find this on more common ones l'll re-open. XFCE, GNOME, and KDE i'll consider the most common for now, since they are top 3 officially supported by manjaro. I haven't actually tested this yet, as I've been busy with other things, but I'll get around to it eventually.
