### ISSUE TITLE
Draw Background Extended Regression

### ISSUE THREAD

**Issue by RobertBColton** [enigma-dev/enigma-dev#2064]
Not sure of the origin, but I want to blame #1975 for it. This occurs with the official GameMaker 7 "space cleaner.gmk" example. The game has a background whose size (640x480) is equal to that of the room. The background is set to visible with stretch enabled, which causes our graphics backend to delegate it to `draw_background_ext` to draw.

![Space Cleaner Background Bug](https://user-images.githubusercontent.com/3212801/86160576-f471f500-bad9-11ea-95cb-86a93229e58a.png)

**Comment by RobertBColton** [comment]
Ah I found the regression, it's because fundies didn't pad any of the backgrounds loaded from the executable.
https://github.com/enigma-dev/enigma-dev/pull/1975/files#diff-b4e42a188c146250097c203c7ef5ce15R95-R98

**Comment by fundies** [comment]
see #2008
