### ISSUE TITLE
BMP read/write bugs

### ISSUE THREAD

**Issue by fundies** [enigma-dev/enigma-dev#2101]
Our current BMP write code doesn't seem to write a proper header. Other programs seem to open them fine however enigma's reader errors. I've bypassed this error for now in #2008 by forcing rgba format but this seems incorrect.

**Comment by KartikShrivastava** [comment]
Hi @fundies, I was trying to understand other bitmap encoders and have a question that should `image_save_bmp` support to `24bit no alpha` is the fix for this issue.

**Comment by JoshDreamland** [comment]
In theory we should support multiple pixel formats, but our internal storage format is 32-bit RGBA (well, ABGR based on little endian). So forcing that format sounds correct, but our header is probably using an old bitmap version that isn't compatible with alpha, or something.

**Comment by KartikShrivastava** [comment]
Hi, I've referenced following three resources, 1st is [BMP wiki](https://en.wikipedia.org/wiki/BMP_file_format), another one is lime BMP encoder code [BMP encoder](https://github.com/haxelime/lime/blob/4adb7d638d15612e2542ae3a0ef581a786d21183/src/lime/_internal/format/BMP.hx) rest two are SO posts [Post 1](https://stackoverflow.com/questions/14195289/can-a-bmp-image-format-handle-transparency) and [Post 2](https://stackoverflow.com/questions/59632643/transparency-on-a-32-bit-bmp-doesnt-do-anything) which helped me understand how to app transparency to bmp.

According to wiki a 108 byte `BITMAPV4HEADER` is required with `BI_BITFIELDS` as compression bit to support transparency. With the new header we need to set extra bit mask for each channel. As I understood the bit mask part is basically setting 255 value for the corresponding byte for corresponding channel according to the output image format.

These are the new bytes to be added:
1. 16 byte Channel mask bits (for RGBA) R`0x00FF0000` G`0x0000FF00` B`0x000000FF` A`0xFF000000`.
2. 4 byte windows little-endian `0x206E6957`.
3. 48 empty bytes.

**Comment by KartikShrivastava** [comment]
Hi, I've created a PR with the mentioned changes, kindly review it and let me know if updates are needed.

**Comment by RobertBColton** [comment]
Please link pull requests with the hashtag for future reference. It's easier to find from context.

**Comment by KartikShrivastava** [comment]
Sure, will take care of that.
