### ISSUE TITLE
(Ubuntu 20.xx) vk_esc is being reported as constantly pressed & released when 'Let <Esc> end the game' is disabled

### ISSUE THREAD

**Issue by mikeypro83** [enigma-dev/enigma-dev#2108]
### Describe the bug
Under Ubuntu, if you disable esc to close the game, vk_esc will constantly be pressed&released by the enigma engine thefore rendering the use of the vk_esc key impossible.

### Steps To Reproduce
1. start a project, in the project settings under other -> default keys uncheck "let <esc> end the game"
2. provide visual feedback for proof: display some kind of visual for when vk_esc is pressed and when vk_esc is released.
```gml
draw_text(0,0,
          string(keyboard_check_pressed(vk_escape)) + " " +
          string(keyboard_check_released(vk_escape))
);
```
3. run the project

### Parse & Compiler Bugs
none.

### Expected behavior
vk_esc should only be reported when the corresponding button on the keyboard is pressed/released.

### ENIGMA Configuration:
* OS: Ubuntu
* Platform: SDL

**Comment by RobertBColton** [comment]
I'm wondering if this is actually related to the LGM game settings issue from #2109, you could actually try v1.8.159 until I send a fix and see if it is or not.

**Comment by RobertBColton** [comment]
@mikeypro83 I'm not able to reproduce this on Windows with SDL and I really can't believe this is the observed behavior. I tested with both LGM v1.8.184 and v1.8.183 with and without the game settings save fix. Which I am also confused about how you were disabling the game setting when v1.8.183 had a regression preventing you to actually change game settings.

**Comment by RobertBColton** [comment]
@mikeypro83 in fact, there is no handle of that setting on any platform except Windows right now. 

We can search the repository for the `treatCloseAsEscape` internal variable controlled by the setting.
https://github.com/enigma-dev/enigma-dev/search?q=treatCloseAsEscape&unscoped_q=treatCloseAsEscape
We have a comment in the source mentioning this.
https://github.com/enigma-dev/enigma-dev/blob/02b54e017cd8448649d9003ccf117609c6fdb0ed/ENIGMAsystem/SHELL/Platforms/platforms_mandatory.h#L112
We can also just see from the search that no general platform code or the SDL platform code is even reading the variable.

**Comment by mikeypro83** [comment]
I will start with, I've updated to the latest with the fixed settings and verified that vk_esc is still being fired off at all times. This is under Ubuntu 20.whatever with the SDL platform chosen. I can tell you that when it came to the esc key to close game setting, it was being saved what I chose before the fix,  but platform and other settings were not being saved. Have not verified platform and those other settings are being saved yet but I'm working on it. Not lot of time to put into this. If you need anything let me know. 

Sent from Yahoo Mail on Android 
 
  On Sat, Aug 15, 2020 at 8:13 PM, Robert Colton<notifications@github.com> wrote:   


@mikeypro83 I'm not able to reproduce this on Windows with SDL and I really can't believe this is the observed behavior. I tested with both LGM v1.8.184 and v1.8.183 with and without the game settings save fix. Which I am also confused about how you were disabling the game setting when v1.8.183 had a regression preventing you to actually change game settings.

**Comment by mikeypro83** [comment]
Curious, I enabled let escape close the game and compiled and ran the project and escape now closes the game. Disabled it, compiled and ran, esc is constantly fired. So I have no idea what magic is going on, but it looks like what your search pulled up... is wrong at some level. Not looking in the right spot? Old code in lgm or somewhere else doing stuff it no longer should? I don't know the internals so I am no help here.

    On Saturday, August 15, 2020, 11:17:19 PM MDT, Michael Stuart <michaelscottstuart@yahoo.com> wrote:  
 
 I will start with, I've updated to the latest with the fixed settings and verified that vk_esc is still being fired off at all times. This is under Ubuntu 20.whatever with the SDL platform chosen. I can tell you that when it came to the esc key to close game setting, it was being saved what I chose before the fix,  but platform and other settings were not being saved. Have not verified platform and those other settings are being saved yet but I'm working on it. Not lot of time to put into this. If you need anything let me know. 

Sent from Yahoo Mail on Android 
 
  On Sat, Aug 15, 2020 at 8:13 PM, Robert Colton<notifications@github.com> wrote:   


@mikeypro83 I'm not able to reproduce this on Windows with SDL and I really can't believe this is the observed behavior. I tested with both LGM v1.8.184 and v1.8.183 with and without the game settings save fix. Which I am also confused about how you were disabling the game setting when v1.8.183 had a regression preventing you to actually change game settings.

**Comment by mikeypro83** [comment]
To clarify, when I disable let esc close the game, vk_esc is constantly fired, it does not close the window (as expected), but vk_esc is spammed as being pressed and released. when enabled, vk_esc does close the game as expected.

    On Saturday, August 15, 2020, 11:24:02 PM MDT, Michael Stuart <michaelscottstuart@yahoo.com> wrote:  
 
  Curious, I enabled let escape close the game and compiled and ran the project and escape now closes the game. Disabled it, compiled and ran, esc is constantly fired. So I have no idea what magic is going on, but it looks like what your search pulled up... is wrong at some level. Not looking in the right spot? Old code in lgm or somewhere else doing stuff it no longer should? I don't know the internals so I am no help here.

    On Saturday, August 15, 2020, 11:17:19 PM MDT, Michael Stuart <michaelscottstuart@yahoo.com> wrote:  
 
 I will start with, I've updated to the latest with the fixed settings and verified that vk_esc is still being fired off at all times. This is under Ubuntu 20.whatever with the SDL platform chosen. I can tell you that when it came to the esc key to close game setting, it was being saved what I chose before the fix,  but platform and other settings were not being saved. Have not verified platform and those other settings are being saved yet but I'm working on it. Not lot of time to put into this. If you need anything let me know. 

Sent from Yahoo Mail on Android 
 
  On Sat, Aug 15, 2020 at 8:13 PM, Robert Colton<notifications@github.com> wrote:   


@mikeypro83 I'm not able to reproduce this on Windows with SDL and I really can't believe this is the observed behavior. I tested with both LGM v1.8.184 and v1.8.183 with and without the game settings save fix. Which I am also confused about how you were disabling the game setting when v1.8.183 had a regression preventing you to actually change game settings.

**Comment by RobertBColton** [comment]
That's possible mikey, but also, this may be an SDL bug in the SDL that Ubuntu 20 happens to be shipping. It's really quite odd I would like @time-killer-games and some others to try reproducing. I asked Hugar on Discord to run the test code I put into your original issue and he got the same result as me and GM8.1, it draws 0s and for 1 frame while you press and release escape each side flashes to 1 meaning pressed/released respectively. They are never both 1 at the same time regardless of whether the setting is enabled, which is what it sounds like you are telling us you are seeing on your end.

**Comment by mikeypro83** [comment]
> That's possible mikey, but also, this may be an SDL bug in the SDL that Ubuntu 20 happens to be shipping. It's really quite odd I would like @time-killer-games and some others to try reproducing. I asked Hugar on Discord to run the test code I put into your original issue and he got the same result as me and GM8.1, it draws 0s and for 1 frame while you press and release escape each side flashes to 1 meaning pressed/released respectively. They are never both 1 at the same time regardless of whether the setting is enabled, which is what it sounds like you are telling us you are seeing on your end.

Miscommunication. What I am saying is with let esc close the game disabled, vk_esc is being fired off like i am tapping the key very quickly the entire time, but I am not. if i attempt to check for vk_esc it is always reported as pressed.

**Comment by mikeypro83** [comment]
Side-note: Double-checked, API Platform setting is not being saved. Probably others as well.

    On Saturday, August 15, 2020, 11:29:01 PM MDT, Robert Colton <notifications@github.com> wrote:  
 
 


That's possible mikey, but also, this may be an SDL bug in the SDL that Ubuntu 20 happens to be shipping. It's really quite odd I would like @time-killer-games and some others to try reproducing. I asked Hugar on Discord to run the test code I put into your original issue and he got the same result as me and GM8.1, it draws 0s and for 1 frame while you press and release escape each side flashes to 1 meaning pressed/released respectively. They are never both 1 at the same time regardless of whether the setting is enabled, which is what it sounds like you are telling us you are seeing on your end.

**Comment by fundies** [comment]
is this only the escape key? or does it happen with any other keys?

**Comment by RobertBColton** [comment]
@mikeypro83 this is a really strange issue, when the setting is _enabled_, does the game stay open? As fundies said, does it occur with any other keys? Most importantly, could you maybe try making a native C++ SDL app or testing some other program for pressed/released of escape if you have time? I wouldn't even rule out a hardware issue with your keyboard here because what you're seeing is quite strange.

**Comment by mikeypro83** [comment]
Only the esc key acts this way in combination with disabling and enabling the use esc to close game option. The other keys, such as f4 still do nothing at all even if their options are enabled but those keys, I can use them fine in scripts. 

Sent from Yahoo Mail on Android 
 
  On Sun, Aug 16, 2020 at 1:54 AM, Greg Williamson<notifications@github.com> wrote:   


is this only the escape key? or does it happen with any other keys?

**Comment by mikeypro83** [comment]
Yes, it works properly when the option is enabled. It won't close until I press escape. will make something here in an hour or so to test sdl.  Escape key works fine in every other app I use. Open calc, aesprite, Firefox, etc. 

My little sdl test app basically runs this every loop:
            inline void Update(void)
            {
                SDL_memcpy( &m_PrevEvent, &m_Event, sizeof(SDL_Event) );
                SDL_memset( &m_Event, 0, sizeof(SDL_Event) );            
                SDL_PollEvent( &m_Event );

                switch(m_Event.type) 
                {
                    case SDL_QUIT:
                        break;
                    case SDL_KEYUP:
                        switch ( m_Event.key.keysym.sym ) 
                        {    
                            case SDLK_RETURN:
                                break;
                            case SDLK_ESCAPE:
                                Stop();
                                break;
                        }
                        break;
                    default:
                        break;
                }    
            }
and it works as intended.

Sent from Yahoo Mail on Android 
 
  On Sun, Aug 16, 2020 at 8:39 AM, Robert Colton<notifications@github.com> wrote:   


@mikeypro83 this is a really strange issue, when the setting is enabled, does the game stay open? As fundies said, does it occur with any other keys? Most importantly, could you maybe try making a native C++ SDL app or testing some other program for pressed/released of escape if you have time? I wouldn't even rule out a hardware issue with your keyboard here because what you're seeing is quite strange.

**Comment by RobertBColton** [comment]
@mikeypro83 ok so I got the chance to test Ubuntu 20 in my Virtual Machine and I'm not seeing what you describe. I have the setting disabled, and with checking `keyboard_check_pressed`/`keyboard_check_released` nothing is being reported when I'm not pressing the key. If you could, I'd like to suggest you try your SDL test again one more time, and this time check `SDL_KEYDOWN` instead of up, and let me know if SDL stays open/escape is registered when you don't press anything.

![Ubuntu 20 SDL Platform Escape Key Testing](https://user-images.githubusercontent.com/3212801/90528392-8d1f0b80-e140-11ea-9af0-cc9839430f16.png)

**Comment by mikeypro83** [comment]
I changed the test code and it works as expected, it loops until I press escape, prints ESC then exits.

				switch(m_Event.type) 
				{
					case SDL_QUIT:
						break;
					case SDL_KEYDOWN:
							printf(  (m_Event.key.keysym.sym==SDLK_ESCAPE?"ESC":"KEY") );
						break;
					case SDL_KEYUP:
						switch ( m_Event.key.keysym.sym ) 
						{	
							case SDLK_RETURN:
								break;
							case SDLK_ESCAPE:
								Stop();
								break;
						}
						break;
					default:
						break;
				}	
			}

**Comment by mikeypro83** [comment]
Additional Screenshots. In this test I am _NOT_ pressing any keys. And if I press a key that is not esc it will show NADDA for a split second before going back to reporting ESC PRESSED.

![enigma-esc-key-test](https://user-images.githubusercontent.com/41976933/90806108-cd65c180-e2d9-11ea-8902-65d3a2e6adb2.png)
![enigma-esc-key-test-settings](https://user-images.githubusercontent.com/41976933/90806112-ce96ee80-e2d9-11ea-8849-4c8f326cdf93.png)

**Comment by RobertBColton** [comment]
Alright, I have a few more ways to find out, but you'll need to continue working with me to get this resolved. So what happens when ENIGMA/GM get a keyboard down event is they copy the current state into a separate array of the last frame keyboard state, then they set the current keyboard state.
https://github.com/enigma-dev/enigma-dev/blob/c1af8483fc6b259bfa5fe842b386b8ccaa3bbbe8/ENIGMAsystem/SHELL/Platforms/SDL/Event.cpp#L229
Every frame the input state is updated such that the current state is copied to the previous state.
https://github.com/enigma-dev/enigma-dev/blob/f5c89f1299b0f78434d935d1e448a35fe818543c/ENIGMAsystem/SHELL/Platforms/General/PFwindow.cpp#L44

Could you try adding a cout/print statement to those functions and tell us what happens? This is exactly the code path that is handling the keyboard pressed check. That function simply checks the current state if the key is down and if the previous state for if the key was not down.

**Comment by mikeypro83** [comment]
I added some printf reports and all that, recompiled , everything was reporting no key presses, so I looked at PFWindow.h and the key defines, then it hit me:
 I am dumb. I was checking vk_esc, NOT vk_escape. I don't know why the crap I thought vk_esc was the right name.  Sorry for wasting our time.


    On Thursday, August 20, 2020, 12:04:39 PM MDT, Robert Colton <notifications@github.com> wrote:  
 
 


Alright, I have a few more ways to find out, but you'll need to continue working with me to get this resolved. So what happens when ENIGMA/GM get a keyboard down event is they copy the current state into a separate array of the last frame keyboard state, then they set the current keyboard state.
https://github.com/enigma-dev/enigma-dev/blob/c1af8483fc6b259bfa5fe842b386b8ccaa3bbbe8/ENIGMAsystem/SHELL/Platforms/SDL/Event.cpp#L229
Every frame the input state is updated such that the current state is copied to the previous state.
https://github.com/enigma-dev/enigma-dev/blob/f5c89f1299b0f78434d935d1e448a35fe818543c/ENIGMAsystem/SHELL/Platforms/General/PFwindow.cpp#L44

Could you try adding a cout/print statement to those functions and tell us what happens? This is exactly the code path that is handling the keyboard pressed check. That function simply checks the current state if the key is down and if the previous state for if the key was not down.

**Comment by RobertBColton** [comment]
That's great news, and that's so funny because I even copied your screen but with `vk_escape` instead of the typo, so that's really funny. I am so glad it turned out to be something simple like this. 👍 And yeah, this is kind of one of the side effects of GML being dynamically typed.

**Comment by mikeypro83** [comment]
At best, this is an unexpected behaviors issue but GML is loose af anyway; I really don't expect it to verify that a number variable I am sending it is valid or not.

**Comment by RobertBColton** [comment]
On second thought, we could maybe still change our keyboard functions now that I thought about it. We aren't doing any debug mode bounds checking and just do `& 0xFF` which normalizes the keyboard constant you pass between 0 and 255. I think we should in fact add a debug check that would error if the constant is outside that range.

**Comment by mikeypro83** [comment]
I vote yae. Lol. 

Sent from Yahoo Mail on Android 
 
  On Thu, Aug 20, 2020 at 1:14 PM, Robert Colton<notifications@github.com> wrote:   


On second thought, we could maybe still change our keyboard functions now that I thought about it. We aren't doing any debug mode bounds checking and just do & 0xFF which normalizes the keyboard constant you pass between 0 and 255. I think we should in fact add a debug check that would error if the constant is outside that range.

**Comment by RobertBColton** [comment]
Ok I've sent #2117, however, it wouldn't actually catch this specific mistake due to "Treat uninitialized variables as 0" and 0 being `vk_nokey` in GM. The pull request is open to suggestions from anybody with any ideas about that.

**Comment by mikeypro83** [comment]
I thought about that scenario and Personally I feel assigning a 'wrong' variable name to a nokey is better than interpreting it as a key with a true keypress value. The two outcomes are no change and people report the same mistake I did or with the changes people report a key isn't reporting keypress because of their typo. I think because I got a keypress true report it helped me passively assume my vk_esc was correct, why would a bad var name report true, dynamically, should it not have a base zero/false value and therefore never return a new var as true? So under that kind of mentality, clamping the value, I think it would decrease cases of an issue arising. 

Sent from Yahoo Mail on Android 
 
  On Thu, Aug 20, 2020 at 1:58 PM, Robert Colton<notifications@github.com> wrote:   


Ok I've sent #2117, however, it wouldn't actually catch this specific mistake due to "Treat uninitialized variables as 0" and 0 being vk_nokey in GM. The pull request is open to suggestions from anybody with any ideas about that.

**Comment by mikeypro83** [comment]
Thanks Robert! 

Sent from Yahoo Mail on Android 
 
  On Thu, Aug 20, 2020 at 1:58 PM, Robert Colton<notifications@github.com> wrote:   


Ok I've sent #2117, however, it wouldn't actually catch this specific mistake due to "Treat uninitialized variables as 0" and 0 being vk_nokey in GM. The pull request is open to suggestions from anybody with any ideas about that.
