### ISSUE TITLE
Some of the mouse events are not behaving correctly

### ISSUE THREAD

**Issue by TheOuterLinux** [enigma-dev/enigma-dev#2133]
### Describe the bug
This is regarding the noob-friendly mouse events and not a script within a step event. The left and right mouse release need to be switched. Mouse wheel up and down behave in a global-like way instead of when the mouse is on top of the object, and global left and right both essentially behave as an "any click."

### Steps To Reproduce
1. Create sprite
2. Create object that uses sprite
3. Add a left or right mouse release event, mouse wheel up or down event, or global left and right release event
4. Add a script to one of the mouse events that does something like "instance_destroy()"
5. Add a few of those objects to a room
6. Run
7. Click on the objects with left or right mouse or use the scroll wheel depending on which you chose

### Expected behavior
The left and right release events need to be switched as the behave backwards. Right-release clicking an object is destroying it when left-release click should be and visa versa.

The mouse wheel up and down act globally, but I'm not exactly sure if that is what is supposed to happen or if only do what is in the event if the mouse is on top of the object. Right now, all objects are destroyed when moving the mouse wheel, whether or not the mouse is on top.

The global left and right release behave the same. In other words, if I want all the objects to destroy on "global left release," they will regardless of a left or right release and the same goes with "global right release," as if both were treated as an "any click release."

### ENIGMA Configuration:
* Linux
* Tried on both X11 and SDL as well as all available OpenGL versions.

**Comment by Hughtech** [comment]
i've been able to re-produced this bug on my Opensuse laptop.. It pertains to all the 'mouse_[button]_released' events.

**Comment by Hughtech** [comment]
confirmed that this has happen also on my Linux Mint machine as well.
[event_test.gmk.zip](https://github.com/enigma-dev/enigma-dev/files/5182875/event_test.gmk.zip)

![Screenshot_2020-09-07_07-39-14](https://user-images.githubusercontent.com/19632613/92384027-5738cb80-f0dd-11ea-98f6-667ded47dfc3.png)

**Comment by RobertBColton** [comment]
Alright, I was able to reproduce some of this, but part of what you said is intended behavior.

I recreated your steps but using color, with spacebar restarting the room.
Download: [mouse-test-lite.zip](https://github.com/enigma-dev/enigma-dev/files/5518903/mouse-test-lite.zip)

>The mouse wheel up and down act globally, but I'm not exactly sure if that is what is supposed to happen or if only do what is in the event if the mouse is on top of the object.

The mouse wheel events in GM8.1 are global. You can run my example in GM8.1 lite to see.

**Comment by RobertBColton** [comment]
@TheOuterLinux Alright I've sent #2152 to fix the left/right local release events, the mouse wheel is not an actual issue, and I can't repro the global left/right release problem. When I set a different color for global left/right mouse events and release, the middle button doesn't do anything and the buttons are not backwards. That's regardless of whether I test them both or independently. You'll have to be more specific or provide an example for only that remaining issue by itself.

**Comment by RobertBColton** [comment]
Ok it was merged, this should be resolved then. @Hughtech in your recreated example, there's nothing wrong with the second purple row, you made all 3 events destroy the purple objects. They behave as I expect them to, only the object I click on is deleted.

If you guys have anymore issues or can clarify any remaining issue better, please reply.
