### ISSUE TITLE
FileDropper broke azure cross compile job.

### ISSUE THREAD

**Issue by fundies** [enigma-dev/enigma-dev#2146]
@time-killer-games your file dropper extension seems to have broken the azure cross compile job. It looks like you're missing an include somewhere.

**Comment by time-killer-games** [comment]
odd, this should be old news as the only thing i changed was the icon. Anyways, I'll take a look at and see what i can do.

**Comment by time-killer-games** [comment]
ChangeWindowMessageFilter requires Vista or later according to microsoft docs. I'd change the wine compatiblity mode to vista if that would fix it though I'm not the one who maintains cross-compile stuff so idk how to do stuff like that. The problem i assume might also be it doesn't recognize the macro i am using to determine windows version.

**Comment by time-killer-games** [comment]
Ok now i really do not have any idea. That function requires the windows header, which we have in there, and it detected the version of MinGW required.
https://github.com/time-killer-games/enigma-dev-fork/blob/b671faa0684eb73f65a34b4bd5bdb086f26c493a/ENIGMAsystem/SHELL/Universal_System/Extensions/FileDropper/FileDropper.cpp#L99

**Comment by fundies** [comment]
its a compile error. wine is irrelevant

**Comment by time-killer-games** [comment]
you are correct. macros were deprecated and eventually removed in favor of ones that represent both 64-bit and 32-bit mingw, not either/or.

**Comment by fundies** [comment]
fixed by #2147
