### ISSUE TITLE
Rebuild All Broke Again By Shared libpng

### ISSUE THREAD

**Issue by RobertBColton** [enigma-dev/enigma-dev#2158]
If you do rebuild all and then try to run again from LGM, the build fails on libpng. You have to go back to the command line and manually make the frontend stuff again. Then you can open LGM and the build completes.

**Comment by fundies** [comment]
does #2164 help this?

**Comment by RobertBColton** [comment]
Yeah, I didn't know that when I approved it though, I thought it was related to the build. This is resolved by #2164, I can rebuild all just fine now.
