### ISSUE TITLE
Dialogs Update 2020

### ISSUE THREAD

**Issue by time-killer-games** [enigma-dev/enigma-dev#2177]
I would like to update dialogs (again) which I haven't done in a long time. 

New features include: 

**Setting dialog icon from PNG file** (which is standard for Linux, FreeBSD, and Mac Apps). On Linux/FreeBSD the usual way of setting a window icon is based on a file in the system icons directory so different icon themes can alter the appearance of the window icon relative to the current icon theme set by the user. If your game gets popular enough people will catch on and make their own icon themes that include your game icon much like Super Tux and similar games have due their level of popularity. (at least I think that's how it works). This is not a standard practice on Windows however if you don't set an icon from file it will copy the one used from the main game window automatically on Windows, so this feature isn't really needed on there for that reason. MacOS supports PNG natively for NSAlert icons stored in your app bundle and due to the standard use of app bundles on Mac it will make your app self-contained as one *.app "file".

**VisualBasic-like InputBox for Windows** Microsoft created no standard InputBox dialog in Win32, however they did for VB and VBScript. With the IActiveScript Interface you may interpret VBScript to implement the VB/VBS-style Input Box. My DialogModule DLL I wrote does just that, and it is ABI compatible with ENIGMA, however you guys don't like DLL files and want it to say as one executable. Since we don't support building with Visual Studio yet, and resort to using MinGW, the only suggestion I can make is taking a 32-bit and a 64-bit dll and convert them to char arrays which will be written to a temp directory at runtime like how some self-extracting EXE's use their dependencies while staying one EXE file. I only intend to do this on Windows. The other platforms aren't reliable at keeping backwards compatibility like MS is known for.

**Button Localization for Dialogs** that don't get translated by the system automatically. No further explanation needed. Not everyone can read English so having partially English and partially fill-in-the-blank-language is a very huge eyesore.

If @JoshDreamland would approve of these changes before I go through the trouble of making the PR that would be nice. Most of the code would just be copy-pasted from my DialogModule DLL repository into my ENIGMA pr. However I would need to convert the DialogModule Windows DLL to a char array and handle all that code using the External Functions extension as a necessary dependency. Yes providing dialogs that appear somewhat "native" to the OS or "familiar" to the user I consider very important so games won't scream "this was made with ENIGMA" with a customized InputBox dialog.

A lot of people don't like GameMaker Studio's custom dialogs for that very reason, being custom and only used recognizably in GameMaker Studio, it screams "Made with GameMaker" which is very bad and looks unprofessional.

As for Mac, not much will change that I can foresee Josh will object to the way I've written it. Linux and FreeBSD still use and rely on that thing Josh called a "weird fork() usage" unfortunately I've been working on other ways that don't need fork and haven't been able to find a working solution over the past 3 or 4 years I've been at it. Please just let me use fork(). I'm completely out of ideas, unless Josh you have an idea that works and you tested already yourself that doesn't need fork(), and you can verify that without asking me to try it for you, I don't see any other way I'd be willing to try more ways to get it working that don't involve fork. Please tell me Josh you even remember what I'm talking about; see here:

https://github.com/time-killer-games/DialogModule

Now one thing I can almost guarantee Josh won't approve of, is the way I handled async Mac dialogs. It involves running a Mac executable I wrote from the shell much like KDialog/Zenity although we don't have much else as an option because macOS only allows UI elements to be created and/or modified within the main thread. You can't create async dialogs with multithreading the way we have this set up. std::thread will crash if you try to create a Mac NSWindow / NSPanel / NSAlert because that would run outside the main thread which is reserved for all UI handling on macOS. Blame Steve Jobs. Working async dialogs are better than the current segfault we get on Mac when you try to use the async extension.

@JoshDreamland close this issue if you don't like these ideas, but it would make me very damn happy if you'd allow it. Seeing as I can't remember the last time you merged a pr from me within the year of 2020, at least not in my memory.

But I would appreciate you telling me all the reasons you closed it if you did. It honestly wouldn't take long for me to add this stuff as I already did most the work already all the code is written pretty much it will just need char * replaced with std::string for strings and stuff like that other than what I have mentioned above, which again won't take long to do.

I don't see dialogs needing anymore updates after this other than maintenance when stuff breaks. I've been wanting this stuff from my repository put in enigma for roughly a year or two now, for almost every feature I mentioned above.

**Comment by JoshDreamland** [comment]
If you have a reasonably-sized code change, I can look it over. We don't want to version binaries.

Something we could do to make this process a little easier is use Git submodules for large extensions. Each extension could have its own repository and could version as many binaries as it likes.

**Comment by time-killer-games** [comment]
@JoshDreamland this is what i meant by a char array creating the dll https://github.com/enigma-dev/enigma-dev/pull/2178/files

I basically did this in MinGW:
```
cd /c/path/to/mydllfolder/
xxd -i 'libdlgmod32.dll' | sed 's/\([0-9a-f]\)$/\0, 0x00/' > 'libdlgmod32.h'
xxd -i 'libdlgmod64.dll' | sed 's/\([0-9a-f]\)$/\0, 0x00/' > 'libdlgmod64.h'
```

Using the DLL's compiled with Visual Studio on Windows with the exact source code from here:
https://github.com/time-killer-games/DialogModule

Let me know whether you have any objections about this before I work on Cocoa and xlib.
