### ISSUE TITLE
file_bin_read_byte() skips bytes 09, 0A, 0B, 0C, 0D and 20; fileio.cpp

### ISSUE THREAD

**Issue by van0014** [enigma-dev/enigma-dev#2184]
The function 'file_bin_read_byte()' skips certain characters (In ENIGMAsystem/SHELL/Universal_System/fileio.cpp)
This is the part of the function that skips: "enigma::files.get(fileid).fs >> byte;", at line: 223;

[skip_byte_bug.gm81.zip](https://github.com/enigma-dev/enigma-dev/files/5922121/skip_byte_bug.gm81.zip)

These bytes are skipped: 09 0A 0B 0C 0D 20

### Steps To Reproduce
Call file_bin_read_byte() in a file that has any of these bytes: 09 0A 0B 0C 0D 20. These may all be skipped over

### ENIGMA Configuration:
* Manjaro, also happens on MSYS2

**Comment by fundies** [comment]
fixed by #2185
