### ISSUE TITLE
protopooped!

### ISSUE THREAD

**Issue by time-killer-games** [enigma-dev/enigma-dev#2208]
after installing all deps as instructed from the wiki,

I simply: 

git clone https://github.com/enigma-dev/enigma-dev
cd enigma-dev
make # gmake on freebsd

and wammo! the protofbufs are protopooped!

make -C shared/protos/
make[1]: Entering directory '/home/neon/enigma-dev/shared/protos'
mkdir -p .eobjs
protoc -I. --grpc_out=.eobjs --plugin=protoc-gen-grpc= server.proto
: program not found or is not executable
--grpc_out: protoc-gen-grpc: Plugin failed with status code 1.
protoc -I. --cpp_out=.eobjs Action.proto
protoc -I. --cpp_out=.eobjs Path.proto
protoc -I. --cpp_out=.eobjs Settings.proto
protoc -I. --cpp_out=.eobjs Sprite.proto
protoc -I. --cpp_out=.eobjs treenode.proto
protoc -I. --cpp_out=.eobjs EventDescriptor.proto
protoc -I. --cpp_out=.eobjs Script.proto
protoc -I. --cpp_out=.eobjs GameInformation.proto
protoc -I. --cpp_out=.eobjs compiler.proto
protoc -I. --cpp_out=.eobjs Room.proto
protoc -I. --cpp_out=.eobjs Timeline.proto
protoc -I. --cpp_out=.eobjs Shader.proto
protoc -I. --cpp_out=.eobjs game.proto
protoc -I. --cpp_out=.eobjs Background.proto
protoc -I. --cpp_out=.eobjs Font.proto
protoc -I. --cpp_out=.eobjs options.proto
protoc -I. --cpp_out=.eobjs Sound.proto
protoc -I. --cpp_out=.eobjs project.proto
protoc -I. --cpp_out=.eobjs Object.proto
protoc -I. --cpp_out=.eobjs server.proto
protoc -I. --cpp_out=.eobjs Include.proto
make[1]: *** No rule to make target '.eobjs/server.grpc.pb.cc', needed by '.eobjs/Path.pb.o'.  Stop.
make[1]: Leaving directory '/home/neon/enigma-dev/shared/protos'
make: *** [Makefile:42: libProtocols] Error 2

Happens on both KDE neon (basically Ubuntu amd64 with bleeding edge KDE) and FreeBSD, also with a minimal KDE amd64 setup. Oh an I'm pretty sure it happens on Arch Linux (moreover, aarch64 Manjaro KDE) as well, but I am about to double check.

KDE neon is based on Ubuntu 20.04 LTS at the time of writing.
As for FreeBSD I am using 12.2-RELEASE.

Edit: Happens on specified Manjaro (21.0) as well.

**Comment by fundies** [comment]
you need grpc suff now. feel free to update that wiki
