### ISSUE TITLE
feel free to spy on my fork

### ISSUE THREAD

**Issue by time-killer-games** [enigma-dev/enigma-dev#2263]
my fork has a lot of stuff you guys don't have; feel free to take a look every once in a while and see if there is anything you'd like to copy/paste from my fork into enigma, although I'm not going to do it for you / make any pull requests.

https://github.com/time-killer-games/stigma-dev

i beat you to webm video playback support, Raspberry Pi OS compatibility (your enigma has std::filesystem related build errors on this platform), and many other things, even installers.

I used debreate to create an installer, you can just modify the installer project in debreate from here (the *.dbp project):

https://github.com/time-killer-games/stigma-dev/releases/tag/v1.0.0.0

...to quickly create an enigma installer for ubuntu and debian. I used debtap AUR to create the arch linux package, but note the freetype and jdk deps won't be recognized due to a bug with debtap, and you'll need to edit the package deps, which it will prompt you to do so

Debreate
https://antumdeluge.github.io/debreate-web/

Debtap:
https://aur.archlinux.org/packages/debtap/

**Comment by hpgDesigns** [comment]
i tested this and i did like the extensions and how slimline it is.
Most of the games i tested worked well, so so complaints there........for now
i also liked the installer which placed a shortcut in the menu

![image](https://user-images.githubusercontent.com/75296992/130447629-8b310959-55a6-47ba-a38a-567a6f61ecab.png)

**Comment by fundies** [comment]
If you want to send something send a PR. We have other things to do than keeps tabs on you.

**Comment by time-killer-games** [comment]
@fundies i literally handed you a two-minute way of creating an enigma installer, I'm sorry you're ungrateful and would rather do it from scratch because you don't like help from people who are far more capable.
