### ISSUE TITLE
Easily Create Debian Package with Debreate amd Arch with Debtap

### ISSUE THREAD

**Issue by time-killer-games** [enigma-dev/enigma-dev#2265]
I used debreate to create an installer, you can just modify the installer project in debreate from here (the *.dbp project):

https://github.com/time-killer-games/stigma-dev/releases/tag/v1.0.0.0

...to quickly create an enigma installer for ubuntu and debian. I used debtap AUR to create the arch linux package, but note the freetype and jdk deps won't be recognized due to a bug with debtap, and you'll need to edit the package deps, which it will prompt you to do so. Also arch linux has no direct equivalent for build-essential. I looked at the underlying packages build-essential includes and that can safely be omitted, as well as jdk since jre already allows you to run lgm and you don't actually need the full jdk.

Debreate
https://antumdeluge.github.io/debreate-web/

Debtap:
https://aur.archlinux.org/packages/debtap/

@fundies I can't make a pr for a binary file. Sorry dude. :/ It belongs under releases, but you know that lel

**Comment by time-killer-games** [comment]
@JoshDreamland , tell fundies to not close good issues, or ban him. he is misusing authority you gave him, yet again...

**Comment by time-killer-games** [comment]
@JoshDreamland i can create the installer for you if that's what you'd prefer, but it can't be done in a pr becuase its a binary file and belongs under releases. I though you guys would prefer to modifiy to a way you'd prefer it to be with direct access to the debreate project file, which gives you more say in how it will end up being, instead of just sending you a premade binary.

**Comment by time-killer-games** [comment]
@JoshDreamland , tell fundies to not close good issues, or ban him. he is misusing authority you gave him, yet again...

I was literally trying to cause peace where there was a huge need for there to be. Even hugar liked my issue I posted.

**Comment by JoshDreamland** [comment]
We've never had a problem generating an installer. The problem is, we need to keep doing that when we want to cut a release. Right now, fundies is trying to set up automation so that the CI prepares the installer with each new commit, like we do for RadialGM. Back in the day, he used to build an installer every few months, until he got completely sick of it. No one enjoys doing that. If you continue to do so, though, I'm sure users will find that helpful, and I'm happy to mirror it somewhere.

**Comment by time-killer-games** [comment]
Debtap is a command line interface, and Debreate can generate a debian package folder tree so that all of this can be automated from that. The cool thing is you can call git clone from the debian / arch packages and have it install the latest version every time.

**Comment by time-killer-games** [comment]
@JoshDreamland you can also have it clone based on a release commit, that way when stuff breaks in master, there's something to fall back on. I'm just saying there is a number of ways to go about it.

**Comment by fundies** [comment]
This is the whole point of a PR you send it to be critiqued and tested by others. However, you seem to take every critique as an attack for some reason. If you want us to see it send a PR. If you want it merged listen to our critiques. That's just how the process works. None of us here including Josh & I unilaterally merge things without approval from someone else. I didn't close your issue as an attack on you but you are using the issue tracker as a forum / blog and that's not the purpose of it. Your initial post here is fine as a feature but everything below it has no place on the tracker. I'm guilty of similar behavior to yours in the past and it was treated in the same manor. Simply, stop doing it or I will continue to close the issues an eventually you will end up banned from here too.

**Comment by time-killer-games** [comment]
> This is the whole point of a PR you send it to be critiqued and tested by others. However, you seem to take every critique as an attack for some reason. If you want us to see it, send a PR. If you want it merged, listen to our critiques. That's just how the process works. None of us here including Josh & I unilaterally merge things without approval from someone else. I didn't close your issue as an attack on you but you are using the issue tracker as a forum / blog and that's not the purpose of it. Your initial post here is fine as a feature request but everything below it has no place on the tracker. I'm guilty of similar behavior to yours in the past and it was treated in the same manor. Simply, stop doing it or I will continue to close the issues an eventually you will end up banned from here too.

I was going to generate a debian tree with debreate, before i can submit that tree as a pr, i will need josh to critique my debreate project, i mean i guess i could submit the debian tree as-is and ask how it should be different, but the whole point of debreate is to make the process quicker easier / it probably isn't that difficult anyways so i'll just go ahead and do that and we'll go from there.

**Comment by time-killer-games** [comment]
I will say this, no idea why you guys haven't murdered me yet for my behavior.
