### ISSUE TITLE
Compiler / Plugin error (i guess?) Everything Crashes LGM on Build

### ISSUE THREAD

**Issue by time-killer-games** [enigma-dev/enigma-dev#2271]
- Install deps (already had them before recording)
- git clone https://github.com/enigma-dev/enigma-dev
- cd enigma-dev
- make (will report different ticket for emake so no need to make that)
- ./install.sh
- java -jar lateralgm.jar
- create 1 room, with 1 object in it, maybe add code in it, though probably doesn't make a difference.
- watch lgm crash in response to you trying to build anything
- hugar _probably_ accused himself for being the problem, not you guys, just like I often do, because to quote what fundies has told us many times in the past "enigma-dev isn't broken and you are doing it wrong"--this refusing to take _our_ criticism. Sometimes, we are the problem and didn't do something right, but you can't just assume that though because you don't feel like accepting something is broken and you don't feel like testing or fixing it.

reproducible:
https://www.youtube.com/watch?v=DO17FjoYsFc

Moral of the story - ci doesn't replace real tests from real human beings. Sorry guys. 

Don't take this critique as yet _another_ attack, please. 

Because this is _exactly_ how you guys treated me on discord and github for _years_.

**Comment by time-killer-games** [comment]
@JoshDreamland don't let fundies close this one too, thanks.

**Comment by JoshDreamland** [comment]
This should be fixed in 7d21bba3b87c0b655c46ef6cf1abf4d7ab30bca9.

A PR comment I left wasn't addressed (or the change addressing it was somehow elided from the merge).

**Comment by time-killer-games** [comment]
@JoshDreamland Thank you! I'll close this assuming it won't be long before that gets mudged in.
