### ISSUE TITLE
FFMPEG is bad.

### ISSUE THREAD

**Issue by time-killer-games** [enigma-dev/enigma-dev#2273]
Unless you plan to pay millions of $$$ for the h264 patent or otherwise get in a world of legal troubles, don't use ffmpeg as a dependency. I overheard you had this in your plans, if you do this I'll be sure to get the word out as much as possible no one can legally sell, closed source, or distribute an enigma game without the aforementioned restrictions of h264 as well as gpl concerns, no one will use enigma and will hop over to my fork to use that instead.

https://www.mpegla.com/programs/avc-h-264/

If you don't take this warning lightly, you are literally asking for the death of enigma and a legal battle with a lot of people you'll end up losing. I warned you guys about this, and told you why libwebm is the way to go, but you are so arrogant you find there is no credibility to these facts as I present them to you, because you think everything i say is not true on the bogus reasoning I am too dumb in your view to be right about anything.

I can also report you guys to the patent owners if you don't take this seriously. :-)

**Comment by faissaloo** [comment]
intellectual property isn't real lmao

**Comment by time-killer-games** [comment]
I'd like you guys keep in mind, I'm trying to save you of trouble and a lot of it. The threat I made I only did with the intent to expand upon how serious you should take this, because whether I do anything or not, it will bite you in the butt eventually either way. I'm on your side, as much as you'd like to believe otherwise. It gets tiresome every attempt I go through to waste my time wanting to help, ends up being ignored, only for your downfall. I would like to educate you on all the ways you are violating international laws by pursuing this dependency, but I will need a more clear understanding of every last way you intend to misuse the library, which I cannot have access to that info with you banning me from your discord.

Do your research, contact the patent owners and ffmpeg devs with all of your questions. none of you live in the UK except polyz and hitcoder, as long as that remains true you have zero rights to distribute anything that links to this library, whether dynamically or statically, free-of-charge. I don't know all of the details concerning what is and isn't permissible, some of this can be taken with a grain off salt. All I'm asking is you educate yourself on what all the issues are before just using it blissfully.

**Comment by time-killer-games** [comment]
@fundies ok, i'm joining the server in an alt account with a fake ip and will gladly collect infomation that will bring you guys hell on earth for being so obvlvious. @JoshDreamland you clearly don't care about staying within the law. I hope you lose your job over this.

**Comment by time-killer-games** [comment]
@fundies have any explanation to give before I get you all banned?

**Comment by time-killer-games** [comment]
My report:

> They were looking to add ffmpeg to the software enigma-dev for video playback including the h264 patent and were looking to distribute binaries without owning the legally paid rights to do so. I was nice at first, on Discord, I informed them what they were considering to do wasn't legal. They didn't believe me, making arrogant claims that I have no idea what I'm talking about because they think I'm far too stupid to ever be right about anything, and that's the abuse I always get from them. I overheard from a screenshot someone sent me who is on their discord after they banned me from it, they didn't listen to my warning and are still going to implement this into https://github.com/enigma-dev/enigma-dev I warned them again, telling them I would notify the patent owners, ffmpeg developers, and github staff. They ignored and closed my issued ticket on enigma-dev.
> 
> Please keep a close eye on them if they happen to ever distribute binaries of ffmpeg of anything built using h264 and related patented material. I don't have the emotional energy to spy on or keep up with them anymore seeing as I've cut off ties with these verbally abusive and socially manipulative developers. I tried to warn them and they just don't give a crap, all I ever do is try to help them and they never appreciate it.
> 
> Thanks, 
> Samuel

**Comment by JoshDreamland** [comment]
Please quit harassing my team, or you will be banned.

**Comment by time-killer-games** [comment]
If all you want to believe is I am one who is trying to harass, then by your own choice I am no help to you.

**Comment by JoshDreamland** [comment]
For your own sake, I suggest you stop issuing threats on a public forum (or anywhere else).
