### ISSUE TITLE
New version of grpc breaks enigma

### ISSUE THREAD

**Issue by hpgDesigns** [enigma-dev/enigma-dev#2277]
### LateralGM / RadialGM Bugs
If your bug relates specifically to the IDE please file it on the appropriate tracker.

### Describe the bug
updated version of grpc-1.41.0-1 breaks Enigma at startup

![Screenshot_2021-10-02_08-16-34](https://user-images.githubusercontent.com/75296992/135718616-0b2a4974-9410-4a07-a382-f0cf7b748a2c.png)

### ENIGMA Configuration:
* I'm using EndeavourOS  _86x64 version........a Linux fork of Arch Linux

**Comment by JoshDreamland** [comment]
We don't prepackage C++ binaries, Hugar; can you delete libcompileEGMf.so and run make?

**Comment by hpgDesigns** [comment]
Rebuilding the compiler will fix this.

Many thanks to gfundies for providing the solution
