### ISSUE TITLE
resource_idmax is signed

### ISSUE THREAD

**Issue by JoshDreamland** [enigma-dev/enigma-dev#228]
The current compiler generates signed integers for resource ID caps. This is a reminder to me to make sure that's fixed in the new pretty-printer.

**Comment by RobertBColton** [comment]
@fundies was telling me this shows up in release mode on Linux.
http://paste2.org/BU5seZjI

He thinks he can fix it, is that true or do we need something more robust?

**Comment by JoshDreamland** [comment]
It's a simple fix.

**Comment by RobertBColton** [comment]
So basically just change sprite_idmax and object_idmax etc. to be unsigned? I can do that.

**Comment by RobertBColton** [comment]
@JoshDreamland Ok I started doing the fix and made them match the types. However, this presents new warnings:
```
Universal_System/roomsystem.cpp: In function 'int enigma_user::room_next(int)':
Universal_System/roomsystem.cpp:338:35: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if (num < 0 or num >= enigma::room_idmax)
                                   ^
```

This is because the ``room_next`` function takes a signed integer for the next room's id. Similar to what I mentioned about how ``d3d_model_draw`` can take -1 meaning no texture. However, ``d3d_model_draw`` is not much of a problem because we can have texture id be unsigned and the -1 would actually be INT_MAX when cast to unsigned. But what should we do for room_next? Change it to take an unsigned integer?

**Comment by JoshDreamland** [comment]
Rather than `num < 0 or num >= enigma::room_idmax`, use `(size_t) num >= enigma::room_idmax`.

As for the chars, it doesn't matter; go ahead and use unsigned.

**Comment by RobertBColton** [comment]
Yeah but why not just make room_next take unsigned instead of int? I mean, if you are going to allow the id's to go that high... all the resource functions should use unsigned for id's. Right?

**Comment by JoshDreamland** [comment]
Yes, that would be good. For the foreseeable future, `size_t` sounds like the best resource ID type we could ask for.

**Comment by RobertBColton** [comment]
So for ``d3d_model_draw`` exception would it be ok to do like this?

```cpp
if (texid == (size_t)-1)
  // no texture
```

Also this is going to be a significant undertaking to switch over all the systems to use unsigned for resource id's. I am postponing this for a bit so we can focus on other tasks. But please do test #1007 if you can since it is a 1 line fix and I just don't want to break Linux.

**Comment by fundies** [comment]
why arent you using ugly c++ sytle casts? Also @RobertBColton casting a signed number to unsigned is silly.... if (texid == (size_t)-1) would compile to if (texid == 1)

**Comment by fundies** [comment]
Why can't we use pointers for resources in enigma? I know gm uses int but copying that seems silly.

**Comment by RobertBColton** [comment]
No it wouldn't fundies it would compile to ``if (texid == UNSIGNED_INT_MAX)`` please come back when you learn binary and the two's complement kthx

**Comment by JoshDreamland** [comment]
Go ahead and set a constant to `size_t(-1)`, like `<string>`does with `npos`. Alternatively, we might consider just using `(texid > texture_list.size())`. It's one size lookup more expensive, and makes error cases less disastrous.

**Comment by RobertBColton** [comment]
@JoshDreamland I don't think the original issue here still exists? I see you started changing these 10 years ago to unsigned, in 3a325382b01088c5e518016ff6c5deda9497ed33, before you even filed this issue. Today all of the `*_idmax` variables in `Preprocessor_Environment_Editable` are in fact `size_t` as you were wanting.

The only other thing I found poking around in there was `enigma::objectcount` in `IDE_EDIT_objectdeclarations.h` which is signed.
https://github.com/enigma-dev/enigma-dev/blob/998cdb9853a5f0c41145b9b8191a0867510b6af0/CompilerSource/compiler/components/write_object_data.cpp#L660
I also found some goofball stuff like some id thing shaders were using was signed.
https://github.com/enigma-dev/enigma-dev/blob/998cdb9853a5f0c41145b9b8191a0867510b6af0/CompilerSource/compiler/components/write_shader_data.cpp#L64
There's also `room_loadtimecount` is signed.
https://github.com/enigma-dev/enigma-dev/blob/998cdb9853a5f0c41145b9b8191a0867510b6af0/CompilerSource/compiler/components/write_room_data.cpp#L68

Anyway if the issue has been resolved we should probably close this.

**Comment by JoshDreamland** [comment]
This is stale, anyway, given the migration to your resource storage class.
