### ISSUE TITLE
emake doesn't show error finding input file

### ISSUE THREAD

**Issue by HitCoder9768** [enigma-dev/enigma-dev#2296]
### Describe the bug
when running emake in the command line to build a game that it can't find, it doesn't output an error unless environment variable ENIGMA_DEBUG=TRUE is parsed. The default output is as follows:
```
[hitcoder@hitcoder-endeavour Documents]$ emake enigma-tetris.gmk -o ./tetris
LibEGM parsing log at: /tmp/enigma_libegm.log
ENIGMA compiler log at: /tmp/enigma_compiler.log
Linking up to IDE
Implementing JDI basics
UnimplementedUnimplemented

Choosing language: C++
 > Normal
 > Stacked
 > Specialized
 > TriggerOnce
 > TriggerAll
 > Inline
Creating parse context
 > Normal
 > Stacked
 > Specialized
 > TriggerOnce
 > TriggerAll
 > Inline
```

when running with the aforementioned env-var the end of the output prints the following

```
File: enigma-tetris.gmk does not exists
```

This should most likely be an important piece of output that should not be filtered.

### Steps To Reproduce
run emake and supply it a path to a nonexistent game file

### Expected behavior
the compiler should state that it could not find the specified file or that it does not exist (as shown above)

### Game files & Screenshots
The game used in the example was the Tetris example uploaded by hugar/hpg678
https://enigma-dev.org/edc/games.php?game=112

### ENIGMA Configuration:
* Endeavour OS (Arch Linux) LINUX510 Kernel

**Comment by abu1861** [comment]
kindly assign this issue to me.

**Comment by fundies** [comment]
> kindly assign this issue to me.

No one is actively working on it. Feel free to make a pull request.

**Comment by Adityasaini10012001** [comment]
@fundies  assign this to me

**Comment by fundies** [comment]
> @fundies assign this to me

We do not assign bugs. If you wish to fix it just send a pull request. And if you need help message me on discord.

**Comment by Adityasaini10012001** [comment]
ok @fundies

**Comment by parteekcoder** [comment]
@Adityasaini10012001 are working on this issue?

**Comment by Rohan-Dah** [comment]
Hiii... I would like to work on this issue as well. I guess the comments here are stale and currently no one's working on it. If anyone is working on this already I'll be happy to help..

**Comment by FutureRising007** [comment]
@fundies if this issue is still unsolved, I would like to make a pull request and would like to solve the issue. Thank You.
