### ISSUE TITLE
Transparency Pixel, Interpolation, & Texture Bleed

### ISSUE THREAD

**Issue by RobertBColton** [enigma-dev/enigma-dev#353]
http://enigma-dev.org/edc/games.php?game=43

Run the fps tutorial game, look in the middle of the screen. You see that greenish looking thing? Ya, wtf? Anyway, press space to shoot and it will animate, move around and it will follow you.

Polygonz encountered the issue as well.

**Comment by RobertBColton** [comment]
So what was really happening was that the gun sprite and other sprites use the "Transparency Pixel" setting in the sprite editor. This works all fine and dandy and the green background is removed.

However when you use interpolation on these textures then the edges are interpolated with the background.

![Transparency Pixel](https://cloud.githubusercontent.com/assets/3212801/17588990/266050aa-5fa0-11e6-94bb-46a0f7b1eb5e.png)

**Comment by RobertBColton** [comment]
@fundies Still exists with the gun sprite, I haven't actually figured out the cause yet.

**Comment by RobertBColton** [comment]
![image](https://user-images.githubusercontent.com/3212801/48832253-baaa0b80-ed46-11e8-99a4-ef7bd5f6e117.png)

**Comment by RobertBColton** [comment]
Alright, I found out why GameMaker 8 doesn't have it. Since it removes the transparency option, it has to convert older GMKs and remove the transparency on import. This means if we analyze the image we can see the effects of its transparency algorithm.

We can see in the following image that a 50% transparent border is formed around the opaque part of the sprite. We can also see with the dropper tool, that the pixels outside of this, that are fully transparent now, still have the green color.
![GM8 Transparent FPS Gun Sprite Image Editor](https://user-images.githubusercontent.com/3212801/48833896-60ab4500-ed4a-11e8-8b88-bf2566420530.png)

**Comment by JoshDreamland** [comment]
This is what I told you we could do to stop half-assing the transparency pixel. We would essentially be performing KNN on the transparent pixels to determine their final color. I don't know why the outsides of that barrel are antialiased in Yoyo's version. I suspect they redid them, or else are fudging the antialiasing.

**Comment by RobertBColton** [comment]
Just pointing out it seems somebody dropped the ball on this feature in GMSv1.4.999 where it seems to have regressed into ENIGMA's behavior. It does no alpha interpolating of the neighbors for editor sprites or dynamically added backgrounds.
![image](https://user-images.githubusercontent.com/3212801/141238600-604cbcbf-3b84-482d-bcf6-8fb189e8b122.png)

**Comment by RobertBColton** [comment]
Closing because this is now fixed by #2281 in the engine. If you have an issue with some external editor, file an issue on the relevant tracker. ENIGMA's behavior itself is now exactly the same as GM8.1 and there is nothing left to be done in the engine.
