### ISSUE TITLE
Path extension not able to be disabled

### ISSUE THREAD

**Issue by polygoned** [enigma-dev/enigma-dev#456]
Need cxxflag stuff to work

**Comment by fundies** [comment]
closed as fixed

**Comment by RobertBColton** [comment]
Confirmed as not fixed:
```
C:/Users/Owner/AppData/Local/ENIGMA/.eobjs/Windows/Windows/gcc/Run/Universal_System/planar_object.o:planar_object.cpp:(.text+0x26d): undefined reference to `enigma_user::path_update()'
```

**Comment by RobertBColton** [comment]
Ok going to close, after deleting `.eobjs` and rebuilding with and without and various combinations of the paths and Motion Planning extensions I am not able to recreate that error message now. Strange?
