### ISSUE TITLE
Update loop and paused timing

### ISSUE THREAD

**Issue by RobertBColton** [enigma-dev/enigma-dev#473]
Show a message with show_message() let it set there for a few minutes then click ok and the animations will play super fast for a bit. I believe this is caused by the update loop not realizing how long the game was paused for, like Stupido we need to handle game pauses.

**Comment by fundies** [comment]
can you verify this still happens and if so upload a test case?

**Comment by RobertBColton** [comment]
Alright, I made a GMK that reproduces it. In the test, you'll see 4 numbers in the top left. They are from top to bottom the room speed, current delta time, average delta time, and max delta time. The most important to watch is the bottom one, the max delta time. If you start dragging the window and hold it for a bit, about 10 seconds or longer, then let go, you'll see the delta time averages go way up and the max delta time will be increased.

That obviously means we are not subtracting the time that the window was paused from the delta time. So the first frame where the game is unpaused has an unusually high delta time. However, that does not necessarily correlate with why the animations in the room will also play fast (idk if we use delta time to calculate animation speed). And the delta time may or may not behave the same way in GMS, however I included it to demonstrate what's going on, since it may need fixed as well.

Download: [paused-timing-gmk.zip](https://github.com/enigma-dev/enigma-dev/files/4625635/paused-timing-gmk.zip)

**Comment by RobertBColton** [comment]
It's not reproducible for me in GameMaker 8.1 (fyi it had no delta_time, so you have to delete obj_1 to run it). And that's independent of freeze on lose focus setting as well.

**Comment by fundies** [comment]
ok thanks, I'm just trying to audit some of these bugs so we have real tests to try instead of dead links n etc

**Comment by RobertBColton** [comment]
This one is a real particular oddball though because the current index has nothing to do with any of the timing stuff. If you look in events.res it's just using the image_speed, there's no explanation for the animations just taking off real fast... unless Windows is speeding up the process or something crazy.
https://github.com/enigma-dev/enigma-dev/blob/f93a3851fd987d96a7c8d3d381da95528854b29e/events.res#L90

**Comment by RobertBColton** [comment]
Ok, I think I understand what's going on now. The timing variables getting out of whack, causes a deficiency in the fps counter, so the main loop is trying to play "catch up" and running several frames in succession.

**Comment by fundies** [comment]
the fps should drop during a pause thats normal but issue is likely somehere here:

https://github.com/enigma-dev/enigma-dev/blob/master/ENIGMAsystem/SHELL/Platforms/Win32/WINDOWSmain.cpp#L264

**Comment by RobertBColton** [comment]
I thought that crap was deduplicated lol, sigh, what a pita.

**Comment by fundies** [comment]
I asked you and josh to rewrite a standard one using std::chrono only but you were against it I think
