### ISSUE TITLE
Argument ordering

### ISSUE THREAD

**Issue by JoshDreamland** [enigma-dev/enigma-dev#489]
ISO C++ does *not* guarantee the order of argument execution in code. It is implementation defined and is generally not what you want.

This is a snippet of code from Robert's Project Mario:
```GML
guy = instance_create(file_text_read_real(file), file_text_read_real(file), obj);
```

GM's manual does *not* define the behavior of this, to my knowledge, either. The behavior in GM8.1 is "correct" in that it meets the user's expectation: arguments are evaluated left to right. In C++ and, by extension, in ENIGMA, the parameters are evaluated in the opposite order, and so (x, y, object) is passed (second qword (y), first qword (x), obj).

ENIGMA should either (1) Define the behavior of this code (thereby creating an optimization nightmare) or (2) report a warning on these calls when made inside function parameters.

JDI does not give ENIGMA the level of reflection required to determine that the order of calls to, eg, `file_text_read` or `random` matter while the order of calls to `sqrt` and `instance_nearest` do not. If possible, a flag should be created for this in the compiler or a list mechanism should be created for it.

**Comment by RobertBColton** [comment]
@JoshDreamland I created the following test to reproduce this without the file system involved.
In room create code:
```gml
test = ds_stack_create();
ds_stack_push(test, 0, 1, 2);
scr_0(ds_stack_pop(test), ds_stack_pop(test), ds_stack_pop(test));
```
In scr_0:
```gml
show_message(argument0);
show_message(argument1);
show_message(argument2);
```
GMS always displays them in the order 0,1,2 no matter how many times I run it.

**Comment by JoshDreamland** [comment]
ISO specifically doesn't mandate parameter evaluation order. And yeah, I don't think ENIGMA should, either. It would be nice if we had the metadata in place to warn that functions with side effects may not behave as users intend, in function parameters. Perhaps when we have actual compiler integration, we can use an annotation to denote that a function is stateful.
