### ISSUE TITLE
Texture Atlasing

### ISSUE THREAD

**Issue by RobertBColton** [enigma-dev/enigma-dev#653]
ENIGMA needs texture atlasing options, I can add them to LateralGM but ENIGMA needs to implement the texture atlases to better make optimal use of graphics cards. This will also fix several power of two issues with textures such as #652  and #487 by simply forcing the texture atlases to be a power of two. We also need megatextures for some Unicode fonts.

**Comment by RobertBColton** [comment]
I want to share here a test I ran in GM8.1. I had the bright idea that it's possible for sprites and backgrounds to be COW in GM and the users would never notice the difference. I discovered that this was not the case with GM8.1, but we might still be able to get away with doing it when we add texture paging.

```cpp
sprite1 = sprite_duplicate(sprite0);
spr0tex = sprite_get_texture(sprite0,0);
spr1tex = sprite_get_texture(sprite1,0);
// 1 and 2 in GM8.1
show_message(string(spr0tex) + " " + string(spr1tex));

background1 = background_duplicate(background0);
bkg0tex = background_get_texture(background0);
bkg1tex = background_get_texture(background1);
// 0 and 3 in GM8.1
show_message(string(bkg0tex) + " " + string(bkg1tex));
```

**Comment by fundies** [comment]
There is texture atlas code in enigma already its just not being used

**Comment by RobertBColton** [comment]
Right, TheExDeus wrote it sometime after I posted this ticket. We've known it was needed for quite some time.

**Comment by fundies** [comment]
its used for font packing too or atleast very similar code

**Comment by RobertBColton** [comment]
To clarify what I meant though, it's sort of unrelated to texture atlasing. I'm trying to say that the sprite texture is immutable even after being duplicated, except with certain functions (e.g, sprite_replace_alpha). When we duplicate a sprite, we could just create a COW reference so it uses the same texture as the original sprite, until you call one of these special functions, at which point we do an actual hard copy of the texture before it's mutated.

**Comment by RobertBColton** [comment]
Also fundies, moo.
