### ISSUE TITLE
Debug Printing

### ISSUE THREAD

**Issue by RobertBColton** [enigma-dev/enigma-dev#701]
Ok so basically, we need to work out our own printing system and stop printing shit in regular run mode. Why? Because Linux games won't work by double clicking them, you have to make sure you open them from a terminal or they will segfault because they are outputting to no console, Windows does not have this issue. Anyway, we need to wrap any print calls in our own functions so we can easily filter out the printing in compile mode or run mode or however we want to do it. This was discovered by Josh.

**Comment by fundies** [comment]
This makes no sense. Being able to "double click" has nothing to do with writing to the console.

**Comment by RobertBColton** [comment]
I can't believe I was that silly, it was probably an Ubuntu bug, the display server/window manager, or somehow related to running in VirtualBox. I remember specifically when I encountered this I was testing with VirtualBox. Polygonz debug ticket #566 is good enough to cover all of the debug improvements we'd like to make. All we need to do is make sure to use cerr for debug printing and cout for the regular show_message and dialog functions in the None widget system, that is the only distinction to be made for now. Agree on closing this.

**Comment by RobertBColton** [comment]
> Being able to "double click" has nothing to do with writing to the console.

You are absolutely wrong about this though, plus you have what I said backwards, how the application is launched certainly has an effect on whether or not it can write to the console.

https://stackoverflow.com/questions/25421216/xcode-5-console-application-segfaults-only-when-launched-via-finder

**Comment by RobertBColton** [comment]
This was ultimately resolved by #1440.
