### ISSUE TITLE
Date and Time Formatted Wrong

### ISSUE THREAD

**Issue by RobertBColton** [enigma-dev/enigma-dev#711]
In GM8.1 and Studio is by default formatted to the users locale which is a very easy fix. We should also probably add a date_format_string() function or similar so that the user can format the string themselves. Our current version also lacks the AM/PM after time.
http://www.cplusplus.com/reference/ctime/strftime/

This was discovered in the discussion on https://github.com/RobertBColton/enigma-dev/commit/8b4bea0283c3674b7da3bdf375c79e2431e9546b#commitcomment-6166602

This is how Studio formats the time string.
http://bugs.yoyogames.com/print_bug_page.php?bug_id=9532

**Comment by fundies** [comment]
Go document this on the wiki instead of here.

**Comment by RobertBColton** [comment]
There are a bunch of issues here still.

Further, YoYoGames added the following two functions:
1. date_set_timezone
2. date_get_timezone

I use this to test the formatting:
```gml
show_message(date_date_string(date_current_datetime()));
show_message(date_time_string(date_current_datetime()));
show_message(date_datetime_string(date_current_datetime()));
```
