### ISSUE TITLE
GL Projection functions lighting-aware

### ISSUE THREAD

**Issue by JoshDreamland** [enigma-dev/enigma-dev#723]
For some reason, GL's projection functions update the lighting. I'm sure there's something that breaks if this doesn't happen, but there definitely shouldn't be happening. It's always a good idea to keep individual systems unaware of each other. This still applies when one system is intrinsically bound to another. What happens if someone writes a custom projection function? Now they need to be aware of a checklist to go through to make sure they haven't broken anything else. Not to mention, lighting is getting updated even when no lights are set and 3D isn't even on.

**Comment by JoshDreamland** [comment]
Just make sure you didn't introduce a regression when changing projection, Robert. Sounds as though Harri handled that case (at the cost I'm complaining about in this bug), but this seems justified in GL1. Just make a note of why this has to happen (namely, GL1 is being "helpful" and adapting all lighting inputs to eye coordinates automatically).

**Comment by RobertBColton** [comment]
I did not introduce a regression, I actually made it handle certain edge cases better, hence why the Cubes demo has correct lighting in GL1 now as of that pull request.

Also, I did make note of it:
https://github.com/enigma-dev/enigma-dev/blob/4e8ad7c3857794f490610c621ae64ae54b3456b0/ENIGMAsystem/SHELL/Graphics_Systems/OpenGL1/GLd3d.cpp#L328
