### ISSUE TITLE
Room Creation Scope and Locals

### ISSUE THREAD

**Issue by RobertBColton** [enigma-dev/enigma-dev#743]
Room creation is the only code that a GM game can run without an object/instance scope, this is tricky when you consider things like sprite_index or other object locals being accessed here. One solution is to create a dummy instance for the room creation scope, which is exactly what GameMaker does. This is why the id of the first instance in a room starts at 100001.

This issue was discovered by a user as a result of the notme parameter for instance activation/deactivation functions.
http://enigma-dev.org/forums/index.php?topic=1977.0

Another issue originally encountered in #782 is that locals can't be defined in room creation without specifying var/type. `i = 5;` in a blank game in the creation code of a room will throw the following:

```
C:/ProgramData/ENIGMA/Preprocessor_Environment_Editable/IDE_EDIT_roomcreates.h: In function 'variant roomcreate0()':
C:/ProgramData/ENIGMA/Preprocessor_Environment_Editable/IDE_EDIT_roomcreates.h:38:3: error: 'i' was not declared in this scope
   i = 5;
   ^
```

**Comment by JoshDreamland** [comment]
I thought I recall the global scope actually being an instance of `object_locals`. Is that not the case?

**Comment by RobertBColton** [comment]
Hugar recently encountered an issue with trying to set the built in locals in the room create code recently. I helped him to figure out that's not what he wanted to do, but just to mention it also results in this error.
