### ISSUE TITLE
Event Group Ordering

### ISSUE THREAD

**Issue by RobertBColton** [enigma-dev/enigma-dev#895]
This is the only remaining issue of the grouped event bases. When writing the grouped event codegen we do not order the events, we first write the childs then the parents. So this could theoretically create a situation where alarm events are for instance fired 3,0,1,2

3 would be the alarm the child has and 0,1,2 would be inherited from the parent

The following comment denotes the issue
https://github.com/enigma-dev/enigma-dev/blob/master/CompilerSource/compiler/components/write_object_data.cpp#L346

I also created the following test case in which the alarm events are fired in the order (2, 3, 0, 1) where as in GM8.1 and Studio they are fired in the order (0, 1, 2, 3)
https://www.dropbox.com/s/etep72hnq9752te/alarmorderingtest.gm81?dl=0

**Comment by RobertBColton** [comment]
I went back and decided to test this out and using the latest portable ZIP with that example, I am no longer able to reproduce this.

The order it fires in GM: Studio
```
from obj_0 : obj_0 : alarm0
from obj_1 : obj_0 : alarm0
obj_1 : alarm0
obj_2 : alarm0
from obj_3 : obj_0 : alarm0
from obj_0 : obj_0 : alarm0
```

**Comment by fundies** [comment]
note to check this against #1875
