### ISSUE TITLE
Variant Pointer Overloading

### ISSUE THREAD

**Issue by RobertBColton** [enigma-dev/enigma-dev#896]
We are missing pointer overloading for var which was added in Studio. The corresponding function is_ptr() is also currently not implemented.
- [x] var pointer overloading
- [x] is_ptr() function
- [x] is_undefined() function
- [ ] window_device() function to get the IDirect3D9 device

**Comment by RobertBColton** [comment]
Closing as resolved by #1082

**Comment by JoshDreamland** [comment]
Yes... we've opened this particular Pandora's Box. Watch for falling rocks.
