### ISSUE TITLE
Script Identifier Conflict/ISO C98

### ISSUE THREAD

**Issue by RobertBColton** [enigma-dev/enigma-dev#915]
Create an empty project, create 1 script called "CreateFont" and build it. If you try using a script named this you will be met with errors.

```
C:/ProgramData/ENIGMA/Preprocessor_Environment_Editable/IDE_EDIT_objectdeclarations.h:35:0: warning: "CreateFont" redefined [enabled by default]
 #define CreateFont(arguments...) _SCR_CreateFont(arguments)
 ^
In file included from c:\users\owner\desktop\enigma\mingw32\i686-w64-mingw32\include\windows.h:71:0,
                 from ./Platforms/Win32/WINDOWSmain.h:23,
                 from ./Platforms/Win32/include.h:1,
                 from C:/ProgramData/ENIGMA/API_Switchboard.h:31,
                 from SHELLmain.cpp:60:
c:\users\owner\desktop\enigma\mingw32\i686-w64-mingw32\include\wingdi.h:2669:0: note: this is the location of the previous definition
 #define CreateFont __MINGW_NAME_AW(CreateFont)
 ^
```

Additionally you can not have a script called CreateWindow or any other windows.h function. ISO C98 does not guarantee that *.h C headers will not pollute the global namespace.

**Comment by TheExDeus** [comment]
That is why ENIGMA should prefix all it's stuff and only keep original names for errors, because I doubt there is a better solution. Maybe only allowing the users to use enigma_user namespace functions and not global ones, but I don't don't like restrictions.

**Comment by RobertBColton** [comment]
@TheExDeus I'd just like to clarify to you Harri that it would not be that big of a deal because then you could control what pollutes the enigma_user namespace yourself with using statements.

**Comment by sorlok** [comment]
Well, there is the "keyword blacklist" that I added to get around similar issues in OSX. Right now, blacklisting CreateFont will replace all uses of "CreateFont" with "CreateFont_____". It doesn't re-write script names, but I could probably extend it to do that.

**Comment by RobertBColton** [comment]
@sorlok What were the other reasons for the black list? I mean specifically what identifiers conflicts did you encounter? I am just curious because of its relevance in finding possibly a larger solution to this problem.

I would also like to note that the keyword lists in the build menu are actually only from enigma_user namespace or rather they should be, it may not be that way but it should be. From what I see CreateFont does not show up in that list. This was changed by me somewhere in the compiler to fix the syntax highlighting on ENIGMA specific functions.

**Comment by sorlok** [comment]
Lots of random problems that are a result of us pulling in most of the C/C++ library before compiling (as well as keywords). Things like "time", "try", and "short". You run into these a lot more when you try compiling other people's code.

If we built an AST, we could eliminate these problems more thoroughly.

**Comment by RobertBColton** [comment]
@sorlok Ahhh I see, yeah I've known about "time" for a while. And an AST is essentially what the new JDI which is already in ENIGMA is, the new compiler could basically take care of this.

**Comment by sorlok** [comment]
True, but there's no reason not to keep the old compiler up-to-date as well. :)

**Comment by RobertBColton** [comment]
@sorlok Sure, if you have a solution I'm all ears, but don't expect me to figure out how to use the AST heh at least until I pass discrete math for compsci this semester.

**Comment by RobertBColton** [comment]
@sorlok @TheExDeus 
I found where I added the fix for enigma_user keywords to show up properly in LateralGM, https://github.com/enigma-dev/enigma-dev/blob/master/CompilerSource/frontend.cpp#L72

We basically have to do the same with keywords and users can optionally include other stuff into enigma_user, but the part of JDI that is needed to use this is a year behind and Josh wants to fix the lexer first. There is a hack however to set the parent of enigma_user to NULL after parse, but that's way to hacky for me taste.

**Comment by fundies** [comment]
enigma_user and enigma namespaces have been implemented globally. If you have an issue with a specifc conflict please create a new issue.
