### ISSUE TITLE
use of 'exit' in room creation code fails to compile

### ISSUE THREAD

**Issue by BPzeBanshee** [enigma-dev/enigma-dev#924]
Error Log: http://pastebin.com/PXJxTqQW
Example project: https://www.dropbox.com/s/92xadf6x51bbh76/Test4.gmk?dl=0

Attempting to use 'exit' in room creation code leads to a failure to compile under C++ level. I also tested with only 'exit' used as well as a 'then' statement, made no difference. Said project works in GM8.0 and Studio v1.4.1499.

Seems the parser's change of exit to "return 0;" causes an issue in the area where room creation code is handled in ENIGMA. I haven't tested for gml workarounds but I wonder if just sticking in 'return' would work.

**Comment by sorlok** [comment]
I can probably fix this; the multi-block fix actually makes this fix easier, since "exit" is no longer a macro (it's a special keyword). I'll have a look and get back to you --thanks for reporting this!

**Comment by RobertBColton** [comment]
@BPzeBanshee This was fixed in #926 and will be included in the next portable ZIP.
