### ISSUE TITLE
vspeed/hspeed behaviour issues

### ISSUE THREAD

**Issue by BPzeBanshee** [enigma-dev/enigma-dev#933]
Test builds:
https://www.dropbox.com/s/qbwr7zmrournjls/Test7.gmk?dl=0

Using vspeed or hspeed by themselves results in an offset direction value. Using vspeed=270 will give a direction value of 269 instead of Game Maker 8.0 and Studio and every other version of Game Maker I've ever been familiar with's 270. The behaviour here is apparent in Test7.gmk, and defining a direction after defining vspeed/hspeed does not appear to affect the weird behaviour at all. Using plain speed and defining a direction will work correctly.

I originally noticed this in my Warbird project and posted about it quite some time ago but hadn't isolated it from the other ENIGMA compatibility issues. obj_en1 appeared slightly distorted and would not fly down past the screen as intended, expecting an exact direction value of 270 when it was getting 269 due to it's use of vspeed.

**Comment by TheExDeus** [comment]
Seems like a precision issue (because of some type casting) or rounding issue. I will maybe check this out later.

**Comment by TheExDeus** [comment]
There is a rounding issue, where we just casted the result to int (269.9999 into 269.0000) instead of rounding. This is fixed in this commit: https://github.com/enigma-dev/enigma-dev/commit/0e358861fba53e7b6898df3696e94fc4fb2a3948

**Comment by TheExDeus** [comment]
This was fixed in January.
