### ISSUE TITLE
[Linux] Fullscreen doesn't work

### ISSUE THREAD

**Issue by fervi** [enigma-dev/enigma-dev#937]
Hi!

Some time ago, when I used Enigma - FullScreen working
But now i downloaded enigma and it doesn't work (screen in game is scaled, but the windows of game is still the same, and it is still window)
F4 key doesn't work
![2015-02-08-120747_2048x1152_scrot](https://cloud.githubusercontent.com/assets/2242925/6096327/66312be4-af8b-11e4-8f62-ad5961e27f91.png)
![2015-02-08-120811_2048x1152_scrot](https://cloud.githubusercontent.com/assets/2242925/6096328/66333b82-af8b-11e4-83a8-344788c53548.png)

**Comment by TheExDeus** [comment]
Works fine on Windows. I will try installing a dual-boot ubuntu at some point and test stuff there. Right now there isn't much I can do. Virtual machine has crappy GL support, so I cannot run ENIGMA in it.

**Comment by fervi** [comment]
Probably working now ok
