### ISSUE TITLE
execute_shell and execute_program 'undefined reference' on compile

### ISSUE THREAD

**Issue by faissaloo** [enigma-dev/enigma-dev#947]
Whenever I try to compile a program with execute_shell or execute_program in it it causes the error:

    SHELLmain.cpp:(.text+0x60bc): undefined reference to `enigma_user::execute_shell(std::string, std::string)'  

or  

    SHELLmain.cpp:(.text+0x60be): undefined reference to `enigma_user::execute_program(std::string, std::string, bool)'

**Comment by TheExDeus** [comment]
Can you share your OS, where you got ENIGMA and how you run it?
Because it does work for me on Windows. I am not sure if it was implemented in Linux or Mac.

**Comment by faissaloo** [comment]
@TheExDeus I'm running it on Linux, specifically Xubuntu 15.10. I got enigma from this repo and I run it by doing
    cd /home/faissaloo/Desktop/Applications/enigma-dev; java -Djna.nosys=true -jar lateralgm.jar

**Comment by TheExDeus** [comment]
Indeed, I see that in Linux they are not implemented. I will try adding them using System() function (http://www.cplusplus.com/reference/cstdlib/system/) as it seems to be the most "portable" way to do it. I will probably do that tomorrow and try giving it to you for testing as I don't have Linux.

**Comment by faissaloo** [comment]
Thanks alot man, I'd advise putting a warning in the compiler window about shell injection so that no one thinks to use it for anything with untrusted input.

**Comment by TheExDeus** [comment]
I have added them here: https://github.com/enigma-dev/enigma-dev/commit/fdb349dd06d73803585137c53ad0d0c4d02cdd16
Take this file: https://raw.githubusercontent.com/enigma-dev/enigma-dev/GL3.3NormalMatrix/ENIGMAsystem/SHELL/Platforms/xlib/XLIBmain.cpp
And put it in "\enigma-dev\ENIGMAsystem\SHELL\Platforms\xlib\" overwriting the existing one. I sadly cannot test it so it might even have basic syntax errors somewhere.

**Comment by faissaloo** [comment]
Works flawlessly, thanks

**Comment by TheExDeus** [comment]
No problem! I'll close this then.
