### ISSUE TITLE
I wrote a 1 click bash download/install script for enigma-dev

### ISSUE THREAD

**Issue by faissaloo** [enigma-dev/enigma-dev#949]
```
#!/bin/bash
cd ~
echo Installing dependencies
apt-get install g++ zlib1g-dev libglu1-mesa-dev libalure-dev libvorbisfile3 libvorbis-dev libdumb1-dev git default-jre wget
echo Downloading Enigma
git clone git://github.com/enigma-dev/enigma-dev.git
cd enigma-dev
echo Downloading easy startup script
wget http://pastebin.com/raw.php?i=znQ41zqY
mv raw.php?i=znQ41zqY start.sh
echo Correcting permissions
chmod 775 start.sh
chmod 775 install.py
echo Installing...
./install.py
cd CompilerSource
echo Rebuilding compiler
make clean
make
echo Done, to start Enigma just do ~/enigma-dev/start.sh
```
some of the stuff in there also prevents certain frequent issues, needs to be run with sudo. I didn't make a pull request because I thought it would be more appropriate to show you so you could decide where to put it since there wouldn't be much use in having it in the repo

**Comment by adambadawy** [comment]
I'm not a security expert, but this doesn't look very safe. Don't you need to check the success of most of these commands? For example, if the `git clone` fails, this script will likely make a mess in the cwd.

**Comment by faissaloo** [comment]
Yeah, it would be good to check the success of the commands, but I don't think it'll be that much of a big deal since the rest of the script will just fail anyways.

**Comment by adambadawy** [comment]
Will it? I thought it will just continue executing. Currently not on a system with bash so I can't check; sorry.

**Comment by faissaloo** [comment]
It's ok, it'll try to execute yes, but the stuff won't exist so they'll fail

**Comment by faissaloo** [comment]
Someone improved it:
```
#!/bin/bash
cd
echo "Installing dependencies..."
sudo apt-get install g++ zlib1g-dev libglu1-mesa-dev libalure-dev libvorbisfile3 libvorbis-dev libdumb1-dev git default-jre wget
echo "Downloading Enigma..."
git clone git://github.com/enigma-dev/enigma-dev.git
cd enigma-dev
echo "Downloading easy startup script..."
wget http://pastebin.com/raw.php?i=znQ41zqY -O start.sh
echo "Correcting permissions..."
chmod +x start.sh
chmod +x install.py
echo "Installing..."
./install.py
cd CompilerSource
echo "Rebuilding compiler..."
make clean
make
echo "Done, to start Enigma just run ~/enigma-dev/start.sh"
```

**Comment by RobertBColton** [comment]
@faissaloo I would say it'd be best to just copy and paste it onto the Wiki.

Does this apply to Windows bash or just Linux?

http://enigma-dev.org/docs/Wiki/Install:Linux

I would put it on the Wiki in a collapsible table, one that is collapsed by default.

**Comment by faissaloo** [comment]
@RobertBColton This is for debian based distros (since it uses apt-get) so I doubt it'll work in Cygwin or any other implementation of bash on Windows.

**Comment by adambadawy** [comment]
Debian itself does not have `sudo` installed by default.

**Comment by faissaloo** [comment]
@adambadawy Here's a version without sudo:
```
#!/bin/bash
cd
echo "Installing dependencies..."
apt-get install g++ zlib1g-dev libglu1-mesa-dev libalure-dev libvorbisfile3 libvorbis-dev libdumb1-dev git default-jre wget
echo "Downloading Enigma..."
git clone git://github.com/enigma-dev/enigma-dev.git
cd enigma-dev
echo "Downloading easy startup script..."
wget http://pastebin.com/raw.php?i=znQ41zqY -O start.sh
echo "Correcting permissions..."
chmod +x start.sh
chmod +x install.py
echo "Installing..."
./install.py
cd CompilerSource
echo "Rebuilding compiler..."
make clean
make
echo "Done, to start Enigma just run ~/enigma-dev/start.sh"
```

**Comment by faissaloo** [comment]
Added: http://enigma-dev.org/docs/Wiki/Install:Linux
