### ISSUE TITLE
Extra float argument for draw_button

### ISSUE THREAD

**Issue by faissaloo** [enigma-dev/enigma-dev#951]
Enigma's draw_button function is:
```
void enigma_user::draw_button(gs_scalar, gs_scalar, gs_scalar, gs_scalar, float, bool)
```
While Yoyogames' specification says:
```
draw_button(x1, y1, x2, y2, up);
```

So shouldn't it be:
```
void enigma_user::draw_button(gs_scalar, gs_scalar, gs_scalar, gs_scalar, bool)
```
unless there is some reason for the extra float argument that I'm not aware of, even then, the float argument should be optional for compatibility.

**Comment by TheExDeus** [comment]
We don't strive with GM compatibility. If you want to port your GM game to ENIGMA, then just use the additional argument. The reason why it is not at the end is for consistency, as we usually have bool's in the end (like draw_rectangle(x,y,w,z, bool outline)). I guess we could change it in this case and have it a default value, but not for compatibility reasons, as we already have a lot more incompatible functions in ENIGMA which will never be changed.
Maybe someone else has an opinion on this.

**Comment by JoshDreamland** [comment]
An overload that elides the float wouldn't bother me. Though if the boolean is optional in the longest overload, that would lead to ambiguity in, eg, the case where 0 is passed. If that's the case, we should keep it as-is.

**Comment by TheExDeus** [comment]
Bool is not optional in that function. So I will add an overload if someone can tell me what the border size is on GM's button.

**Comment by faissaloo** [comment]
It's 2 pixels wide, I measured it in GIMP.
![pic](http://docs.yoyogames.com/source/dadiospice/002_reference/drawing/drawing%20basic%20forms/draw_button.png)

**Comment by TheExDeus** [comment]
Did the change here: https://github.com/enigma-dev/enigma-dev/commit/d995a914cec1061948943f119cae7525c65b473c
