### ISSUE TITLE
ENIGMA: Unable to communicate with the library

### ISSUE THREAD

**Issue by basedheaven** [enigma-dev/enigma-dev#953]
![screenshot from 2016-01-01 18-39-39](https://cloud.githubusercontent.com/assets/16512488/12072634/0abfc404-b0b7-11e5-8f72-2bf753cf5af9.png)

Operating System: Linux
Version: 4.3.3-2-ARCH
Architecture: i386

Java Vendor: Oracle Corporation
Version: 1.8.0_66

Available processors (cores): 3
Free memory (bytes): 29740848
Maximum memory (bytes): 863240192
Total memory available to JVM (bytes): 73924608

File system root: /
Total space (bytes): 543793020928
Free space (bytes): 516096561152
Usable space (bytes): 510553788416

Stack trace:

java.lang.UnsatisfiedLinkError: Unable to load library 'compileEGMf': Native library (linux-x86/libcompileEGMf.so) not found in resource path ([file:/opt/enigma-dev-git/plugins/enigma.jar])
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:271)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:398)
	at com.sun.jna.Library$Handler.<init>(Library.java:147)
	at com.sun.jna.Native.loadLibrary(Native.java:412)
	at com.sun.jna.Native.loadLibrary(Native.java:391)
	at org.enigma.EnigmaRunner.attemptLib(EnigmaRunner.java:247)
	at org.enigma.EnigmaRunner.access$1(EnigmaRunner.java:240)
	at org.enigma.EnigmaRunner$3.run(EnigmaRunner.java:178)

Got this error on first boot. I'm still pretty new to linux.

**Comment by faissaloo** [comment]
Are you using Ubuntu?

**Comment by basedheaven** [comment]
Im using a fork of arch Linux called antergos

**Comment by faissaloo** [comment]
Open a terminal in the 'CompilerSource' folder in the Enigma folder and do:
```
make clean
make
```

**Comment by basedheaven** [comment]
Do you know where the Enigma folder would be located I've done some searches and couldn't find it.

**Comment by adambadawy** [comment]
Did you use the AUR package to install enigma?

**Comment by basedheaven** [comment]
Yes. I installed from AUR

**Comment by adambadawy** [comment]
Do you have an enigma directory in `/opt`? Like perhaps `/opt/enigma-dev-git`? Look around in there. It's also worth noting that the AUR package is probably broken, since you seem to be missing dependencies.

**Comment by basedheaven** [comment]
Found the folder I was looking for and did
make clean
make
Same error

**Comment by adambadawy** [comment]
Relevant:
* [AUR discussion](https://aur.archlinux.org/packages/enigma-dev-git/)
* [Another local issue](https://github.com/enigma-dev/enigma-dev/issues/944)

**Comment by adambadawy** [comment]
In fact, it might be a good idea to close this in favor of #944 if it looks the same to you, @basedheaven.

**Comment by basedheaven** [comment]
Thank you. Closed.
