### ISSUE TITLE
Feature: Add script name display in editor

### ISSUE THREAD

**Issue by Kayomn** [enigma-dev/enigma-dev#954]
So in Enigma's counterpart, Game Maker, you are able to see the name of your scripts within the object you're working on. Coming from past experience from Game Maker it seems really inconvenient for all of your scripts to be named the stock value.

Surely it couldn't be that hard to make the name of the entry in the list change to the first line of the file's "///...".

Thanks in advance.

**Comment by JoshDreamland** [comment]
That's sort of a weird hack, but it doesn't sound hard, no. Could you file this request on LGM's tracker at [IsmAvatar/LateralGM](/IsmAvatar/LateralGM)?

**Comment by Kayomn** [comment]
https://github.com/IsmAvatar/LateralGM/issues/233

Added.

**Comment by RobertBColton** [comment]
Thank you, this is one I was aware of that could be added for a while. I will be closing this here as it would be entirely LGM side if implemented. The thing about is though, I would prefer something more like doxygen, something that is dynamic, "///" could possibly work. More input from @JoshDreamland would be appreciated.
