### ISSUE TITLE
LGM Crashes When Action is Added

### ISSUE THREAD

**Issue by ryanisaacg** [enigma-dev/enigma-dev#962]
I installed enigma on my Ubuntu GNOME laptop using the instructions at [the enigma site](http://enigma-dev.org/docs/Wiki/Install:Linux). Everything seemed to be going well, until I tried to use it. I launched LGM with the command `java -Djna.nosys=true -jar lateralgm.jar`, and it opened fine. When I created an object, I tried to add an action to the creation event. The entire window froze and refused to respond to input, and wouldn't even close when I hit the close button. I had to close it by killing the process.

**Comment by TheExDeus** [comment]
LGM probably crashes. It is sadly very unstable. This is the LGM tracker: https://github.com/IsmAvatar/LateralGM/commits/master . You should probably post there.

**Comment by ryanisaacg** [comment]
Alright, I opened it at [that tracker](https://github.com/IsmAvatar/LateralGM/issues/258), so I'll close it here.
