### ISSUE TITLE
Unable to Update Enigma

### ISSUE THREAD

**Issue by Kayomn** [enigma-dev/enigma-dev#968]
Alright, so whenever Enigma-Dev is launched I get this error. I'm running Linux Mint right now with Open-JRE. Everything is basically vanilla as the system came, it was a fresh install to see what Enigma would actually run on.

Currently the only way I'm able to run it is by opening a terminal and suffixing the Java -jar launch command with a sudo the elevate the program to superuser privileges.

`Operating System: Linux`
`Version: 3.19.0-32-generic`
`Architecture: amd64`

`Java Name: OpenJDK 64-Bit Server VM`
`Java Vendor: Oracle Corporation`
`Version: 1.7.0_101`

`Available processors (cores): 4`
`Free memory (bytes): 125384912`
`Maximum memory (bytes): 1841823744`
`Total memory available to JVM (bytes): 157286400`

`File system root: /`
`Total space (bytes): 463762644992`
`Free space (bytes): 449539891200`
`Usable space (bytes): 425958465536`

`Stack trace:`
`org.lateralgm.file.GmFormatException: java.io.FileNotFoundException: Compilers/Linux/gcc.ey (No such file or directory)`
`	at java.io.FileInputStream.open(Native Method)`
`	at java.io.FileInputStream.<init>(FileInputStream.java:146)`
`	at java.util.Scanner.<init>(Scanner.java:680)`
`	at java.util.Scanner.<init>(Scanner.java:674)`
`	at org.enigma.file.YamlParser.parse(YamlParser.java:189)`
`	at org.enigma.EnigmaRunner.make(EnigmaRunner.java:277)`
`	at org.enigma.EnigmaRunner$3.run(EnigmaRunner.java:173)`

**Comment by RobertBColton** [comment]
Just to be clear, this only occurs when you launch without **superuser** privileges?

**Comment by Kayomn** [comment]
I installed Oracle's JDK and replaced OpenJDK, did all sorts of stuff. I eventually discovered the issue was linked to something shared with an old build of Antergos Linux and Mint Cinnamon, in that it was defaulting to using the wrong Python version when installing. Anyway, it's since been fixed in Mint 18. Closing this issue now, thank you for reminding me it was open.

**Comment by RobertBColton** [comment]
Ok that's a relief. As I understand it, you are saying that the wrong python version caused the install script to fail? That's great news and it may help us resolve #944.

Do you happen to have any other information about the python issues. For example a copy of the output after the installation script ran in the wrong python version? We might be able to patch the installation script so it would work anyway.

**Comment by Kayomn** [comment]
Although I don't have the output anymore, as I have updated to Mint 18 since, I can tell you exactly what I know to have been happening.

As near as I can tell, when running the Python execution command, Linux Mint 17 was defaulting to running either Python 2 or Python 3, whichever one is the incorrect version for the install script.

**Comment by RobertBColton** [comment]
Thank you so much. Perhaps it would also help if I list the minimum required version of python for that script to run on our Wiki but I don't know what that would be or how I could figure that out without trying each one :stuck_out_tongue:

Maybe I should just put "Use a newer version of Python for the installation script to run properly."

What do you think?

**Comment by Kayomn** [comment]
Well the issue was more so that that there are two versions of Python that exist right now. 3.X and 2.7.X. Both of these are supported branches of Python, but the difference is that version 3 had a massive overhaul and made it reworked a lot of how the interpreter parsed Python's syntaxes.

I think the best thing to do is to make sure users are executing it with the right version of Python, whichever that may be. It's fairly easy to find out but unfortunately the current computer I am using does not have a spare installer nor do I have the means right now to install it on this device.

**Comment by RobertBColton** [comment]
Thank you really that is immensely helpful.

**Comment by faissaloo** [comment]
This invalidates [this comment](https://github.com/enigma-dev/enigma-dev/blob/master/install.py#L2):  
># This python script runs in both Python 2.6 and Python 3+
