### ISSUE TITLE
High DPI Fonts

### ISSUE THREAD

**Issue by RobertBColton** [enigma-dev/enigma-dev#970]
I noticed some problems today on my high DPI 2k monitor (2560x1440 resolution). The default font is not effected by DPI at all. If you create a font and set it as the font it is effected by the DPI.

``` gml
// use the ENIGMA default font, won't be very big
draw_set_font(-1);
draw_text(0,0,"Hello, world!");
// use our custom font, will be really big because of DPI
draw_set_font(font_0);
draw_text(0,200,"Hello, world!");
```

GMS studio does not seem to have this problem because it all together ignores DPI in the engine just like the IDE ignores DPI and lets Windows just upscale it as a bitmap (which it does since Vista) because it's written in Delphi.NET. 

![High DPI Fonts](https://cloud.githubusercontent.com/assets/3212801/16106636/3a1a74b2-3364-11e6-9a06-82a163efc8ca.png)

I am not really sure what the solution to this would be or if it should be changed in ENIGMA at all. But I think that maybe there should be a plugin setting for it because when you export your game you want to have control over the DPI depending on the target platform. I am interested to know what @JoshDreamland and everybody thinks.
http://help.yoyogames.com/hc/en-us/articles/216757528-No-support-for-Windows-Zoom-DPI-scaling

**Comment by JoshDreamland** [comment]
ENIGMA is a game engine; fonts are rendered at the *resolution* you request. And this rasterization is done long beforehand by LGM. If you want a "high DPI" font, you should include a 24pt font in addition to your 12pt font, and render the correct one, accordingly. Essentially, this is all on the users as they implement their in-game UIs.

If any support for font DPI settings is to be added, it belongs in the UI code Harri wrote. It should take a list of fonts at each scale and use the smallest font whose size is greater than the desired draw area multiplied by some factor given by DPI / expectedDPI.

**Comment by RobertBColton** [comment]
Actaully, have we specified if ENIGMA exe's are DPI in their manifest? I wonder if we should? I think that's what the issue is here Josh. I am saying more so that a 12 pt font should always be a 12 pt font rendered by the IDE. Then your solution works but only if the point size always produces the same size font on every development machine.

**Comment by RobertBColton** [comment]
Closing this here because this is not an issue with ENIGMA. This is actually LGM's fault for not generating all the bitmaps at a consistent DPI, to make what you suggest work (which would be the way to do it in GM). It should also be done the way you say so that the font texture atlas can be saved to the GMX or EGM and taken to another platform where said font may not exist.

We do have `display_get_dpi_x` in Win32 which can be used in games and the engine:
https://github.com/enigma-dev/enigma-dev/blob/bc5dffefdfb2f754d35f636af16310118cb5fec4/ENIGMAsystem/SHELL/Platforms/Win32/WINDOWSwindow.cpp#L490

When we add the font packer to emake we can do the same thing, generate all the font bitmaps at the same DPI. To clarify, we don't plan on supporting dynamically resized fonts, users can hack that on or maybe later we'll add to the TTF extension fundies made if there is enough demand for it. But in general, as far as an IDE or front end goes, the font texture atlases should be generated at the same consistent DPI, and maybe have a preference to control that DPI per-project. We can look into this in RadialGM later.
