### ISSUE TITLE
Depth buffer format

### ISSUE THREAD

**Issue by RobertBColton** [enigma-dev/enigma-dev#971]
I recently noticed intense z-fighting on the GMS cubes demo. I switched from OGL 1.1 to Direct3D9 graphics system and realized it did not occur in the latter.

The reason was because I made the Direct3D9 graphics system use a 24bit zbuffer like GMS does:
https://github.com/enigma-dev/enigma-dev/blob/2010bcea914eb79e293f75ea2681cdd4a677ec8d/ENIGMAsystem/SHELL/Bridges/Win32-Direct3D9/graphics_bridge.cpp#L106

The OpenGL bridges continue to use a 16 bit zbuffer like legacy GM8.1 and lower:
https://github.com/enigma-dev/enigma-dev/blob/c7a9dfd438f7abe7e81bcfd2c27b6c8e8401b0e7/ENIGMAsystem/SHELL/Bridges/Win32-OpenGL1/graphics_bridge.cpp#L63

https://docs.yoyogames.com/source/dadiospice/002_reference/drawing/drawing%203d/3d%20setup/d3d_start.html

> First of all depth testing (also known as Z Buffering) is switched on (using a 24-bit z-buffer)

You can see the differences switching the zbuffer in the OpenGL bridges from 16 to 32bit:
![16 bit Depth Buffer](https://cloud.githubusercontent.com/assets/3212801/16108533/923063f2-3371-11e6-98c5-fb83ffbc4f02.png)
![32bit Depth Buffer](https://cloud.githubusercontent.com/assets/3212801/16108542/9fb2fee0-3371-11e6-982a-7152de64ed0a.png)

We could simply switch all the bridges over to use a 24 bit zbuffer like GMS does and this would also render legacy GM games at a higher quality. But perhaps we should also add a setting for it @JoshDreamland or does it not really matter? Maybe we should try to satisfy everybody and switch it to a 24 bit zbuffer when calling d3d_start like YoYoGames does?

**Comment by RobertBColton** [comment]
@JoshDreamland I'd like to talk to you some more about this issue considering #993. This is the next issue I want to work on and clean up the graphics bridges after #989.

There are 3 approaches that can be taken to address this, some of them in concert.
**Abstract the Depth Buffer Formats**
Since OpenGL uses a number like ``pfd.cDepthBits = 16;`` and Direct3D9 uses constants like ``D3DFMT_D24S8`` and ``DXGI_FORMAT_R8G8B8A8_UNORM`` we could invent our own constants for ENIGMA. This would also be useful for additional control over surface creation, which Harri wanted because he had a boolean parameter to surface_create so you can create surfaces without any depth buffer.
**Use a #define for the Depth Buffer Size**
This is simple, just like we did for ma_scalar, we can #define DEFAULT_DEPTH_BUFFER_SIZE fmt_32. This define would not just be used in bridges but also to set the default argument for the format parameters of surface_create that we add. So then you could do ``mysurf = surface_create(800, 600, fmt_32);`` or simply omit the format parameter.
**Add a Setting for the Depth Buffer Size**
Instead of defining the default we could add a setting to ENIGMA settings as well, which would still have a default value. We would like set the default to 24 bit since that is what GMS and most games use nowadays.
**Use the GameMaker Compatibility Setting for Depth Buffer Size**
Instead of adding a new setting we could also just use that compatibility setting from #993 and set the depth buffer to 16 bit for old GM versions and 24 bit for anything newer than GM 8.1.
**Use no Depth Buffer by Default and Create it on d3d_start**
This one is a little tricky, but I believe it is what GMS does. If you read the documentation that is apparently when the depth buffer is not only turned on, but also when it is created.
https://docs.yoyogames.com/source/dadiospice/002_reference/drawing/drawing%203d/3d%20setup/d3d_start.html
I am not sure how good of an idea it is to defer the depth buffer creation until d3d_start because users often mistakenly call d3d_end to go back to 2D drawing for the HUD. And since this requires a device reset in Direct3D9 that means we have to dump and reload all the textures when that happens, potentially killing the framerate. So I think this is the strongest argument that it should be a per project setting and we give users more control over the depth buffer format during surface creation as well. But then again, depth buffers are extremely cheap these days, so maybe we could just set all games to use a 24 bit depth buffer and forget about it.

I would like to know which if any of these solutions you like and how you want to go about this. I already know how to fix it, I just don't know what will end up being the best.

**Comment by JoshDreamland** [comment]
> Abstract the Depth Buffer Formats

Yes; good idea. We've done this for a number of constants. Unfortunately, `db` as a prefix usually means "Database" and not "Depth Buffer," so let's do something like `depth_buffer_24bit` and `stencil_buffer_8bit`, and fit these to the MS constants behind-the-scenes.

> Use a #define for the Depth Buffer Size

Well, okay; maybe in conjunction with your first item. I assume we want to pass this to surface creation functions, as well? Otherwise, it could as well be a global.

> Add a Setting for the Depth Buffer Size

Generally, this is configured through code; I don't think we have much of a space for nitty-gritty render target configurations. If you can amass a decent number of these, I'd be happy to support one. The only real switch I'd consider putting in graphics is a "This is a 3D game!" checkbox, so we can prepare for all the fancy metadata they need with their initial framebuffer (eg, depth and stencil channels).

Maybe if we had a few high-level graphics settings to display, we could put an "Advanced" button in to allow configuring this minutia, but otherwise, the solution is probably more parameters to `d3d_start`/`d3d_end`.

> Use the GameMaker Compatibility Setting for Depth Buffer Size

Not much point; I doubt games rely on a 16-bit depth buffer. I don't know how allocations differ on the hardware for 24 bit vs 16 bit; if there's a substantial performance difference, then I'm on board, but honestly, 24 bits is a reasonable default....

> Use no Depth Buffer by Default and Create it on d3d_start

This is definitely something we should be doing, but it might make d3d_start clunky. See my remarks on graphics settings.

**Comment by RobertBColton** [comment]
I just had another idea reading your post while I was getting started on this. I like the idea of passing it to d3d_start, but where my thinking was wrong before was that d3d_end would destroy the depth buffer. How about we go with a 24 bit zbuffer for now and lazy load it. I mean we wait until the first d3d_start to create it and then we just let it hang around assuming you'll use it again. Then we can just add a simple bool flag to d3d_start like Harri did to surface_create so you can override and force 3D mode on with no depth buffer (if you really really want). What do you think of that?

Btw I have another question for my own knowledge. How would you calculate the size that the depth buffer takes up in RAM? Would it be width * height * bits per pixel / bits per megabyte?

**Comment by JoshDreamland** [comment]
Yes; that is exactly what I would have recommended, though this is assuming changing depth buffer format is that easy in, eg, XGL. I'm not sure how big a pain it is to change that sort of thing (XGL forces you to request most of this information up front).

And yes, that is the equation you want.
