### ISSUE TITLE
Major visual bugs and lag

### ISSUE THREAD

**Issue by faissaloo** [enigma-dev/enigma-dev#979]
Game lags and I get these visual glitches:  
![bug](https://i.sli.mg/zmphDT.png)  
I had recently added some new sprites but didn't get any issues until the next day which I believe might have been because I recompiled everything. -After messing with it a bit to try to figure out what was wrong the game just gets stuck at a black screen now (or if I use debug mode, a blue screen, because it refuses to go to the next room)- turns out it this bit was my error, room was constantly restarting because lives was unset.
Here's the GMX: https://www.speedyshare.com/p2yb2/Penguins.gmx.zip  
I ran Valgrind on it with --leak-check=full -v --track-origins=yes: https://www.speedyshare.com/z8DC8/log.txt and it seemed to throw up a bunch of stuff about the graphics system.  

Edit: The issues have disappeared all of a sudden, I can't get them to reproduce anymore.

**Comment by faissaloo** [comment]
Ok, it started happening again, here's the gmx:  
https://www.speedyshare.com/xcgac/Penguins.gmx.tar.7z  
Here's an executable with debugging symbols:  
https://www.speedyshare.com/UAv7A/egm5754696216842004273.tmp    
It's less prominent in this one but you can see the water textures near the edges of the screen randomly partially appearing and disappearing and the lag is there.  
![](https://i.sli.mg/f60VT1.png)  
The water should not be getting cut off like that, and the point at which it gets cut off is inconsistent on a frame by frame basis.
I've also noticed that the problem gets worse the more copies I have open of the game (this screenshot was taken with 3 open).

**Comment by faissaloo** [comment]
This is caused when a tile is assigned to <no background> by LateralGM. Removing the tiles manually fixes the issue.

**Comment by JoshDreamland** [comment]
Do you have steps to reproduce this problem in a fresh game?

**Comment by faissaloo** [comment]
Create a new background, make it a tileset, make instances of that tile, then delete the background. The effects might not always show though, so you'll probably want to test it in an existing project to see the effects of it.

**Comment by JoshDreamland** [comment]
That's a bug the compiler could have sniffed out. Looking at the compiler module that writes room data, there's currently no error reporting mechanism being passed to that method, so this is a more involved change than I can make from here. I've committed a basic, ugly fix for this problem, less error reporting, in #985. Can you give it a try?

**Comment by faissaloo** [comment]
For some reason I can't reproduce the issue in the game anymore, not even with the gmx files I've previously uploaded.

**Comment by JoshDreamland** [comment]
Well, this bug has appeared transient in the past; if it returns, try that pull request, again.

**Comment by faissaloo** [comment]
Managed to make it appear again, but this time I don't think it has anything to do with the tiles, since I didn't touch tiles this time.

**Comment by faissaloo** [comment]
I believe this may have been an issue on my end with Mir. Closing as such.
