### ISSUE TITLE
Big Problem for All of Us, The Repository Got Rebased

### ISSUE THREAD

**Issue by RobertBColton** [enigma-dev/enigma-dev#990]
@JoshDreamland  Ok guys, we have a huge problem.

Someone rebased our repo. From Dec 29, 2014 to Apr 18, 2016  all commits and PRs have been erased.
https://github.com/enigma-dev/enigma-dev/commits/master

I just noticed this today when looking for why some of my old changes were reverted. It looks like some of sorlok's did too. @faissaloo's int64() function addition just a couple weeks ago got removed too.
https://github.com/enigma-dev/enigma-dev/pull/959

The changes no longer appear on master at all.

**Comment by sorlok** [comment]
This is probably not super-helpful, but I do have a partial copy of master
on my fork of the repo up to ~Jan 2015:
https://github.com/sorlok/enigma-dev

Hope you're all doing well! Been busy with other projects, but it seems
like ENIGMA is doing just fine. Good luck. :)

Seth

**Comment by RobertBColton** [comment]
Thanks sorlok! Looks like Rusky got most of it in #992, but double check anyway.

**Comment by JoshDreamland** [comment]
Indeed; thanks! The commit Rusky made should not have missed anything from before its merge date. It's possible that it missed commits afterward, but I can't find any (or I'd have manually cherry-picked them).
