### ISSUE TITLE
FUCK FUCK FUCK FUCK FUCK FUCK FUCK

### ISSUE THREAD

**Issue by RobertBColton** [enigma-dev/enigma-dev#991]
@JoshDreamland  Ok guys, we have a huge problem.

Someone rebased our repo. From Dec 29, 2014 to Apr 18, 2016  all commits and PRs have been erased.
https://github.com/enigma-dev/enigma-dev/commits/master

I just noticed this today when looking for why some of my old changes were reverted. It looks like some of sorlok's did too. @faissaloo's int64() function addition just a couple weeks ago got removed too. https://github.com/enigma-dev/enigma-dev/pull/959

The changes no longer appear on master at all.

**Comment by faissaloo** [comment]
Wth it's not just master, I literally can't find the int64 function in anything anymore.

**Comment by RobertBColton** [comment]
After #992 I think we are good to go.

**Comment by faissaloo** [comment]
Yeah it's back:  
https://github.com/enigma-dev/enigma-dev/blob/master/ENIGMAsystem/SHELL/Universal_System/mathnc.h#L79
